### ISSUE TITLE
Support pausing emulation

### ISSUE THREAD

**Issue by asturur** [caiiiycuk/js-dos.com#101]
With a combination of keys, dosbox native can pause emulation.
Can we support this too with an api?

**Comment by caiiiycuk** [comment]
Hi yes. This is something what can be easily added.

**Comment by asturur** [comment]
Do you think i can help?

**Comment by caiiiycuk** [comment]
Fixed in [beta.r33](https://github.com/caiiiycuk/js-dos/releases/tag/beta.r33)

**Comment by asturur** [comment]
oh wow! do we have docs on how to do it?
i want to update my small site to use it

**Comment by caiiiycuk** [comment]
Not documented yet, but it's pretty simple:
`ci.pause()`
`ci.resume()`
`ci.mute()`
`ci.unmute()`

**Comment by asturur** [comment]
thank you very much for your work.
