### ISSUE TITLE
Support multiple instances

### ISSUE THREAD

**Issue by asturur** [caiiiycuk/js-dos.com#102]
I'm not sure if this is possible, but i was wondering if Dosbox could become an instance and we could start multiple instances of it on the same page, and writing code to bind keypress to one or more instances.

**Comment by caiiiycuk** [comment]
Hi. js-dos already sandboxed and you can run multiple instances. Check this https://js-dos.com/6.22/64k/index.html. However, 6.22 works only in browser thread, so many instances will hangs browser.

This problem already solved in v7 (that not production ready). v7 uses worker for each instance, so emulation and browser ui works normally.

**Comment by caiiiycuk** [comment]
For example here
https://js-dos.com/v7/build/docs/estimating-performance

if you press `Start` button multiple times you will see parallel output from multiple dosbox instances.

**Comment by asturur** [comment]
Hi Aleksander, thank you for replying so quickly to all my questions.

I tried to give a look on how the event listener for keyboard to one
instance or another but using js-dos package isn't clear. Any idea?

I have been running 4 digger instances with cycles 400 and was ok.
