### ISSUE TITLE
Now used on DOSGames.com

### ISSUE THREAD

**Issue by dhewer** [caiiiycuk/js-dos.com#103]
Hiya, thank you for creating js-dos. I just replaced the older implementation of DOSBOX on DOSGames.com with js-dos. It seems to be working great so far. If you want to add a link from the "Clients" section of the doc I'd appreciate it. Thanks again for your work on this project.

**Comment by caiiiycuk** [comment]
Thanks, I will add it on next update.

**Comment by caiiiycuk** [comment]
Done!
