### ISSUE TITLE
Audible noise-like sound at startup

### ISSUE THREAD

**Issue by SenhorFlibble** [caiiiycuk/js-dos.com#105]
This is an issue that happens both on the Dosify test page and at DOS Games Archive, at least in Chrome. I tested this on two machines with similar results.

After JS-DOS loads the files and the DOS screen appears as a game starts, a brief but very unpleasant noise can be heard. I ran multiple tests and discovered that for whatever reason, the quality and volume of said noise seems to depend on the ZIP file size (but not on compression rate or the size of the unpacked files), with files in the range from about 2 MiB to 2.9 MiB giving the quietest, least noticeable noise similar to faint clicking, but everything above or below that range usually results in a rather loud, grating noise.

Compare [Doom Shareware](https://www.dosgamesarchive.com/play/doom/) (2.32 MiB ZIP) and [Bedlam Demo](https://www.dosgamesarchive.com/play/bedlam/) (5.10 MiB ZIP).

**Comment by caiiiycuk** [comment]
Seems fixed in v7. You can try [here](https://dos.zone/en/studio). Unfortunately I can't say when v7 will be released. But I will not update 6.22 anymore.

**Comment by SuperSteve9** [comment]
Is there a way to fix this in v6.22?

**Comment by caiiiycuk** [comment]
It can be fixed, but no time to do this. (
