### ISSUE TITLE
DOS program not running

### ISSUE THREAD

**Issue by fernandoBranqs** [caiiiycuk/js-dos.com#106]
Hi

My DOS program is not running with js-dos. I dont know why. Follow what i did:

1. I have uploaded the file 20000100.zip to the www.branqs.com.br/simulador
2. I have created the "simulador.html" page according the instructions

Opening the page:

http://www.branqs.com.br/simulador/simulador.html

I can see the image:

![image](https://user-images.githubusercontent.com/68825355/90400754-5202d680-e073-11ea-8943-5d153fd91220.png)

Clicking to start, appears:

Initializing DOSBOX
Launching 20000100.EXE

But , after that, shows the following page:

![image](https://user-images.githubusercontent.com/68825355/90400881-8bd3dd00-e073-11ea-96a4-7690a56b5d1d.png)

Could you help me ?

I left the files on the server for your evaluation.

Thank you very much.

Fernando

**Comment by caiiiycuk** [comment]
Hi. Code that you used is from old version of js-dos. Please update sources to js-dos 6.22 as described [here](https://js-dos.com/#js-dos-622-how-it-works)

**Comment by caiiiycuk** [comment]
Closed due innactivity
