### ISSUE TITLE
IPX support?

### ISSUE THREAD

**Issue by paul-goodall** [caiiiycuk/js-dos.com#108]
This is an amazing project - I've used it to bring one of my favourite games back to life with family during COVID.

I know you are working on lots of enhancements - do you know if/when the IPX component will be available?
It's my favourite feature of DOSBox - being able to connect to others via IPXNET and NETBIOS.

Currently I just get:

C:\>IPXNET STARTSERVER
Illegal command: IPXNET

I'm guessing this is one of the dosbox "extras" that aren't included yet.
If this is made into a future "enhancement" - can you give me some tips on how you might do this with the latest version of dosbox with IPXNET included?  (I'm assuming Emscripten is required)

**Comment by caiiiycuk** [comment]
Hi. Thanks you for interest. The IPX support is thing that we always want to have, but didn't tried yet. Browsers does not support IPX so you should emulate it through WebSockets or something else. So I think enabling IPX in browser requires a lot of work, but it seems doable.

**Comment by paul-goodall** [comment]
That sounds difficult - very interesting though.
Do you think it is something that might be solved this year?

**Comment by caiiiycuk** [comment]
Hi. I have some ideas on how to do it, but I'm not sure about the timings for now because I have more urgent tasks. ;)

**Comment by paul-goodall** [comment]
Ok well good luck Aleksander - this is a great project 😀

**Comment by PokeyManatee4** [comment]
Same I Want To Play Doom With My Friend Using JS-Dos Because I Use A Chromebook And He Uses The Os Called Kubnutu

**Comment by PokeyManatee4** [comment]
But There Is No IPX

**Comment by paul-goodall** [comment]
It is available with the latest version of Dosbox I think. It also works really well with dosbox-staging if you manage translate that to JavaScript 😉

**Comment by PokeyManatee4** [comment]
im not good at javascript

**Comment by caiiiycuk** [comment]
It will be supported at some moment, but not in priority list sorry.

**Comment by PokeyManatee4** [comment]
k

**Comment by PokeyManatee4** [comment]
#what about in v7

**Comment by PokeyManatee4** [comment]
`<!----- Copy and Paste This Code Into Your Post ----><h3>Infographic Name</h3><a href="http://www.domain.com/your-post" target="_blank" rel="noopener"><img src="data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20viewBox='0%200%20700%200'%3E%3C/svg%3E" alt="Name of infographic or image" width="700px" data-lazy-src="http://www.domain.com/image.jpg" /><noscript><img src="http://www.domain.com/image.jpg" alt="Name of infographic or image" width="700px" /></noscript></a><br /><p><a href="http://www.domain.com" target="_blank" rel="noopener">eg: Infographic By Domain.com</a></p></textarea>`

**Comment by caiiiycuk** [comment]
Done. [Docs](https://js-dos.com/v7/build/docs/cloud/networking)

**Comment by paul-goodall** [comment]
Hi @caiiiycuk - I'm a little confused about the Docs.  
You mention to add  `ci.networkConnect(NETWORK_DOSBOX_IPX, "ws://127.0.0.1", 1901);`   for Local IPX server connections.  Where do you put this?  Inside `Dos(document.getElementById("jsdos"), { ...})` ?

Also `please checkout js-dos ipx server and start it` - how do I start a server?

Currently I have this:
```
Dos(document.getElementById("jsdos"), { wdosboxUrl: "/wdosbox.js" }).run("bundle.jsdos");
```

**Comment by caiiiycuk** [comment]
Hi @paul-goodall, you should do like this:
```ts
const ci = await Dos(<...>).run(bundleUrl);
ci.networkConnect(NETWORK_DOSBOX_IPX, "ws://127.0.0.1", 1901);
```

Regrarding to ipx server, I didn't published it yet,  I am preparing it.

**Comment by paul-goodall** [comment]
Hmm.  When I change from this:

```javascript
Dos(document.getElementById("jsdos"), { wdosboxUrl: "/wdosbox.js" }).run("homm1and2.jsdos");
```

to this:

```javascript
const ci = await Dos(document.getElementById("jsdos"), { wdosboxUrl: "/wdosbox.js" }).run("homm1and2.jsdos");
ci.networkConnect(NETWORK_DOSBOX_IPX, "ws://127.0.0.1", 19901);
```

Nothing loads and I get a blank screen.
