### ISSUE TITLE
Error when extracting zip archive

### ISSUE THREAD

**Issue by ghost** [caiiiycuk/js-dos.com#109]
When I try to run JS-DOS, the zip archive downloads just fine, but throws an error when extracting, even though the html file has the correct name of the archive.
VM12: extract-zip: can't open zip archive 'archive.zip': Not a zip archive
index.html: Uncaught (in promise) Can't extract zip, retcode 1, see more info in logs

**Comment by caiiiycuk** [comment]
Please provide you zip archive, or url to page to test. Thanks

**Comment by ghost** [comment]
Wait, first, can JS-DOS only run games? Because if it can only run games then that's the problem.

**Comment by ghost** [comment]
Also, are the .js files portable, or do I have to Bootstrap again for a new zip archive?

**Comment by ghost** [comment]
> Please provide you zip archive, or url to page to test. Thanks

Here's the [link](https://knucklehead-mcspazatron.github.io/Win95-JS/).

**Comment by caiiiycuk** [comment]
>Also, are the .js files portable, or do I have to Bootstrap again for a new zip archive?

You can download release from [releases page](https://github.com/caiiiycuk/js-dos/releases)

**Comment by caiiiycuk** [comment]
From you [link](https://knucklehead-mcspazatron.github.io/Win95-JS/windows95.zip) the zip archive is not actual archive it is just a text file with this contents:
```
version https://git-lfs.github.com/spec/v1
oid sha256:1f496c8d6b59e9c0fd1a3cedea1befd0f8117ee4d630bd54d9f76243cd9ed9f3
size 230870471
```

Please check your server config.

**Comment by ghost** [comment]
Yeah, I pushed the zip using Git LFS, that must've had something to do with it. Thanks!
