### ISSUE TITLE
Problem with the web emulator

### ISSUE THREAD

**Issue by rrodrigofranco** [caiiiycuk/js-dos.com#111]
Hello, how are you?
I tried to put a different DOS game on the emulator, but I was unsuccessful. Can anybody help me? Below is my code:

```
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>js-dos 6.22, 4D-PRINCE</title>
  <script src="https://js-dos.com/6.22/current/js-dos.js"></script>
  <style>
    html, body, canvas, .dosbox-container {
      width: 100%;
      height: 100%;
      margin: 0;
      padding: 0;
      overflow: hidden;
    }
  </style>
</head>

<body>
  <canvas id="jsdos"></canvas>
  <button style="position: absolute; right: 1em; top: 1em;" onclick="ci.fullscreen()">Fullscreen</button>
  <script>
    Dos(document.getElementById("jsdos"), { 
      wdosboxUrl: "https://js-dos.com/6.22/current/wdosbox.js",
      cycles: 1000,
      autolock: true,
    }).ready(function (fs, main) {
      fs.extract("https://sites.google.com/site/negocindosica/4D.zip").then(function () {
        main(["-c", "4D_PRIN.EXE"]).then(function (ci) {
          window.ci = ci;
        });
      });
    });
  </script>
</body>
</html>
```

**Comment by caiiiycuk** [comment]
Is it same as 
http://inflacaobr.000webhostapp.com/4d_prince.html ?
It works for me

**Comment by caiiiycuk** [comment]
Do you have any errors? Anything?
![изображение](https://user-images.githubusercontent.com/1727152/98470390-d3ec4100-2217-11eb-9a9b-e519d81af9d6.png)

**Comment by rrodrigofranco** [comment]
@caiiiycuk yes. Work to me too, but I can't move the prince

**Comment by caiiiycuk** [comment]
Yep, I know this bug is confirmed fo js-dos 6.22 can you try js-dos 7. Just go here https://dos.zone/en/studio, upload archive and press next until the end. I can't do this because I don't have Czech keyboard

**Comment by rrodrigofranco** [comment]
@caiiiycuk Can you help me pass the code to js-dos 7? Because I would like to put these games on my website

**Comment by caiiiycuk** [comment]
It's pretty simple if you have *.jsdos file, read more https://js-dos.com/v7/build/docs/. Anyway I need to know is this bug exists on v7?

**Comment by caiiiycuk** [comment]
https://discord.com/invite/hMVYEbG is better place for quick help

**Comment by rrodrigofranco** [comment]
@caiiiycuk Nice. Regarding the keyboard, in my case, I use the Brazilian keyboard, would you know to tell me where I should change the code to make the game keyboard work correctly?

![image](https://user-images.githubusercontent.com/16249363/98470874-526cc280-21c7-11eb-8fa1-d6a70abbb9dd.png)

**Comment by rrodrigofranco** [comment]
@caiiiycuk I'll enter in the discord. 
Could you take a curiosity out of me? You are Russian, right? Which city in Russia do you live in?
