### ISSUE TITLE
Typing in any window types in them all

### ISSUE THREAD

**Issue by DustinBrett** [caiiiycuk/js-dos.com#113]
I am using the latest v7 beta and continue to notice that if I have 2 instances of js-dos open, typing anything into one will type into any other open one.

**Comment by caiiiycuk** [comment]
Sounds like error. Will check it.

**Comment by caiiiycuk** [comment]
Works fine for me (v7.4.7): https://js-dos.com/v7/build/examples/multiple-instances.html

**Comment by DustinBrett** [comment]
I was able to run Doom and a js-dos console at the same time and indeed the problem seems solved. But a new issue I had with the latest code is that if I try and run Doom and Jazz Jackrabbit it will crash Jazz with `[LOG_SB]DSP:Reset`. I will play around with it more and possibly create an issue if it persists.

**Comment by DustinBrett** [comment]
It seems that it wasn't crashing but was instead resizing to 0x0 because for some reason the 2nd instance of js-dos is creating 2 canvas elements, and the first element has no defined height/width which I had been using to do window adjustments. I will focus on the last canvas to fix my issue but I am not sure if this 2nd canvas element is a js-dos thing or something my messed up code is adding. I don't see it in the example you posted so I will try and track that down. Otherwise it does indeed seem to run multiple instances now, nice! Thanks!
