### ISSUE TITLE
Maybe Js-DOS File Saves

### ISSUE THREAD

**Issue by PokeyManatee4** [caiiiycuk/js-dos.com#114]
File Type Will Be .JS_SAVE

**Comment by lc67846** [comment]
Anyone?

**Comment by caiiiycuk** [comment]
Hi @lc67846. What do you mean? Join our discord to fast communication https://discord.com/invite/hMVYEbG

**Comment by PokeyManatee4** [comment]
like fike saves

**Comment by PokeyManatee4** [comment]
file saves

**Comment by caiiiycuk** [comment]
Sorry, still does not understand you. You want to have additional files ‘js_save’ that will act as saved games? Currently you already can save and load game progress with v7

**Comment by PokeyManatee4** [comment]
Yes With A Import

**Comment by caiiiycuk** [comment]
I added export function to dos.zone. Now you can download bundle with saves using download button:
![image](https://user-images.githubusercontent.com/1727152/104114960-c436c900-533c-11eb-9c2b-e150f4f6ad5f.png)
