### ISSUE TITLE
Correct way to dispose of js-dos and all listeners

### ISSUE THREAD

**Issue by ianharrigan** [caiiiycuk/js-dos.com#115]
Hi there!

Great project! Works really well and the interface is nice and simple. I do have a question however - im creating a canvas dynamically and showing that in a popup (html popup, not a new window) and using that to start the js-dos box - that all works fine. However, i would like to destroy this instance (and any event handlers) once the popup is closed. Any ideas one how to do this? Ive tried to just .remove the canvas, but after showing a few jsdos gets verrrry slow, indicating that it hasnt properly unloaded something. 

Thanks in advance,
Ian

**Comment by caiiiycuk** [comment]
Hi, thank you for interest. If you use v7 it should be simple: call ci.exit()

**Comment by ianharrigan** [comment]
Thanks for the quick reply, im using v6 as it seems v7 isnt ready? Will ci.exit work there, as i get: 

```
===> [ERROR] Runtime is still alive
```

Would you advise to use v7 then?

Cheers,
Ian

**Comment by caiiiycuk** [comment]
Yep, but 6.22 have this problem. It’s not possible to exit correctly. I hope to release v7 in end January

**Comment by ianharrigan** [comment]
Right, gotcha... ill try v7 and see what happens... many thanks for the quick replies!
