### ISSUE TITLE
Program freezes in v7 without initial "pause" command

### ISSUE THREAD

**Issue by ArmstrongJ** [caiiiycuk/js-dos.com#117]
I'm trying to experiment with v7, specifically on [dos.zone](https://dos.zone/en/studio) before committing too much more time, and I'm running into an issue running a simple program.  If the program is executed in the bundle via .jsdos/dosbox.conf autoexec section, the program freezes upon execution.  However, simply adding a "pause" command prior to running the program allows everything to work.  I've attached two jsdos bundles, one that works by having an initial "pause," and one that does not because it executes the program "tgt.exe" without any initial user interaction.

I'm baffled as to why this is the case.  Any thoughts?

[broken.zip jsdos bundle that doesn't run](https://github.com/caiiiycuk/js-dos/files/5815409/broken.zip)
[pauseworks.zip jsdos bundle that does run](https://github.com/caiiiycuk/js-dos/files/5815414/pauseworks.zip)

Please note that these bundles were created using Game Studio over on dos.zone.

**Comment by caiiiycuk** [comment]
Hmm I recently updated dos.zone to latest emulator, and now both files does not work. I will investigate this and back to you soon. Thanks!

**Comment by caiiiycuk** [comment]
Now fixed in emulators/0.0.42 and js-dos/r25 you can download it in Releases page. Now it works on Dos.Zone as well. Please reopen issue if you still have problems.
