### ISSUE TITLE
React v7

### ISSUE THREAD

**Issue by kristianstroka** [caiiiycuk/js-dos.com#118]
Is it now somehow possible to run js-dos with React including Typescript? I cannot figure it out, and documentation is poor about this... I would like to modify all stuffs on react side (meaning keyboard mapping, customisation, etc), it is even possible?

**Comment by caiiiycuk** [comment]
Hi. Yep still have no time to document it. But it works completely fine, dos.zone is on React

**Comment by kristianstroka** [comment]
Can you share your component where are you using js-dos, so I can inspire? :)

**Comment by caiiiycuk** [comment]
It have too much logic, I need to write simple example.

**Comment by caiiiycuk** [comment]
https://js-dos.com/v7/build/docs/react/
