### ISSUE TITLE
Different usage

### ISSUE THREAD

**Issue by GerhardKreuzer** [caiiiycuk/js-dos.com#12]
Hi,

is it possible to use this to have a simple terminal window, in/out to/from a web Service?
Sorry, no gamer.

With best regards

Gerhard

**Comment by caiiiycuk** [comment]
Hi. I don't understand your request. This api works only in browser, in javascript environment.

**Comment by GerhardKreuzer** [comment]
Yes, but it is a DOS box and I only Need a terminal.
