### ISSUE TITLE
How to know the Dosbox exit

### ISSUE THREAD

**Issue by xsro** [caiiiycuk/js-dos.com#124]
When type `exit` and press <kbd>enter</kbd>, the dosbox canvas will stop and a message `SDL_Quit called` will be logged to console. Is there a way to know the dosbox has exited via javascript?

**Comment by caiiiycuk** [comment]
Hi. Currently there is no way to be notified when dosbox is exited. However you can call `ci.exit()` which returns the promise when dosbox is ended.

Anyway it's good to add this "exit" event. I will do it. I am curious where you want to use it?

**Comment by xsro** [comment]
Thanks very much. I am using JSDos in my VSCode extension to emulate DOS environment for running easy some assembly code.

I find a way to do this via listen `console.log`.[my repo](https://github.com/xsro/masm-tasm), [related codes](https://github.com/xsro/masm-tasm/blob/83af5a567c284e8d0917575d37178c0876ba3384/tools/js-dos/src/main.ts#L162-L178)

**Comment by caiiiycuk** [comment]
Wow, very impressive! Btw, I see that you using js-dos 6.22, is it possible
to you to switch on js-dos 7?

вт, 16 февр. 2021 г. в 10:11, Chen Leoxsro <notifications@github.com>:

**Comment by xsro** [comment]
NICE, I will try to use jsdos7.
