### ISSUE TITLE
Fails to run on Node natively

### ISSUE THREAD

**Issue by WasabiThumb** [caiiiycuk/js-dos.com#126]
**The Problem**:
I can't get this to run on Node natively, that is to say without a browser.

**The Code**:
```
const { JSDOM } = require("jsdom");
window = (new JSDOM(`<!DOCTYPE HTML><html><body><canvas id="dosScreen" width="640" height="480"></canvas></body></html>`)).window;
document = window.document;
XMLHttpRequest = window.XMLHttpRequest;
require("js-dos");

const canvas = document.getElementById("dosScreen");
window.Dos(canvas).ready((fs, main) => {
	console.log("Ready!");
});
```
_Using canvas@2.6.1, jsdos@6.22.59, jsdom@16.4.0_

**The STDOUT**:
```
ERR! Can't initalize cache, cause: Indexed db is not supported on this host

node:internal/process/promises:227
          triggerUncaughtException(err, true /* fromPromise */);
          ^
[DOMException [SyntaxError]: The string did not match the expected pattern.]
```

Thanks for your time.

**Comment by caiiiycuk** [comment]
Hi. If you need execute emulators is node, you definitely need to use emulators package it works fine in node at least in direct mode. 

https://js-dos.com/v7/build/docs/estimating-performance

**Comment by WasabiThumb** [comment]
> Hi. If you need execute emulators is node, you definitely need to use emulators package it works fine in node at least in direct mode.
> 
> https://js-dos.com/v7/build/docs/estimating-performance

Thanks for the reply! Looks interesting, but I see a test script for the web with no image output on this page. I'm probably missing something here, could you elaborate how this could be used in a standard Node environment?

**Comment by caiiiycuk** [comment]
Sure, I will create example asap.

**Comment by caiiiycuk** [comment]
Ok, now works. Read tutorial:
https://js-dos.com/v7/build/docs/node/

Reopen issue if you have any problem.
