### ISSUE TITLE
Enabling and disabling keyboard

### ISSUE THREAD

**Issue by NoordGuy** [caiiiycuk/js-dos.com#129]
JS-DOS 6.22 working great so far for me. Thanks for this amazing project.

However, i would like to disable and enable keyboard input while dosbox is running. Is there any way or workaround to achive that?

**Comment by caiiiycuk** [comment]
Hi. Thanks! Do you want to disable key input **INTO** dosbox while it's running?

**Comment by NoordGuy** [comment]
Yes! Currently everything I type is sent to dosbox, but I want html text inputs besides the emulator canvas that allow for input without the dosbox receiving the key command.

I tried the pause() and resume() functions, but nothing happened.

**Comment by caiiiycuk** [comment]
Did you try to stop [event propagation](https://developer.mozilla.org/ru/docs/Web/API/Event/stopPropagation) on your fields?

**Comment by NoordGuy** [comment]
Yeah, I tried that. The thing is I do not even receive oninput events for my textarea. So I cannot stop event propagation. If I don't load jsbox, it works as expected.

**Comment by caiiiycuk** [comment]
Did you tried `options.capture = true` when adding your listener?

**Comment by caiiiycuk** [comment]
Also you can switch to js-dos v7, and implement your own input system

**Comment by NoordGuy** [comment]
Yes I tried that. I hope this example illustrates my problem. Even if focus is in textarea, I do not receive input event.

[https://pastebin.com/b3n23rdR](https://pastebin.com/b3n23rdR)

**Comment by caiiiycuk** [comment]
Try this:
```
document.addEventListener("keyup", function (event){
            alert("sss");
            event.preventDefault();
        },true);
document.addEventListener("keydown", function (event){
            alert("sss");
            event.preventDefault();
        },true);
```

**Comment by caiiiycuk** [comment]
ahh sorry! we should use ```event.stopPropagation()``` :facepalm:

**Comment by NoordGuy** [comment]
That works! (I use _keypress_ to simulate text input in the textarea.)

**Comment by HunterBoy344** [comment]
Would just like to mention that this solution only worked for me when I added event listeners for _all three_ kinds of keyboard events. So, if @caiiiycuk's solution isn't working for you, try something like this:
```
window.addEventListener('keydown', function(event){
    event.stopPropagation()
}, true);

window.addEventListener('keyup', function(event){
    event.stopPropagation()
}, true);

window.addEventListener('keypress', function(event){
    event.stopPropagation()
}, true); 
```
