### ISSUE TITLE
Games freezes

### ISSUE THREAD

**Issue by digdug82** [caiiiycuk/js-dos.com#13]
I tried it on two games and they both crashed.
The First one is Beneath a Steel Sky and the second one was Horror Zombies from the Crypt , the first one froze in the title screen and the second one frozen in the password screen.
Thanks in advance.

**Comment by caiiiycuk** [comment]
Starting from version 3, this game can be runned in js-dos. Please try: http://js-dos.com/Horror%20Zombies/
