### ISSUE TITLE
expose a FS API to read and write files

### ISSUE THREAD

**Issue by xsro** [caiiiycuk/js-dos.com#130]
Is it possible to expose a fs api to read and write files and can be used when the jsdos is running

**Comment by caiiiycuk** [comment]
Please read this messages about how-to use FS api of emscripten:
https://discord.com/channels/732544419189882890/786612599164895243/811775548002664458

**Comment by matthewturk** [comment]
In case it's helpful, the discussion there led to this: https://github.com/matthewturk/jupyterlab_dosbox/blob/f08f8de012c466b505c6f0dc38a5a48ceebff65d/src/contents.ts

**Comment by xsro** [comment]
Thank you very much. 
I'm trying the react Example，But seems the returned ci does not has the property 'module'?

**Comment by caiiiycuk** [comment]
module only available in direct emulation mode, so you need to change
```
          emulatorFunction: "dosWorker",
```
to
```
          emulatorFunction: "dosDirect",
```

then ci will have module field

**Comment by xsro** [comment]
@caiiiycuk plz take a look to this

I find in the latest version of emulators, this API is not able to get

This is my file for test

```html
<!doctype html>
<html>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <!-- <script src="node_modules/emulators/dist/emulators.js"></script>
    <script src="node_modules/emulators-ui/dist/emulators-ui.js"></script> -->
    <script src="https:/js-dos.com/v7/build/releases/latest/js-dos/js-dos.js"></script>
    <link href="https:/js-dos.com/v7/build/releases/latest/js-dos/js-dos.css" rel="stylesheet">
</head>

<body>
    <div id="jsdos" />
    <script>
        emulators.pathPrefix = "https:/js-dos.com/v7/build/releases/latest/js-dos/";
        async function getandrun() {
            const ci = await Dos(document.getElementById("jsdos"), { emulatorFunction: "dosboxDirect" })
                .run("./digger.jsdos")
            if (ci.module) {
                console.log(ci.module)
            }
            else {
                alert("can't get ci")
            }
        }
        getandrun()
    </script>
</body>

</html>
```
