### ISSUE TITLE
Another site that uses JS-DOS

### ISSUE THREAD

**Issue by deathwombat** [caiiiycuk/js-dos.com#131]
RGB Classic Games (https://www.classicdosgames.com) uses JS-DOS.

**Comment by caiiiycuk** [comment]
Thank you. Will add on site on next deploy!

**Comment by mylann** [comment]
> Thank you. Will add on site on next deploy!

Another site you can add is mine, recently added online games: [Best Old Games](https://www.bestoldgames.net/games/online)

**Comment by caiiiycuk** [comment]
done

**Comment by asturur** [comment]
Not sure if it makes sense, but this small personal site also uses jsdos
https://andrea-childood-games.netlify.app/

**Comment by caiiiycuk** [comment]
> Not sure if it makes sense, but this small personal site also uses jsdos
> https://andrea-childood-games.netlify.app/

Great, will add it to discord!
