### ISSUE TITLE
8-directional movement arrows on mobile

### ISSUE THREAD

**Issue by amecir** [caiiiycuk/js-dos.com#134]
Hey,
thank you for your great work!

I am trying to play Civilization 1 on my mobile phone,  but I have no idea how to add "numeric keyboard" layout because this game (and many others) is using this keyboard (8-directional movement arrows) to move units over the game map.

I can assign these numeric keys to buttons using your builder, but it looks a bit weird. Is there any way how to add this numeric keyboard layout to (for example) the right bottom corner of mobile screen?

Thank you!

**Comment by caiiiycuk** [comment]
Hi. Thank you for interest. Currently I am working on new virtual controls for mobile, especially for games like Civ, C&C, XCom. Please be patient I will publish it soon. 

Unfortunately I can't imagine any workaround for current build.

**Comment by sparkyspider** [comment]
I've written a API to do it. You're welcome to take it.

https://github.com/emergegaming/dosbox-game-api
https://github.com/emergegaming/dosbox-game-api/blob/master/src/index.ts

**Comment by sparkyspider** [comment]
You're welcome to implement the screen controller I created at:

https://github.com/emergegaming/dosbox-game-api/blob/master/src/index.ts -> handleTouchEvent(...)

This maps 8 directions to 4 keys (as in up and right can be pressed simultaneously) but doesn't map to keypad keys. You can refactor this to map the keycodes using numpad1 through numpad9.

KeyCodes: https://www.cambiaresearch.com/articles/15/javascript-char-codes-key-codes

Cheers,

**Comment by caiiiycuk** [comment]
Now you can build such control with [Nipple Activator](https://js-dos.com/v7/build/docs/mobile-support#nipple-activator-control)
