### ISSUE TITLE
[js-dos v7 beta 30] sound hiccups in Chrome

### ISSUE THREAD

**Issue by maximilien-noal** [caiiiycuk/js-dos.com#135]
While js-dos v7 fixes the controls problem in Chrome with Prince of Persia, and the high-pitched sound in Another World (both problems are from js-dos v6.22), I can't fix this no matter what setting I try.

The js-dos bundle this can be tested are below (Another World, Prince of Persia)

In Firefox, the sound is fine.

[AnotherWorld.jsdos.zip](https://github.com/caiiiycuk/js-dos/files/6370117/AnotherWorld.jsdos.zip)
[PoP.jsdos.zip](https://github.com/caiiiycuk/js-dos/files/6370118/PoP.jsdos.zip)

Thank you again for this awesome emulator !

**Comment by caiiiycuk** [comment]
Can you record an example how it sounds like? Anyway I will replace audio library soon.

**Comment by maximilien-noal** [comment]
Will do (soon) !

**Comment by maximilien-noal** [comment]
Here it is for Another World with Chrome :

https://www.youtube.com/watch?v=_Qn2WfN1YAE

I can upload the result with Firefox or anything else that might help. Just ask ! :)

My system:
Intel Core i7 6700K @ 4 GHz
Windows 10 x64
nVidia GeForce GTX 1070

**Comment by maximilien-noal** [comment]
Do you need more information or videos ?

**Comment by caiiiycuk** [comment]
No thanks, I think I will try to fix it on next week

**Comment by caiiiycuk** [comment]
This is tricky. possible solution here is to create AudioWorklet and send data to it using MessagePort.

**Comment by maximilien-noal** [comment]
Curious to know if this is fixed in the latest v7 releases ?

**Comment by caiiiycuk** [comment]
Not yet

**Comment by caiiiycuk** [comment]
@maximilien-noal do you hear any sound differences between this versions:
https://dos.zone/out-of-this-world-1992/
https://dos.zone/out-of-this-world-1992/?direct=1
https://shd.dos.zone/out-of-this-world-1992/

**Comment by maximilien-noal** [comment]
Test browser: Chrome (Version 99.0.4844.74)
Same hardware config as above.

First one : moderate and constantly present sound hiccups.
Second one : exact same thing
Third one : exact same thing,
