### ISSUE TITLE
[js-dos v6 and v7] No sound nor music in Transport Tycoon Deluxe

### ISSUE THREAD

**Issue by maximilien-noal** [caiiiycuk/js-dos.com#138]
Regular DOSBox has sound and music.

Default settings all around, both for regular DOSBox and JS-DOS :
- sbtype=sb16
- irq=7
- dma=1
- cycles=auto
- cputype=auto

The game was taken from an already working DOSBox 0.74 installation.

A lot of other games are affected by this bug, such as:
- Sim Farm (sound present, but no music)
- others that I can't recall right now.

Tested with:
- js-dos 6.22.40
- js-dos 6.22.60
- js-dos v7b30

Browsers used for tests:
- Firefox (desktop)
- Chrome (desktop)
- Edge (desktop)

**Comment by caiiiycuk** [comment]
Wow, interesting will look into it

**Comment by maximilien-noal** [comment]
Thank you very much. If you need more info, just ask !

**Comment by maximilien-noal** [comment]
Same with Capitalism.
No music once it's run by js-dos v6. To be tested with v7.
Default settings (sblaster, irq, dma, cputype and cycles), as above.

**Comment by caiiiycuk** [comment]
Just tried, sounds works for me, but mouse not, please check this bundle:

https://talks.dos.zone/t/transport-tycoon-deluxe-1995/6695
