### ISSUE TITLE
Pausing DosBox?

### ISSUE THREAD

**Issue by therealbnut** [caiiiycuk/js-dos.com#139]
Hey,

I'm trying to pause DosBox's main loop while I'm not using it, but `ci.dos.pause()` doesn't seem to work (it's calling existing event listeners, but doesn't seem to affect DosBox).

A [closed issue](https://github.com/caiiiycuk/js-dos/issues/101) seems to indicate something like that is meant to work, but it looks like it doesn't anymore.

I'm not very familiar with the source code, but `emscripten_pause_main_loop` or `PauseDOSBox` in C++ look promising.

Am I missing something?

Thank you :)

**Comment by caiiiycuk** [comment]
Hi, issue that you referred is about jsdos v7. pause/resume   is supported only in v7 out of the box.

**Comment by therealbnut** [comment]
Ah ok, if I can work out how to implement it would it be a welcome contribution? Any suggestions for how you’d want to go about it and expose it in the API?

**Comment by therealbnut** [comment]
Oh wait sorry, v7 is the next release, I’ll use that then thank you :)
