### ISSUE TITLE
[Js-Dos 7][Feature Request] Disable all elements that are not <canvas> in canvasContainer

### ISSUE THREAD

**Issue by markemerge** [caiiiycuk/js-dos.com#140]
![image](https://user-images.githubusercontent.com/78346176/124944153-61816a00-e00d-11eb-9309-6d486a768c31.png)

It would be ultra useful to be able to disable all the overlays that go with Js-Dos 7 and ideally just supply a canvas element to JS-DOS-7

**Comment by markemerge** [comment]
I'd also like to know if there are processes associated with these elements that are running in the background using resources and if those processes can be shut down to achieve maximum performance.

**Comment by caiiiycuk** [comment]
Yeah, but what about mouse clicks, keyboard support etc? They are implemented using this overlays

**Comment by matthewturk** [comment]
@caiiiycuk I could see this being useful for automated runs, or where any type of input interposition was necessary.  Or maybe for demoscene stuff?

**Comment by markemerge** [comment]
> Yeah, but what about mouse clicks, keyboard support etc? They are implemented using this overlays

We've implemented our own drop joystick (AntStream style), our own onscreen controls, the Gamepad API, keyboard listeners, etc, so have no need for the built-in ones.

We're really just after the emulator and the ci. 

I'd love to show you what we've been up to.We've got some pretty neat things going. May be nice to share it with the community.

**Comment by caiiiycuk** [comment]
I still didn't get the difference between using `only emulators + custom ui` vs `emulators + emulators-ui - overlays`. I think it's something like reconfiguration of emulators-ui that provides only canvas + sound, however it looks like very special case.
