### ISSUE TITLE
[Js-Dos 7]: How to send ASCII Event Keycodes to the CommandInterface

### ISSUE THREAD

**Issue by markemerge** [caiiiycuk/js-dos.com#141]
In Js-Dos 6.22 we used to send ASCII events to DOS

```javascript
ci.simulateKeyEvent(13, true);  // Press Enter
ci.siluateleKeyEvent(13, false);  // Release Enter
```

I now see that Js-Dos 7 is remapping them to some other format, so we've now need to create a mapping converter to map the keycode to the Js-Dos mapping, so so that Js-Dos mapping can map it back to the original ASCII Keycode.

Is there a way we can send plain ASCII codes to the ci?

Thanks,

**Comment by caiiiycuk** [comment]
Hi. Mapping is already there, read this
https://github.com/caiiiycuk/js-dos/issues/120#issuecomment-813156335

**Comment by caiiiycuk** [comment]
@markemerge 

From MDN:
![изображение](https://user-images.githubusercontent.com/1727152/125276573-93ab0880-e33a-11eb-85e5-881da5dc3011.png)

`keyCode` is **deprecated** and  **implementation dependent numerical code**. So it not true that keyCode is a ASCII code it can be **Windows-1252** for example. 

Even more DOSBOX itself does not use ASCII codes internally:
![изображение](https://user-images.githubusercontent.com/1727152/125276899-f7cdcc80-e33a-11eb-97c9-d207d4946d14.png)

As you can see 'Enter' is 28 not 13. So, I think this layer of mapping is needed.
