### ISSUE TITLE
UI, mobile: disabling mouse

### ISSUE THREAD

**Issue by Ser-Gen** [caiiiycuk/js-dos.com#144]
In Supaplex a mouse emulation is necessary to use in menu.
But in the game process a mouse click explodes a player.

On mobile you need to press on-screen buttons very careful, every sloppy move will be punished!

Looks like the UI needs a button to disable the mouse emulation, same button as is for a keyboard.

https://talks.dos.zone/t/supaplex-1991/6206/2?u=sergen

https://user-images.githubusercontent.com/1856145/129186118-58dd15a6-75f2-4bbf-b0de-6bf7728b020a.MP4

**Comment by caiiiycuk** [comment]
Nice catch! Will do it
