### ISSUE TITLE
UI: canvas is too blurry

### ISSUE THREAD

**Issue by Ser-Gen** [caiiiycuk/js-dos.com#145]
Canvas is blurred. Not DOS enough.
Screenshots are from desktop Chrome but blur is noticeable even on mobile.
Firefox supports `image-rendering: crisp-edges`, but current `image-rendering: "crisp-edges"` is not works too.

Is there any limitations that prevented use of `image-rendering: pixelated`?

| current | `image-rendering: pixelated` |
| --- | --- |
| ![image-rendering: pixelated](https://user-images.githubusercontent.com/1856145/129197721-146c307e-ae69-47cb-b0f7-176aa26ae6f6.png) | ![current ](https://user-images.githubusercontent.com/1856145/129197714-ab927022-21ac-4849-8f55-95c9ee4be04e.png) |

**Comment by caiiiycuk** [comment]
Hi. Just forgot to do it, will add `image-rendering: crisp-edges` in css rules for jsdos

**Comment by Ser-Gen** [comment]
Looks like Chrome needs `pixelated`.
https://caniuse.com/css-crisp-edges

**Comment by maximilien-noal** [comment]
Firefox -> crisp-edges
Everyone else, including Chrome-> pixelated.
I worked on it a lot when integrating js-dos 6.22. Full example :


```

<style>
  canvas {
    min-width: 40vw;
    min-height: 30vw;
    image-rendering: pixelated;
}
</style>
<p>
<canvas id="jsdos"></canvas>
<script type="text/javascript">
var isFirefox = navigator.userAgent.toLowerCase().indexOf('firefox') > -1;
if(isFirefox)
{
  document.getElementById("jsdos").style.imageRendering = "crisp-edges";
}
</script>
<script type="text/javascript">
function goFull() {
  if(!document.onfullscreenchange) {
    document.onfullscreenchange = function ( event ) {
      if (!(document.fullscreenElement || document.mozFullScreenElement || document.webkitFullscreenElement)) {
        canvas.style.width = "40vw";
        canvas.style.height = "30vw";
      }
      else {
        canvas.style.width = "auto";
        canvas.style.height = "100%";
      }
    };
  }
  ci.fullscreen();
}
</script>
<button class="btn_play" onclick="goFull();">fullscreen</button>
</p>
<script type="text/javascript" src="/lib/js-dos.js"></script>
<script type="text/javascript">
        var canvas = document.getElementById("jsdos");
        var wDosUrl = "/lib/wdosbox.js";
        Dos(canvas, {
                cycles: 3000,
                autolock: true,
		log: (message) => {},
		onerror: (message) => {},
		wdosboxUrl: wDosUrl
	}).ready((fs, main) => {
		fs.extract("https:/mysite.com/DOOM.zip", "/DOOM").then((ci) => {
			main(["-c", "cd DOOM", "-c", "DOOM"]).then((ci) => {
				window.ci = ci;
			});
		});
	});
</script>

```
