### ISSUE TITLE
Mobile, UI, keyboard: emulated keyboard with custom layout

### ISSUE THREAD

**Issue by Ser-Gen** [caiiiycuk/js-dos.com#146]
I need a Russian keyboard in this game to enter a word but I got only English layout on mobile.
https://talks.dos.zone/t/pole-chudes-capital-show-1993-ru/12311/2

Maybe in the Studio should be a layer with customizable layout of keyboard.

**Comment by caiiiycuk** [comment]
This is problematic, dosbox does not operate with letters only key codes. So Russian letters mapping depends on game and driver like keyrus.

**Comment by Ser-Gen** [comment]
I looked at the problem more closely. it seems that my description of the problem was not accurate.

The layout on hardware keyboard is correct. Even no need to switch it anywhere.
Emulated keys are also correct: key `s` becomes `ы` in game.
But labels of buttons on emulated keyboard are latin.

Maybe it's enough to add a switch to change labels of the keys?
