### ISSUE TITLE
Game Studio: Program terminated with exit(101) undefined

### ISSUE THREAD

**Issue by melissamcewen** [caiiiycuk/js-dos.com#148]
Hi, I would like to create a bundle for the game OddBallz. I have a Dosbox, but I'm not sure how to convert it. I tried using the Game Studio but all the executables I tried give me a "Program terminated with exit(101) undefined" error. 
![CleanShot 2021-08-16 at 20 40 08@2x](https://user-images.githubusercontent.com/1251094/129650060-34f4c29c-ea12-4a93-8d9b-d2e797afe4c2.jpg)

The example game (Digger) works fine so maybe I'm selecting the wrong file? The game I'm using is here: http://kutheraver.com/acidtrip/files/installers/Oddballz%20Installers.rar

I tried both the "Native Disc" and "Dosbox" versions. Thanks!

**Comment by Ser-Gen** [comment]
I have same error with russian version of Warcraft from here.
https://www.old-games.ru/game/download/72.html

Could it be possible because of size of game archive? Size of my archive is 58 MB.

**Comment by caiiiycuk** [comment]
No this is an asyncify error, some function not in asyncify list. I will look it at Monday

**Comment by caiiiycuk** [comment]
@Ser-Gen warcraft works for me... When you have this error?

**Comment by caiiiycuk** [comment]
@melissamcewen can you provide js-dos file that throws this error?

**Comment by Ser-Gen** [comment]
@caiiiycuk I use russian version from here
https://www.old-games.ru/game/download/72.html

Error is shown after clicking on Create archive on step 3/4.

**Comment by caiiiycuk** [comment]
Seems that this error is happened after pressing `Create archive` button, during bundle creation.

**Comment by beldog** [comment]
I got same error code when creating the bundle.. then I realised that the ZIP file got first a folder containing all DOS files within, so I move all the files back to the root of the ZIP (no folder), and it worked like a charm. Your error could be the same or not, just giving you some input.

**Comment by caiiiycuk** [comment]
Fixed
