### ISSUE TITLE
optionalChangesUrl is appending `?dt=`

### ISSUE THREAD

**Issue by DustinBrett** [caiiiycuk/js-dos.com#149]
I've setup loading of game saves via the `optionalChangesUrl` argument on `dosInstance.run`. But I've had to modify the lib as it kept adding what I assume is a cache busting param of `dt` (https://github.com/js-dos/emulators-ui/blob/main/src/js-dos.ts#L170) to the url which wasn't working for a buffer url (`createObjectURL`) for me locally.

Any suggestions of a better way I can avoid this issue?

**Comment by caiiiycuk** [comment]
Hi. You right/ I think I will remove dt in next version. Client should add it if it needed.
