### ISSUE TITLE
Add saving feature

### ISSUE THREAD

**Issue by digdug82** [caiiiycuk/js-dos.com#15]
Please add a saving feature Similar to Jdosbox.
Basically make it download the files in a temporary folder in the windows /mac user profile, when the user close /open the page and enter a new session to run a game /app it should check for the folder if it exist then it run the saved app , If not it has to download it.
this will give the user the ability to save his progress/setting.

**Comment by Balrog85** [comment]
I know I'm bumping an old topic, but I believe there are now ways to set up persistence with em-dosbox, so maybe this is possible now?  If so, I would love for this feature to be added, since I have several games running through js-dos on my site, that could really do with offering the ability to save between logins.

**Comment by caiiiycuk** [comment]
Yes it is possible. Even more I think it is not hard to do. Btw, I does not have free time to do it. I add this feature asap.

**Comment by Balrog85** [comment]
That would be amazing.  Thank you and no rush :)

**Comment by x-wolverine-x** [comment]
Any possibility to get this working? I would be very happy to get this done, without this feature "dos-games-on-web" make no fun.

**Comment by caiiiycuk** [comment]
Yes it is possible, I have plans to do this

ср, 22 авг. 2018 г. в 22:40, x-wolverine-x <notifications@github.com>:

**Comment by x-wolverine-x** [comment]
You know when, because it's older then 2 years for now?

**Comment by ken107** [comment]
I got it to work using Emscripten's File System API to get the game's save files out of DosBox:
`var saveFiles = dosbox.getSaveFiles(glob)`

Then using JSZip to inject the save files during DosBox initialization:
`dosbox.run(--, --, {saveFiles: saveFiles})`

It's possible to use File System API's `writeFile()` to put the save files into DosBox, but DosBox doesn't "see" the files until a refresh (CTRL-F4 or the RESCAN DOS command).  And I don't know how to trigger that programmatically.  That would avoid having to use JSZip.

Example on my website: https://lsdsoftware.com

**Comment by caiiiycuk** [comment]
I am not sure what you mean. Yes you can use writeFile to implement stateful FS, you can use autoexec section of dosbox config to trigger RESCAN command.

**Comment by ken107** [comment]
You're right.  I try using `writeFile` right after mounting the archive, and it works fine!  Thanks.

**Comment by x-wolverine-x** [comment]
Any update @caiiiycuk ?

**Comment by caiiiycuk** [comment]
Yes, I implemented permanent storage based on idexeddb, but still not in production

**Comment by x-wolverine-x** [comment]
> Yes, I implemented permanent storage based on idexeddb, but still not in production

I hope it will be in production soon, then I will give it another try :-)

**Comment by caiiiycuk** [comment]
First version of presistent folders is here! Please try it:
http://js-dos.com/#js-dos-622-faq-store-user-progress-between-sessions

**Comment by x-wolverine-x** [comment]
Where can I find the stored IndexedDB, and how long does the DB exist, or will it be stored permanently?

**Comment by caiiiycuk** [comment]
In any browser you can open developer tools (ctrl+shift+i) and in Storage section there is Indexed DB. You can find your data in db named as folder the you use in fs.extract.
![indexeddb](https://user-images.githubusercontent.com/1727152/53931447-c1774700-40c7-11e9-99f6-44ad1f429e08.png)


Regarding to timings, it depends. While there is free space on drive data will be there, but in case when browser requires new free space this data can be removed.

**Comment by x-wolverine-x** [comment]
Perfect ty. Is there a Way to Export / Import this "DB"?

**Comment by caiiiycuk** [comment]
You can do this by using default indexed db API. You can iterate all key/value pairs by doing:
```typescript
    public forEach(each: (key: string, value: any) => void, onend: () => void) {
        const transaction = this.db.transaction(this.storeName, "readonly");
        const request = transaction.objectStore(this.storeName).openCursor();
        request.onerror = () => onerror("Can't open cursor on " + this.storeName);
        request.onsuccess = (event) => {
            const cursor = (event.target as any).result as IDBCursorWithValue;
            if (cursor) {
                each(cursor.key.toString(), cursor.value);
                cursor.continue();
            } else {
                onend();
            }
        };
    }
```

**Comment by developmentsedge** [comment]
Can you please explain which code to add to this example script in order to get the game to save?

```
     <script type="text/javascript" src="https://js-dos.com/cdn/js-dos-api.js"></script>
     <script type="text/javascript">
       var dosbox = new Dosbox({
         id: "dosbox",
         onload: function (dosbox) {
           dosbox.run("upload/Duke Nukem 3d-@digitalwalt.zip", "/DUKE3D.EXE");
         },
         onrun: function (dosbox, app) {
           console.log("App '" + app + "' is runned");
         }
       });
     </script>
```

**Comment by astigmatism** [comment]
With all respect, everything you need to know is in the existing
documentation. Any difficulty outside of that suggests you might need to
learn a little bit of javascript to get things going.

**Comment by developmentsedge** [comment]
Hi astigmatism,

I understand your point. I am just confused with the api calls, as the code examples on js-dos.com is different then in the examples given in the documentation.

For example:

The code here: https://js-dos.com/getting-started/
Looks like this:
```
       <script type="text/javascript" src="https://js-dos.com/cdn/js-dos-api.js"></script>
       <script type="text/javascript">
         var dosbox = new Dosbox({
           id: "dosbox",
           onload: function (dosbox) {
             dosbox.run("https://js-dos.com/cdn/digger.zip", "./DIGGER.COM");
           },
           onrun: function (dosbox, app) {
             console.log("App '" + app + "' is runned");
           }
         });
```

and the code in the documentation looks like this:
```
  <script>
    Dos(document.getElementById("jsdos"), { 
        wdosboxUrl: "https://js-dos.com/6.22/current/wdosbox.js" 
    }).ready((fs, main) => {
      fs.extract("https://js-dos.com/6.22/current/test/digger.zip").then(() => {
        main(["-c", "DIGGER.COM"])
      });
    });
  </script>
<
```
The way the code calls in JS look different, and so I am asking how to call for the saving in a specific folder using the type of script in the first example? At least a point in the right direction on how to learn how to accomplish this would be nice. 

For example, how do I take this code: ( Store user progress between sessions ):
    Dos(canvas).ready((fs, main) => {
        fs.extract("game.zip", "/game").then(() => {
            main(["-c", "cd game", "-c", "game.exe"])
        });
    });

and use it with the first set of coding in this post?

**Comment by astigmatism** [comment]
Looking at both code examples briefly, I don't see any difference. I'll
willing to help nonetheless. What do you mean by "call for the saving in a
specific folder using the type of script" however?

**Comment by caiiiycuk** [comment]
@developmentsedge  you are refer code from old version of js-dos, which is deprecated and does not support saving feature. 

![image](https://user-images.githubusercontent.com/1727152/66711537-0844c200-edb8-11e9-854d-494adf7460da.png)


New version of js-dos will save you file system in indexed db if you mount your game to some folder (not root of fs). 
http://js-dos.com/#js-dos-622-faq-store-user-progress-between-sessions

**Comment by developmentsedge** [comment]
Hi @caiiiycuk,

Thanks for the clarification between the old and new versions!

Do you plan on updating an example of the new code used with a start button and full screen button? For example, the plunked and CodePen examples would be great to have with the new coding structure, or even one of the games you have loaded on js-dos.com

Thank you for your time

**Comment by caiiiycuk** [comment]
Yeah,  now I see that it's not clear which is old version. I will rewrite docs & samples after I publish next version of js-dos with virtual keyboard support. Thanks! 
https://github.com/caiiiycuk/js-dos/issues/67

**Comment by caiiiycuk** [comment]
If you have questions you can ask me directly (caiiiycuk@gmail.com) I will try to help

**Comment by developmentsedge** [comment]
Hi @caiiiycuk 

That sounds great! I will keep an eye out for the new samples. Thanks!
