### ISSUE TITLE
can't get `ci.module` in the lastest version

### ISSUE THREAD

**Issue by xsro** [caiiiycuk/js-dos.com#152]
I try to get the API `ci.module.fs` with the latest version  but something wrong happened. I can't get the API

```javascript
require("emulators");
const JSZip=require("jszip");
const path=require("path");

const emulators=global.emulators;
emulators.pathPrefix=path.resolve(__dirname,"node_modules/emulators/dist/");

const zip=new JSZip();
zip.file(".jsdos/dosbox.conf","");
var promise = null;
if (JSZip.support.uint8array) {
    promise = zip.generateAsync({ type: "uint8array" });
}
if (promise) {
    loadandRun(promise);
}
async function loadandRun(bundleP) {
    const bundle = await bundleP;
    const ci = await emulators.dosboxDirect(bundle);
    console.log(Object.keys(ci));
    ci.exit();
}
```

**Comment by caiiiycuk** [comment]
Yeah you right, it's broken in latest version, I will release new version soon.
FS will be accessible in this way:
```
ci.transport.module.FS
```

**Comment by xsro** [comment]
Thank you.

BTW, I think the `ci.events().onStdout` API can be more funny if no filter [here](https://github.com/js-dos/emulators/blob/6da92d38522e131284d0584522cd134dea03e27f/native/dosbox/src/dos/dos_files.cpp#L440)

The users of this API can do this in their way.  The current filter `isprint` miss some control character like escape character for color displaying

**Comment by caiiiycuk** [comment]
@xsro  Can you make PR with updated filter?

**Comment by caiiiycuk** [comment]
Fixed in v7.0.2

**Comment by muditjuneja** [comment]
What about in v8?

**Comment by caiiiycuk** [comment]
> What about in v8?

Emscripten module only available in direct mode: https://js-dos.com/dosbox-direct.html#accessing-file-system
