### ISSUE TITLE
License mismatch (npm vs repository root) 

### ISSUE THREAD

**Issue by int0x2e** [caiiiycuk/js-dos.com#154]
Hi,
The LICENSE file at the root of the code repo appears to indicate everything in this project is licensed under GPLv2, while the npm package reports it is licensed under ISC. Any chance this could be a mistake?

**Comment by caiiiycuk** [comment]
Hi sorry for long delay. Yes I think it's mistake, thank you

**Comment by caiiiycuk** [comment]
Fixed in 098a3036080b3c13cc8a62bef2f939a51f44a5b6
