### ISSUE TITLE
Internet access

### ISSUE THREAD

**Issue by donno2048** [caiiiycuk/js-dos.com#157]
It would be awesome to be able to connect the internet via js-dos, I'm fairly sure the "Mega Build" of SVG-DOSBox already does it...

**Comment by caiiiycuk** [comment]
You mean internet of something like ipx? Because currently I am working on ipx support. Where I can read how to connect to the internet with dosbox? Does dos have good browser?

**Comment by donno2048** [comment]
> Because currently I am working on ipx support.

Awesome!

> Where I can read how to connect to the internet with dosbox?

The Mega build has an emulated NE2000 card

There is a wiki explaining the setup here:

https://github.com/Wengier/dosbox-x-wiki/wiki/Guide:Setting-up-networking-in-DOSBox%E2%80%90X

> Does dos have good browser?

Don't know about DOS but I have this site running windows95 (https://donno2048.github.io/win95) which has a browser and furthermore there are some game using internet connection

**Comment by AmandaJonesAway** [comment]
I'm currently looking at trying to run a Win3-era game that requires IP networking.  (Either using Win3.11 with Win32s and Trumpet Winsock [so needs modem emulation, as per em-dosbox and libsdl-net] or Win95 with an emulated network card. )  em-dosbox has been abandoned, and I cannot get it to compile, hence my looking at currently active projects. If networking support is being worked on, then this would be fantastic.

This link has a good write up on how to setup networking in Win3.11: https://www.betaarchive.com/forum/viewtopic.php?t=38372

**Comment by donno2048** [comment]
Is this feature planned?

**Comment by donno2048** [comment]
> Is this feature planned?

Will close as stale
