### ISSUE TITLE
Adding the Ability to Read from a Folder

### ISSUE THREAD

**Issue by Bioblaze** [caiiiycuk/js-dos.com#16]
You`ve made it so you need to input a URL, what if the web client I have, does not have the ability to download that zip, and store it? Would there be a way to do the same thing, but directly with a folder.

**Comment by ghost** [comment]
1/ Compress that folder to .zip
2/ `dosbox.run(./digger.zip", "./DIGGER.COM");`

**Comment by caiiiycuk** [comment]
Sorry, it's not possible, browser does not have access to your FS.
