### ISSUE TITLE
Zork! Freezes on mouse click

### ISSUE THREAD

**Issue by caiiiycuk** [caiiiycuk/js-dos.com#165]
Reproduces in game studio too
[zork.jsdos.zip](https://github.com/caiiiycuk/js-dos/files/7613173/zork.jsdos.zip)

**Comment by deskgnome** [comment]
I discovered that after exiting Zork with ingame command `quit`, and re-entering with `zork1 _ZORK1.COM`, DOSBOX no longer freezes on click.

To temporarily fix it on my side, I edited `runme.bat` and replaced line `frotz.exe data/zork1.dat` with `zork1 _ZORK1.COM`, eliminating Frotz completely. It no longer freezes on mouse click.

**Comment by deskgnome** [comment]
I was able to get it working using `frotz.exe data/zork1.dat`. 
I simply replaced the `frotz.exe` executable with the version found **[here](https://jahtari.org/archive/magazine/IF/if-howtoplay.htm)**.  Direct Download Link: [FROTZ.EXE](https://jahtari.org/archive/magazine/IF/download/FROTZ.EXE)

I believe `frotz.exe` in your [zork.jsdos.zip](https://github.com/caiiiycuk/js-dos/files/7613173/zork.jsdos.zip) is either buggy or simply a different version of Frotz.

Using this new executable, **_Zork no longer freezes on mouse click._**
You can test it out here: https://zork.deskgnome.xyz/i/thegreatundergroundempire

_Note: Frotz allows me to use my arrow keys to scroll through command history, so I prefer Frotz over running `_ZORK1.COM` directly with DOS, but both are working options._
