### ISSUE TITLE
Mouse locking doesn't work on iOS

### ISSUE THREAD

**Issue by rwv** [caiiiycuk/js-dos.com#166]
Finger swipe doesn't work. The cursor is stuck in the left-top corner.

System: `iOS 15.0 (19A346)`

![screenshot](https://user-images.githubusercontent.com/7891383/145504272-61fe0c00-366a-492c-a369-c5b0ffdca4fb.png)

**Comment by caiiiycuk** [comment]
Yeah something strange with ios, for me it didn't work at all. Will look asap

**Comment by caiiiycuk** [comment]
Fixed in https://github.com/js-dos/emulators-ui/commit/f23228f3bbe21fb1c5eacd4fd231f2b9b491658d (emulators-ui@0.72.5)

**Comment by caiiiycuk** [comment]
Fixed in v7.2.5
