### ISSUE TITLE
Not include dist/emulators-ui-loader.png

### ISSUE THREAD

**Issue by rwv** [caiiiycuk/js-dos.com#168]
https://github.com/js-dos/emulators-ui/blob/main/src/emulators-ui-loader.png

**Comment by caiiiycuk** [comment]
why not?

**Comment by caiiiycuk** [comment]
ahh ok you mean not in repository, because it included in npm package and release zip

**Comment by rwv** [comment]
Well, I mean commit https://github.com/caiiiycuk/js-dos/commit/a0ad134f782b4ecdf18581e614676ab1258797f7 removed the gif version but didn’t add the apng version.
