### ISSUE TITLE
No keyboard support Chrome on Mac

### ISSUE THREAD

**Issue by ghost** [caiiiycuk/js-dos.com#17]
# http://js-dos.com/games/

cannot use keyboard to run games
fix it
![screen shot 2016-06-24 at 3 47 01 pm](https://cloud.githubusercontent.com/assets/17680976/16332947/f033e304-3a22-11e6-800b-960be6a785b4.png)
thank you.

**Comment by khanh2003** [comment]
- [ ] 1.  I am serious.

**Comment by nrasool** [comment]
Please don't be rude!!, You could have just said I cannot use keyboard in mac using chrome, please could you investigate this. Not fix it and I am serious. This is done by someone free time, have some respect!
