### ISSUE TITLE
LFN (Long File Name) Support / TCP/UDP Networking

### ISSUE THREAD

**Issue by ghost** [caiiiycuk/js-dos.com#180]
Hello, first of all, thank you for the project.
I have been testing it since a while, and discovered that version 6.22 does not support long file names (Windows 9x style).
Do you have added it since version 7?
If it is of help, a project named DosBox-X (https://dosbox-x.com/) has support for it already, so you can simple recompile such project with your tool chains and get direct LFN support.

Other issue that is desirable is TCP/UDP networking. Do you have added already support for it in version 7? Is it documented?
Do networking DOS programs function with it like Arachne Browser?
By the way, DosBox-X also has networking support, so maybe you could also save work by just adding some source code and recompiling it in your project.

Thank you very much for your answer.

**Comment by caiiiycuk** [comment]
Hi, yeah I have plan to add dosbox-x support, but not right now. Regarding to TCP/UDP currently I am testing IPX support, after that will add support for TCP/UDP.

**Comment by caiiiycuk** [comment]
LFN is supported in windows (dosbox-x)
