### ISSUE TITLE
Folders in .zip

### ISSUE THREAD

**Issue by Adam-S-Amir** [caiiiycuk/js-dos.com#182]
I'm trying to play quake 1 (full ver.).

It used to work on JS-DOS, and now it doesn't. I found that whenever I don't have any folders in the .zip file, JS-DOS runs completely fine. But when there is a folder in the .zip file, JS-DOS won't even get past the .JS loading screen. The problem here is that, if I move the contents of the folder to the root of the .zip file, delete the folder, and run it on JS-DOS, it won't find the files properly.

see ex here: https://magnusgames.azurewebsites.net/MS-DOS/quake/quake.exe.html

**Comment by caiiiycuk** [comment]
Hi. js-dos 6.22 is not maintained anymore, so please switch to v7. However I tried your archive and DOS said that there are missed file. So maybe your archive is incomplete?
![изображение](https://user-images.githubusercontent.com/1727152/152900448-9a40d041-7076-419c-ad48-e5f2f62383b4.png)

**Comment by crappyrules** [comment]
I had an issue similar to this over the weekend with a zip file on another game while I was creating docker containers.  This may be a silly response, but the zip file was of a directory with the files inside of a folder.  My solution was to unzip the file I downloaded, go into the folder, then select everything inside and create a new zip then run that.  On another game (GTA dos version) I wasn't able to run the .exe directly, but had to create the container to run a .bat file instead.
hope this helps

**Comment by caiiiycuk** [comment]
Well. Did you tested your archives with dosbox? Because I extracted your quake archive into directory and run dosbox, have exactly same error:
![изображение](https://user-images.githubusercontent.com/1727152/152912954-880aec7f-ddff-49af-b064-dfe1690e3501.png)

There is no such file called gfx.wad in archive

**Comment by Adam-S-Amir** [comment]
Ok, so if you try again, quake should work in regular MS-DOS. I took the files out of the ID1 folder and put it in the root of the zip file, hence why the game failed to work.

**Comment by caiiiycuk** [comment]
I checked your zip file it is affected by this error https://github.com/caiiiycuk/js-dos/issues/136. You need to use other program for creating archive, e.g. I use zip or FileRoller (linux) both works fine. I guess 7zip or WinRar will work too. When I repack it, it start working. 

![изображение](https://user-images.githubusercontent.com/1727152/153107575-238c891f-c439-4f9a-a404-6d687206cf40.png)

![изображение](https://user-images.githubusercontent.com/1727152/153107658-d964ae65-b306-455c-95fc-ba8068b0200a.png)

**Comment by Adam-S-Amir** [comment]
Ok, so I fixed the problem, the games have to be zipped using WinRAR. Now my issue is that, the game runs really slowly. Check out the new .zip file.

**Comment by caiiiycuk** [comment]
Yeah, you can only reduce screen resolution. In browser there is not possible to use dynamic dosbox core, so currently games like quake will work too slow.
