### ISSUE TITLE
Cycles

### ISSUE THREAD

**Issue by Adam-S-Amir** [caiiiycuk/js-dos.com#184]
So I know cycles change the speed of the game. So if I run a .bat file that says to change the cycles to 39000, would I still get the same performance on JS-DOS on different computer with different specs?

**Comment by caiiiycuk** [comment]
Hi. It's depends on performance of host computer. js-dos will try emulate exact amount of cycles that you set in config. However if your pc only can do 25000 cycles then you will have 25000 cycles no matter what you set in config. SO, this option is useful for games that works to fast, and you can limit cycles to something small like 500 - 1000. But if you want to have maximum performance please use 'auto'
