### ISSUE TITLE
cant use js-dos when the javascript/wasm files are in a different directory

### ISSUE THREAD

**Issue by desplmfao** [caiiiycuk/js-dos.com#188]
html file required /src/js/msdos/js-dos.js
javascript file required a file that doesnt exist

its a http.ts error, line 120

![image](https://user-images.githubusercontent.com/98325692/154365296-96cfc7f2-fbbc-4336-97a8-3cd1cbb3e3b5.png)

**Comment by desplmfao** [comment]
js-dos 6.22 works perfectly fine

**Comment by desplmfao** [comment]
js-dos 7 doesnt work at all

**Comment by caiiiycuk** [comment]
you should set `emulators.pathPrefix` to the correct path where wdosbox.wasm is located.
[documentation](https://js-dos.com/v7/build/docs/browser#1-using-js-dos-api)

**Comment by desplmfao** [comment]
oh okay, thank you
