### ISSUE TITLE
Why won't W95.img boot?

### ISSUE THREAD

**Issue by Adam-S-Amir** [caiiiycuk/js-dos.com#191]
Please refer to: https://magnusgames.azurewebsites.net/ms-dos/95/95.exe.html

I've done almost everything my tiny brain can process to try and fix this, but for whatever reason, the site crashes trying to run 
Windows 95.

Why won't it run?

**Comment by caiiiycuk** [comment]
Please use v7. In v7 win95 works

**Comment by Adam-S-Amir** [comment]
Ok, I'm really bad at these kinds of things, so how exactly would I use v7. I've looked at all the documentation and understand nothing. I am so sorry, I am just very dumb.

**Comment by caiiiycuk** [comment]
If you have node then you can bootstrap template project with this command:
```npx create-dosbox```

**Comment by Adam-S-Amir** [comment]
No, I don't have nodeJS nor do I know how to use it.

**Comment by caiiiycuk** [comment]
You can install it from here https://nodejs.org/en/, it is really straightforward. Then you can run command above to boostrap a project.

**Comment by Adam-S-Amir** [comment]
Oh ok, thanks!
