### ISSUE TITLE
Send events when DOS write files to disk to auto save progress

### ISSUE THREAD

**Issue by rwv** [caiiiycuk/js-dos.com#194]
Is there a method to save to indexeddb without calling `ci.persist` manually? I know that the worker version will block the access to the FS of Emscripten. 
Could we log in [`bool DOS_WriteFile(Bit16u entry,Bit8u * data,Bit16u * amount,bool fcb)`](https://github.com/js-dos/emulators/blob/c5880254e0cac1378d3a9a4548b49b15bf637178/native/dosbox/src/dos/dos_files.cpp#L452) and implement a `CommandInterfaceEvents` `onMessage` where `MessageType` is FS changed.

**Comment by rwv** [comment]
Or maybe [`native/dosbox/src/dos/drive_overlay.cpp`](https://github.com/js-dos/emulators/blob/c5880254e0cac1378d3a9a4548b49b15bf637178/native/dosbox/src/dos/drive_overlay.cpp)

**Comment by caiiiycuk** [comment]
Yes this is good idea, to make sort of autosave.

**Comment by shaylevary** [comment]
Hi,

I would love to see this feature soon, as suggested, everytime dos write files, it will trigger the autosave feature, so players won't need to click also on the emulator save button.

**Comment by caiiiycuk** [comment]
Autosave implented when you exit fullscreen, or when dos release mouse lock. This should cover most cases.
