### ISSUE TITLE
Security error when trying to use js-dos API to run DOS games

### ISSUE THREAD

**Issue by santiagoherrera1998** [caiiiycuk/js-dos.com#195]
I'm trying to use the js-dos API to run DOS games on my website, but the emulator stops loading the game at 100% percent, and the browser console gives me this error:

`Security Error: Content at http://localhost:8000/test.html may not load data from https://js-dos.com/v7/build/releases/latest/js-dos/wdosbox.js.`

This is my code:

```
<script>
  emulators.pathPrefix =
    "https://js-dos.com/v7/build/releases/latest/js-dos/";
  Dos(document.getElementById("jsdos")).run(
    "https://doszone-uploads.s3.dualstack.eu-central-1.amazonaws.com/original/2X/2/24b00b14f118580763440ecaddcc948f8cb94f14.jsdos"
  );
</script>
```

**Comment by caiiiycuk** [comment]
You can't mix http and https content. You should host js-dos on your website, please download it from [Releases](https://github.com/caiiiycuk/js-dos/releases)

**Comment by santiagoherrera1998** [comment]
That was it, thank you!
