### ISSUE TITLE
Getting output from the DOS-program

### ISSUE THREAD

**Issue by ThorvaldAagaard** [caiiiycuk/js-dos.com#197]
I have an old DOS-program, that creates a csv-file I would like to use for other purposes. Currently the application stores it in the current folder, but how can I make that file available on my own pc?

The application is running fine in js-dos, and when the program exits to the DOS-prompt I can see the file is there, but would like to download it in some way.

**Comment by caiiiycuk** [comment]
Use ```ci.presist()``` it will return the changed files of your fs as zip archive

**Comment by ThorvaldAagaard** [comment]
I assume there is a spelling error

I am using the example from https://js-dos.com/v7/build/docs/browser

and have the following script
```
  <script>
    emulators.pathPrefix = "js-dos/";
    Dos(document.getElementById("jsdos"), {
      onExit: () => {
        console.log("onExit")
        // here the commandInterface is not available
      }
    }).run("bundle.jsdos")
      .then((ci) => {
        console.log("Now saving")
        console.log(ci);
        ci.persist().then((file) => {
          console.log(file)
          const link = document.createElement('a');
          link.style.display = 'none';
          document.body.appendChild(link);
          const blob = new Blob([file], { type: 'application/zip' });
          const objectURL = URL.createObjectURL(blob);
          link.href = objectURL;
          link.href = URL.createObjectURL(blob);
          link.download = 'game.zip';
          link.click();
        });
      }
      );
  </script>
```
I expected Dos to be a promise, but .then() is executed when the program is loaded (Basically I am saving the state from previous session in my zip)

**Comment by caiiiycuk** [comment]
Correct .then() is executed when DOS loaded and program started. So you need save ci to some var, and then call ci.persist() after your changes are made. you can listen dos stdout for this

**Comment by ThorvaldAagaard** [comment]
Please explain: **you can listen dos stdout for this**

I saved the commandInterface in a variable, and then called ci.persist() in the onExit event, but here it never returns and doesn't create an error. The commandInterface is available as I can print the config

**Comment by caiiiycuk** [comment]
You can't call ci.persist() in the onExit, because it's called when the js-dos fully stoped.
1. You can create a button on web page and call ci.persist() when you press it
2. You can listen stdout of dos with: 
```ci.events().onStdout((message) => { ... });``` e.g. if you program print something into stdout on the end, you can trigger ci.persist() in that moment
3. You can overwrite save function which is called when you close js-dos:
```dos.layers.setOnSave(async () => { ... }```)

**Comment by ThorvaldAagaard** [comment]
1: The simplest way to do it, but on first try it made the app scrollable

2: Possible but I noticed that js-dos it self writes a lot to Stdout, so I would have to find an eyecatcher. The program writes noting to stdout, but I could wrap the application in a .BAT-file and just print the eye catcher from there

3: This seems the best way to do it, It would have been nice if that was the same way as calling onExit, now I can't figure out how to access dos.layers. I did not find anything in the documentation

**Comment by caiiiycuk** [comment]
I think 1. is best option, because some browser requires user gesture to make download.
Regarding to 3:
```
const dos = Dos(root, { ...});
dos.run("...");
dos.layers.setOnSave(() => ...)
```
I think I need add onBeforeExit handler in options object

**Comment by ThorvaldAagaard** [comment]
Yes, I have implemented option 1

**Comment by caiiiycuk** [comment]
If issue is solved, please close
