### ISSUE TITLE
Theme Hospital stuck at mounting/Memory crash chrome

### ISSUE THREAD

**Issue by SyntheticOD** [caiiiycuk/js-dos.com#20]
Hi, 

I've been trying to get Theme hospital running on a webpage but i've run across an issue. In internet explorer it gets stuck mounting hospital.exe and in chrome it crashes after downloading the file/starts launching. Am i missing something ? 

Regards, 

Patrick

**Comment by caiiiycuk** [comment]
It works for me on 6.22.18, but not very fast. Use ripped version, and probably you  need to set autlock=true for this game
