### ISSUE TITLE
Executing dir /p crashes js-dos

### ISSUE THREAD

**Issue by ThorvaldAagaard** [caiiiycuk/js-dos.com#202]
From a prompt execute 
```
dir /P
```
and this is the result

![image](https://user-images.githubusercontent.com/10560652/160605250-5e34c19a-6a01-4202-876e-34be238f338d.png)

Some of the parameters are working (like /S), and others are giving "Invalid switch" (Like /L), but /P is crashing

I am using this reference

![image](https://user-images.githubusercontent.com/10560652/160606267-eda5be08-8b1e-4416-a111-2777502dbb76.png)

**Comment by caiiiycuk** [comment]
@ThorvaldAagaard Please check, should be fixed in  v7.3.9

**Comment by ThorvaldAagaard** [comment]
The command is now showing the first page like this:

![image](https://user-images.githubusercontent.com/10560652/161719335-5bab6518-7b36-4988-8b00-dc08f519ba0d.png)

but after that the command prompt is not responding, and these lines in the javascript console:

![image](https://user-images.githubusercontent.com/10560652/161719651-839c4539-b012-45a9-a80b-3dd04330667f.png)

**Comment by caiiiycuk** [comment]
Ohh, will fix it

**Comment by caiiiycuk** [comment]
@caiiiycuk + when you exit x-com [rus] you have similar message.

**Comment by caiiiycuk** [comment]
Fixed in v7.4.0

**Comment by ThorvaldAagaard** [comment]
Works fine.

While you are looking at it you might have a look at the /s switch, that should show subdirectories
