### ISSUE TITLE
Keeping files after a reload

### ISSUE THREAD

**Issue by ThorvaldAagaard** [caiiiycuk/js-dos.com#206]
When the application is loaded for the first time, there is some initial setup (Based on a config file exist or not)

That file is not present in bundle.jdos that is loaded, and is created.

Returning to the site the next time the file is found so no setup.

But if the user presses F5 to reload the site it looks like a fresh DOSBox is created and the user is once again asked about initial setup as the config file isn't there

Is it possible to keep the created file(s) when F5 used?

I assume the same might happen if I upload an updated bundle

**Comment by caiiiycuk** [comment]
js-dos support storing fs changes [out of the box](https://js-dos.com/v7/build/docs/jsdos-save-load). However it do save only when you close the js-dos window, or press save icon. You can manually trigger the save function if you need:

```js
await dos.layers.save()
```

So, basically when you press F5 browser just stop dos and does not save changes.
