### ISSUE TITLE
Since the V7 version does not support zip files. So how to convert zip into .jsdos files in batches. thanks.

### ISSUE THREAD

**Issue by yyj1983** [caiiiycuk/js-dos.com#208]
Since the V7 version does not support zip files. So how to convert zip into .jsdos files in batches. thanks.

**Comment by caiiiycuk** [comment]
The best way is to write script to convert zip file to jsdos (also zip).

**Comment by yyj1983** [comment]
Thank you, my level is too bad, I will study it slowly.
