### ISSUE TITLE
Mouse mapping bug

### ISSUE THREAD

**Issue by fpalazzolo** [caiiiycuk/js-dos.com#21]
I have found one app where some of the mouse mapping is incorrect under js-dos, but it works fine in DOSBox-0.74 and DOSBox-r4006.  It's probably a bug in em-dosbox.  It appears to be related to the DOS interrupt 0x33 that sets the mouse extents AX=7 and AX=8.  There is an example app at http://cups.avoidspikes.com/ ... if you dismiss the opening dialog and then select Graphs->Path Integral.  Then left-click in the upper left plot area to create a polyline.  You can see the mousedown and the mousedrag coordinates don't match.  I should probably create an issue with the em-dosbox github, but I haven't built em-dosbox yet.  Does your build of em-dosbox uses SDL or SDL2 support?  It might be related to that.  Thanks!

**Comment by fpalazzolo** [comment]
The behavior is slightly different between Chrome and Firefox here as well.  I have recently built em-DOSbox so I will look into it myself.

**Comment by caiiiycuk** [comment]
Please reopen if still exists

**Comment by caiiiycuk** [comment]
This is because program set region where mouse should operate, and it's not supported by js-dos. However you can use `autolock: true` feature of js-dos v7.
