### ISSUE TITLE
"uncaught exception: [object Object]"

### ISSUE THREAD

**Issue by sluke817** [caiiiycuk/js-dos.com#216]
![image](https://user-images.githubusercontent.com/82904475/167682966-e5ef427f-9fbf-4adc-a790-c088482e30af.png)

**Comment by caiiiycuk** [comment]
Can you share jsdos bundle to test?

**Comment by sluke817** [comment]
I am unable to share the bundle. It is a Fortran program and a dosbox conf file, I can share the conf file but not the .exe file

**Comment by caiiiycuk** [comment]
Can you send it to me privately on caiiiycuk@gmail.com? This problem is related to asyncify execution, I can fix it only by using original program

**Comment by sluke817** [comment]
I got lucky and fixed that issue, you can close that, I posted 2 more. Thank you so much for your help


Luke Schaefer
University of Missouri - Columbia (18186970)
College of Engineering - BS Computer Science
***@***.***

[cid:93b5df83-7054-46b8-8e81-0a8bbddde0d0]
________________________________

**Comment by caiiiycuk** [comment]
I don’t think that you fixed it. 2 other issues are about network problems on your website configuration

**Comment by caiiiycuk** [comment]
Ahh ok, this is not related to asyncify. It’s related to #109, some zip archives is not compatible with jsdos. Please use 7zip or dos.zone/studio
