### ISSUE TITLE
Error: Unable to download 'js-dos/wdosbox.js', code: 0

### ISSUE THREAD

**Issue by sluke817** [caiiiycuk/js-dos.com#217]
![image](https://user-images.githubusercontent.com/82904475/167685111-c4d9e3fe-35e1-470c-9315-48f4f27217e4.png)

**Comment by caiiiycuk** [comment]
Seems your webserver is not serving w dosbox.js on that address

**Comment by sluke817** [comment]
Any quick fixes/advice?

**Comment by caiiiycuk** [comment]
Try to open this url in your browser. It should returns content of wdosbox.js
