### ISSUE TITLE
Ignoring certain kb characters

### ISSUE THREAD

**Issue by fpalazzolo** [caiiiycuk/js-dos.com#22]
Another weird bug that only happens in js-dos / em-dosbox.  With the same app at http://cups.avoidspikes.com/ go to Field->Read Scalar Field and try to enter the text field for F=.  Certain characters are rejected -_+=;:'"  This seems to happen for any text field.  I guess I will have to build my own em-dosbox and sort it out...strange that it works in DOSbox-0.74.

**Comment by fpalazzolo** [comment]
After a bit more testing, I found characters that are ignored are different between Chrome and Firefox.  The above comment applies to Chrome, in Firefox only ' and " are ignored.  I recently build em-DOSbox successfully so I am planning to look into it.

**Comment by caiiiycuk** [comment]
![thumbs-up-256](https://cloud.githubusercontent.com/assets/1727152/22713279/d75c3b4a-ed98-11e6-8b5b-a07d17a0a330.png)

**Comment by caiiiycuk** [comment]
![25297](https://cloud.githubusercontent.com/assets/1727152/22713329/07aeeb8a-ed99-11e6-8846-d986a858b3fb.png)

**Comment by caiiiycuk** [comment]
Now fixed in 6.22.18
