### ISSUE TITLE
Not found any game...

### ISSUE THREAD

**Issue by rocknplay** [caiiiycuk/js-dos.com#220]
Could you please, help check if there is a problem to create-dosbox?

  npx create-dosbox my-app
? Enter title of the game to search (e.g. Digger) Digger
Not found any game with this title. Exiting...

Not able to find a game.

Also tried to use a zip archive, but still ask for a game to search.

 npx create-dosbox my-app archive.zip
? Enter title of the game to search (e.g. Digger)
Not found any game with this title. Exiting...

NPM:  npm -v
8.9.0

Thank you.

**Comment by caiiiycuk** [comment]
> Could you please, help check if there is a problem to create-dosbox?
> 
> npx create-dosbox my-app ? Enter title of the game to search (e.g. Digger) Digger Not found any game with this title. Exiting...
> 
> Not able to find a game.
> 
> Also tried to use a zip archive, but still ask for a game to search.
> 
> npx create-dosbox my-app archive.zip ? Enter title of the game to search (e.g. Digger) Not found any game with this title. Exiting...
> 
> NPM: npm -v 8.9.0
> 
> Thank you.

Ohh. Seems broken, I fix it asap

**Comment by caiiiycuk** [comment]
Fixed, to use last version do:
```
npx create-dosbox@latest app
```

**Comment by rocknplay** [comment]
> Fixed, to use last version do:
> 
> ```
> npx create-dosbox@latest app
> ```
Thank you very much, it's perfect now.
Sorry for the trouble.
