### ISSUE TITLE
GTA doesn't work

### ISSUE THREAD

**Issue by ajmeese7** [caiiiycuk/js-dos.com#223]
When attempting to boot up the GTA game on dos.zone, the following error appears:

![DOS error](https://user-images.githubusercontent.com/17814535/172076249-c95ea1ed-98ee-40aa-b0b3-a32a7c535f02.png)

**Comment by caiiiycuk** [comment]
Hi. On dos.zone you need to select:
- Run GTA
- Run Low Color GTA

Then it works.
