### ISSUE TITLE
Could you update the virtual keyboard on the demo?

### ISSUE THREAD

**Issue by yyj1983** [caiiiycuk/js-dos.com#226]
Could you update the virtual keyboard on the demo? The current virtual keyboard has no direction keys, ALT and Ctrl keys. Many games need to use these keys on mobile phones.

**Comment by caiiiycuk** [comment]
Can you use game studio to add virtual keys? I think using them from soft keyboard will be so hard...

**Comment by yyj1983** [comment]
I think if the virtual keyboard on the demo is added with the up, down, left, right direction keys, ALT keys and Ctrl keys, the adaptability will be very good. Sort of https://dos.zczc.cz This site's virtual keyboard, but I don't understand it. I can only use similar https://dos.zone Style on.

**Comment by caiiiycuk** [comment]
Okay I think I can do this. Btw, about what demo you are talking?

**Comment by yyj1983** [comment]
I said demo is this https://github.com/caiiiycuk/js-dos/releases 。 Look forward to your next version of the virtual keyboard with the up, down, left, right arrow keys and other useful keys, such as ALT and Ctrl. thank you. Although I understand that through dos Various buttons can be added to the zone/studio/, but it is inconvenient after all, and some of them will be blocked from the game display by the customized buttons. The perfect way is to improve the virtual keyboard. By the way, your JS DOS is very good. Thank you

**Comment by caiiiycuk** [comment]
Done. The new keyboard layout are published in v7.4.6 version
