### ISSUE TITLE
Node documentation doesn't work

### ISSUE THREAD

**Issue by rjwut** [caiiiycuk/js-dos.com#227]
Using `emulators` version `0.73.6`.

When you run the Node example given on [this page](https://js-dos.com/v7/build/docs/node) as-is, it throws the following error:

```
ReferenceError: rgb is not defined
    at Timeout._onTimeout (C:\rjw\confmeps-api\try3.js:27:38)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
```

This appears to be caused by the `rgba` variable declared on line 25 shadowing the one declared on line 14. It appears that the intent was for the variable declared on line 14 to be named `rgb` rather than `rgba`. Changing lines 14 and 16 to reflect that change results in another problem, however:

```
TypeError: Cannot read properties of null (reading '0')
    at Timeout._onTimeout (C:\rjw\confmeps-api\try3.js:27:41)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
```

A little debugging finds that when the `onFrame()` is invoked, the argument (called `frame` in the example code) is always `null`.

**Comment by caiiiycuk** [comment]
Thanks for report. Seems I broke something in last builds. I will check asap.

**Comment by caiiiycuk** [comment]
Now fixed. The problem was in documentations it self. Please read the updated [docs](https://js-dos.com/v7/build/docs/node/).
