### ISSUE TITLE
How to suppress message logging?

### ISSUE THREAD

**Issue by rjwut** [caiiiycuk/js-dos.com#228]
I haven't been able to find detailed documentation about the command interface API, so I've been digging into the `emulators` source code. Right now, all messages emitted by the emulator are echoed to the console. I'd like to provide my own handler instead. I can do that easily enough by passing a function to `ci.events().onMessage()`, but this doesn't replace the behavior of the existing messages getting logged to the console. How can I suppress that behavior in favor of my own message handler?

**Comment by caiiiycuk** [comment]
Current implementation is logging the ERR/PANIC messages from dosbox. Currently it does not have option to supress them, you can find releated code here:
```https://github.com/js-dos/emulators/blob/main/src/protocol/protocol.ts:264-272```

It will be great if someone could add such option to js-dos

**Comment by rjwut** [comment]
I mean, it seems like the solution is to simply delete the calls to `console.error()` and `console.log()` from that section of the code. The same messages are already being propagated through the `fireMessage()` calls, so anyone who wants it logged can easily register a message listener and pass each message received to the console.

**Comment by caiiiycuk** [comment]
I think you right, will publish new version soon. Btw, I am curious what you are doing with jsdos and node.

**Comment by rjwut** [comment]
For my own amusement, I am creating a JavaScript API that allows you to programmatically control the game _Conflict: Middle East Political Simulator_. It performs optical character recognition on the screenshots to read the text and generates events to notify the consumer of the API of what's happening in the game and of the available options. The consumer submits their choices in response to events, which get translated into keystrokes. Eventually, I'd like to leverage this API to create a bot that plays the game, and maybe even develop a neural network that learns how to play the game effectively.

**Comment by caiiiycuk** [comment]
Wow, interesting. Do you open the sources at some time?

**Comment by caiiiycuk** [comment]
Fixed in [v0.73.7](https://github.com/js-dos/emulators/releases/tag/v0.73.7)

**Comment by rjwut** [comment]
> Wow, interesting. Do you open the sources at some time?

Yeah, I plan to.
