### ISSUE TITLE
Separate exit button with control bar disabled

### ISSUE THREAD

**Issue by ajmeese7** [caiiiycuk/js-dos.com#230]
I would like to have the ability to have a simple exit button, much like the current exit button implementation, that is available even if the `style` attribute of the control bar is set to `none`. My use case would benefit from having the exit button but I do not need the entire functionality afforded by the control bar, and I want to keep the UI minimalist.

**Comment by caiiiycuk** [comment]
I think you can add such exit button by yourself.

**Comment by ajmeese7** [comment]
An alternative workaround was introduced in #231, closing this out now :)
