### ISSUE TITLE
Js script for external fullscreen button

### ISSUE THREAD

**Issue by shaylevary** [caiiiycuk/js-dos.com#234]
Hi,

In older versions of ja-dos I could use ci fullscreen function in order to add an external button to switch to fullscreen.
I've checked your document and didn't find any html code/js-script that do this function.

Is there any way to achieve it on the new version?

 Thanks in advance,
 Shay.

**Comment by caiiiycuk** [comment]
Did you find solution?

**Comment by shaylevary** [comment]
Not exactly, I bypass this issue by putting the html script in an iframe and add a simple fullscreen js-script for the iframe id (if you want I can post my js code here).

I'll be happy If you'll find a better ja solution that uses the original script fullscreen function
