### ISSUE TITLE
bundles not loading from local source under HTTP/1.1

### ISSUE THREAD

**Issue by MacAulayA** [caiiiycuk/js-dos.com#244]
I'm having an issue loading bundle files that are in bundled with my website.  If I pull bundles from the CDN (http/2) they work fine, but local ones return a "zip_to_fs: can't open zip archive: Not a zip archive" message.  They appear to be formed correctly since I can access them directly through the browser at their url (and the contents appear correct).  I have a suspicion that this may be due to the file chunking process of HTTP/1.1.
Is there a workaround for this?

**Comment by caiiiycuk** [comment]
Do you have public url to test?

**Comment by MacAulayA** [comment]
Sorry, I don't.  I'll have a think about how I could do that - it's a bit
tricky!  My current thinking is that my server might be ignoring the
*request.overrideMimeType("text/plain;
charset=x-user-defined"); *statement and returning the data in a different
format, as the XMLHttpRequest looks pretty standard otherwise.

**Comment by caiiiycuk** [comment]
@MacAulayA did you find the solution?

**Comment by MacAulayA** [comment]
Yes, and it wasn't a js-dos issue.  The website bundler was trimming empty
bytes off the end of the .jsdos file and js-dos couldn't process it.
