### ISSUE TITLE
Mouse no longer working when using "Mouse Locking" feature in MacOS

### ISSUE THREAD

**Issue by Ziiven** [caiiiycuk/js-dos.com#245]
It was working on 7.4.4. But with the 7.4.6 the mouse is not working in MacOS (Windows is working fine). I have test it on Chrome & Safari, you can try it in here https://dos.zone/doom-dec-1993/

**Comment by caiiiycuk** [comment]
It is strange, cause I think that chrome should be the same on MacOS/Windows. Which version of chrome did you tried?

**Comment by Ziiven** [comment]
@caiiiycuk Chrome 104.0.5112.79, Safari 15.5 & MacOS 12.4

**Comment by Ziiven** [comment]
@caiiiycuk To be more specific, the mouse is not working when using "Mouse Locking" feature in MacOS

**Comment by caiiiycuk** [comment]
@Ziiven can't reproduce on Safari 15.6.1 & MacOS 12.6. Does it work for you?

**Comment by caiiiycuk** [comment]
Please reopen if still experiencing this problem
