### ISSUE TITLE
Uncaught RuntimeError: unreachable

### ISSUE THREAD

**Issue by Ziiven** [caiiiycuk/js-dos.com#247]
Hi, I'm using jsdos play a turn based game. But when I reached about 50 rounds the game freeze and shows this error in the console

wdosbox.js:9 Uncaught RuntimeError: unreachable
at 0059645a:0x9ca6
at 0059645a:0x2824
at 0059645a:0x11a05b
at 0059645a:0xf5607
at 0059645a:0xdf3e7
at ret.<computed> (wdosbox.js:9:110113)
at Object.doRewind (wdosbox.js:9:111349)
at wdosbox.js:9:111941
at Module.receive (wdosbox.js:9:13772)

Uncaught RuntimeError: unreachable
Uncaught RuntimeError: table index is out of bounds

Uncaught RuntimeError: table index is out of bounds
at 0059645a:0xdd98b
at ret.<computed> (wdosbox.js:9:110113)
at Object.doRewind (wdosbox.js:9:111349)
at wdosbox.js:9:111941
at Module.receive (wdosbox.js:9:13772)

**Comment by caiiiycuk** [comment]
Do you have link to test?

**Comment by Ziiven** [comment]
@caiiiycuk sorry I don't have. It happened in one of my users. 

I think myabe this error is related with the saves in indexedDB? Because he said he saved the game in the 49th round, and it will throw this error every time in the 50th round.

**Comment by Ziiven** [comment]
Is it because the save in the indexedDB is too large? There was another user mentioned a similar error about 2-3 months ago, which happened in the same game level and around 50 rounds

![IMG_1706](https://user-images.githubusercontent.com/29644610/188415038-cbd379b6-1d7f-493c-bc25-d6bcc0ab119d.jpg)
![IMG_1707](https://user-images.githubusercontent.com/29644610/188415043-660aa9c5-f9a7-4d39-a4e3-0dc360f6125a.jpg)

**Comment by caiiiycuk** [comment]
Nope, it’s not related to saves. The problem is in game. I need the game
and save on 49 level to reproduce and fix

Пн, 5 сент. 2022 г. в 12:16, Ziiven ***@***.***>:

**Comment by Ziiven** [comment]
@caiiiycuk I have asked that user to keep the save. Could you tell me how to export the saves from browser?

**Comment by caiiiycuk** [comment]
If you use logged integration, then you can find download button in js-dos settings. Btw, maybe you can pass this turns on PC?

**Comment by Ziiven** [comment]
He said the game freeze after he end the player's turn, no matter what he did. Anyway I will upload the game save as soon as he give it to me.

**Comment by caiiiycuk** [comment]
Which game we are talking about?

**Comment by Ziiven** [comment]
The game is called "Flame Dragon 2". The game bundle is here: https://doszone-uploads.s3.dualstack.eu-central-1.amazonaws.com/personal-v2/studio/dkkpr/bundle.jsdos

However I found out I didn't use logged integration. Is it ok if I exported the game save as arrayBuffer and converted it to base64?  You can convert it back to arrayBuffer using this function:

```
function _base64ToArrayBuffer(base64) {
        let binary_string = window.atob(base64);
        let len = binary_string.length;
        let bytes = new Uint8Array(len);
        for (let i = 0; i < len; i++) {
            bytes[i] = binary_string.charCodeAt(i);
        }
        return bytes.buffer;
    }
```

[base64ArrayBuffer.txt](https://github.com/caiiiycuk/js-dos/files/9492301/base64ArrayBuffer.txt)

**Comment by Ziiven** [comment]
Just tried the save myself, it will 100% trigger the error even the player don't do anything in that round

When you enter the game you can do the following steps to reproduce:
1. in the main menu select "continue"
2. once the game loaded, use the arrow key to move the selector to a grid that without any NPC
3. press "space" key to popup a option menu, select "end" at the bottom by using the arrow key
4. confirm end turn by press "space" key 
5. error triggered

![1662439152137](https://user-images.githubusercontent.com/29644610/188548316-f5b202f4-355b-4022-9bde-076a681bd04b.jpg)

**Comment by Ziiven** [comment]
@caiiiycuk Just confirmed that this issue is not related to the jsdos. It is something that in the game itself (it set a maximum turns of 50, and will force the game to stop when reach 50). So please close this issue :)

**Comment by caiiiycuk** [comment]
Interesting, thanks! I will keep it open, cause I still want to look into.
