### ISSUE TITLE
Issue with setting up js-dos in Angular

### ISSUE THREAD

**Issue by chinonso098** [caiiiycuk/js-dos.com#248]
<img width="915" alt="Screen Shot 2022-09-08 at 6 31 25 PM" src="https://user-images.githubusercontent.com/14144437/189237403-ea664a5f-f195-44cd-8a14-4afa09eae808.png">

....
<img width="1135" alt="Screen Shot 2022-09-08 at 6 37 00 PM" src="https://user-images.githubusercontent.com/14144437/189237986-02e91dd1-5b66-4470-98fa-6b3df86998a4.png">

I followed in parts, the React(TypeScript) tutorial for setting up js-dos. I've installed every package required. Angular still say's Emulators is not defined. Is there something I'm missing ?

**Comment by caiiiycuk** [comment]
Hi, you need to add js-dos.js script and css files into head section.
![изображение](https://user-images.githubusercontent.com/1727152/189276500-5dee4143-9229-4fa3-8d60-341314d43f03.png)
