### ISSUE TITLE
Volcov Commander fails to execute any program

### ISSUE THREAD

**Issue by pavkam** [caiiiycuk/js-dos.com#250]
# Background
I have created a bundle which contains two programs:
- VC - Volcov Commander,
- Sea - a game.

The DOS starts into Volcov Commander interface and I try to execute the game using it. It fails with the error `RuntimeError: indirect call to null`.

# Screenshot
![image](https://user-images.githubusercontent.com/7327309/191023075-5c8719a3-abef-4951-954f-c5ee0f7e794a.png)

# The Bundle
[x.zip](https://github.com/caiiiycuk/js-dos/files/9599088/x.zip)

**Comment by caiiiycuk** [comment]
Fixed in js-dos v7.4.8
