### ISSUE TITLE
loading bundles via file:// fails

### ISSUE THREAD

**Issue by frenchtoastbeer** [caiiiycuk/js-dos.com#252]
It seems that only http:// loading is supported.  I created a:

jsdos.html
mtt.jsdos
v7.4.7/js-dos.js
v7.4.7/js-dos.css

and attempted to load directly off the filesystem via the file:// protocol, but CORS is blocking the loading for mtt.jsdos in firefox and chrome.  It looks like I'd have to host this via a webserver, but that's more involved than I'd like. 

Is there a Dos(..).run() equivalent that accepts the file inline, perhaps as base64 encoded?  How could I do this without a webserver?

**Comment by caiiiycuk** [comment]
Hi. This is correct behavior of browser. You can't load using file://protocol. I mean this is not a js-dos issue. You can use [createObjectUrl](https://developer.mozilla.org/ru/docs/Web/API/URL/createObjectURL) to create a url from byte array. Use it to achieve what you want.
