### ISSUE TITLE
General Setup on a Webserver

### ISSUE THREAD

**Issue by phantompepper** [caiiiycuk/js-dos.com#26]
I'm trying to implement this on my website. For testing, I've just used the example given on the JS-Dos website, and I have that set as my index.html page, so its the only this that shows up. I have my own ZIP folder with Oregon Trail, however, the DOSBOX just hangs at Mount 100% . Any thoughts on this? I've tried multiple games without luck.

**Comment by Balrog85** [comment]
I think it's a problem with the way non-HTML files are transferred from some web servers, possibly a setting that can be changed.  I have one server that I rent and a separate one running off my own computer.  It doesn't seem to matter where the web page is hosted, but if I try to host the zip file on my rented server it hangs while mounting, like yours.  If I put the zip file on the self-hosted server, it works fine.

**Comment by caiiiycuk** [comment]
Can you paste browser log, usually it have some errors
