### ISSUE TITLE
Windows 95 256 colors

### ISSUE THREAD

**Issue by grechucia** [caiiiycuk/js-dos.com#260]
I’ve installed Windows 95 in dosbox for old games but i cant get it to work in 256 colors required to run most games. I’ve tried s3, cirrus and universal drivers. Everything works on dosbox-x but fails on js-dos. Im getting gpu configuration error Message on start.  Is this „normal”?

**Comment by caiiiycuk** [comment]
Which error you have? Windows 95 not officially supported, but sometimes it works. To make it work, need to fix this first:

https://github.com/WebAssembly/binaryen/issues/5343

**Comment by grechucia** [comment]
Exact error is "Display adaptor not configured properly". That's it, nothing else. 

On dosbox-x everything works fine (for example with S3 gpu drivers installed and enabled) in 256 colors mode. On js-dos only 16 colors are available in Windows display settings menu and Windows trying to "configure graphics adaptor" wchich failes all the time.

**Comment by caiiiycuk** [comment]
js-dos is a dosbox, not a dosbox-x. You should make it work on dosbox.

**Comment by caiiiycuk** [comment]
Just use dosbox-x from v8
