### ISSUE TITLE
requestAnimationFrame error

### ISSUE THREAD

**Issue by ghost** [caiiiycuk/js-dos.com#27]
"Looks like you are rendering without using requestAnimationFrame for the main loop. You should use 0 for the frame rate in emscripten_set_main_loop in order to use requestAnimationFrame, as that can greatly improve your frame rates!"

how can i pass this error?

i have wordpress site and just copy js-dos codes. game monted and there is no problem with that but i always get that error.

thanks for the answer,

**Comment by caiiiycuk** [comment]
This is not error, it is a performance tip. But I can't see that error on js-dos.com. Anyway there is no problem.
