### ISSUE TITLE
About Virtual Keyboard and Saving and Loading

### ISSUE THREAD

**Issue by yyj1983** [caiiiycuk/js-dos.com#273]
`Hello,` I have two suggestions:

1. Can the virtual keyboard be optimized to make the mobile phone better.
The virtual keyboard would be perfect if it could look like this picture
[https://collection.global/img/temp/jianpan.jpg](https://collection.global/img/temp/jianpan.jpg)

2. Yes, click the Save button. The default is browser download, and there is also an entry to select the downloaded file to load the game.

**Comment by caiiiycuk** [comment]
Starting from v8.1.19 keyboard is configurable: https://js-dos.com/virtual-keyboard.html#special-keys
