### ISSUE TITLE
[v0.73.8]test start worker fail

### ISSUE THREAD

**Issue by citee520** [caiiiycuk/js-dos.com#274]
[precondition]
    Version: emulators [v0.73.8]
    emscripten tools: 3.1.34

[reproduce]
1. Download release emulators [v0.73.8]
2. tar xvf emulators-0.73.8.tar.gz
3. cd emulators-0.73.8
4. yarn install
5. gulp
6. cd dist
7. replace text temp.jsdos to digger.jsdos from template.html
8. python3 -m http.server 6702
9. open web, press F12 
10. input 127.0.0.1/test/template.html

[problem]
open template.html press "start worker" not work, check debug tools display error message as below:
ncaught RuntimeError: unreachable, 
    at 005a4e02:0x73e61
    at 005a4e02:0x20b02
    at 005a4e02:0x117a9
    at 005a4e02:0x11e764
    at 005a4e02:0xf9c8c
    at 005a4e02:0xe3c64
    at ret.<computed> (wdosbox.js:8:110112)
    at Object.doRewind (wdosbox.js:8:111785)
    at wdosbox.js:8:112368
    at Module.receive (wdosbox.js:8:12234)

**Comment by caiiiycuk** [comment]
Hello, which verison of emscripten  you used?

**Comment by citee520** [comment]
emscripten: 3.1.34
I have try replace file "wdosbox.js" and "wdosbox.wasm" from js-dos, 
It's worked.

**Comment by caiiiycuk** [comment]
Please use 3.1.21

**Comment by citee520** [comment]
OK, will try it.
thanks your help. ^^

**Comment by citee520** [comment]
closed.
Change emscripten to version 3.121 can be worked.
