### ISSUE TITLE
Load Zip File

### ISSUE THREAD

**Issue by leimao** [caiiiycuk/js-dos.com#275]
It seems that the old JS-DOS can load zip files (according to the [old tutorial](https://js-dos.com/getting-started/)), but the latest JS-DOS cannot. Is my understanding correct?

**Comment by caiiiycuk** [comment]
In version 7, we expect a JSDOS file, which is essentially a zip file. However, please ensure that the zip file includes the .jsdos/dosbox.conf file. You can effortlessly create this file using dos.zone/studio. As this is not an issue, I will close this ticket now. Please do not hesitate to contact us if you have any further concerns or queries.
