### ISSUE TITLE
The quote key does not work

### ISSUE THREAD

**Issue by Wanghn233** [caiiiycuk/js-dos.com#276]
here is my bundle.
https://github.com/Wanghn233/tt/blob/main/tt.jsdos
I don't think this problem is caused by my bundle, Because I can't use the quote key on the command line in other games either.

![微信图片_20230420160934](https://user-images.githubusercontent.com/30120785/233302414-a6cc25ec-a57c-42e1-bfc3-5d23a7a9cdcd.png)

**Comment by caiiiycuk** [comment]
The fix was proposed by Fred:
> I fixed this issue, it is due to keys.ts does not have a proper mapping
![изображение](https://user-images.githubusercontent.com/1727152/235226343-2c9e4558-50b4-4a1c-978e-1ae891110a3b.png)
> following changes have to be made in order to work
> those equals to 222 are the changes

**Comment by skyksit** [comment]
Changing the codes for the KBD_quote and KBD_grave keys will resolve the error.

KBD_quote = 222;
KBD_grave = 192;

**Comment by caiiiycuk** [comment]
Related to #325

**Comment by caiiiycuk** [comment]
Fixed in v8.2.3
