### ISSUE TITLE
Compile error Maximum Function Size

### ISSUE THREAD

**Issue by mwmdragon2** [caiiiycuk/js-dos.com#279]
When running JS-DOS on an ibrave hosting server I get this error, do you have any clue what may be causing this?

This error is from the Chrome Devtools:

`CompileError: WebAssembly.compile(): size 2146435072 > maximum function size 7654321 @+332855`

**Comment by caiiiycuk** [comment]
Which version of jsdos you use?

Пт, 12 мая 2023 г. в 23:32, mwmdragon2 ***@***.***>:

**Comment by mwmdragon2** [comment]
6.22

**Comment by mwmdragon2** [comment]
http://allgamearchive.com/DOS/

**Comment by caiiiycuk** [comment]
Unfrotunatelly 6.22 is not mantained anymore. It seems that newer browsers has a limit for function body size, and 6.22 is not fit the limits. Please update to 7.x, of 8.x-beta

**Comment by mwmdragon2** [comment]
> Unfrotunatelly 6.22 is not mantained anymore. It seems that newer browsers has a limit for function body size, and 6.22 is not fit the limits. Please update to 7.x, of 8.x-beta

Is using 7.x or 8.x Beta as easy as replacing the 6.22 files?

**Comment by caiiiycuk** [comment]
Nope, it have different API you need to create bundles from your games (you can do it with script). 

https://js-dos.com/v7/build/docs/jsdos-bundle
