### ISSUE TITLE
Don't build emulators@0.80.18

### ISSUE THREAD

**Issue by skyksit** [caiiiycuk/js-dos.com#284]
I wanted to try dosboxX so I tried building emulators@0.80.18 , but it doesn't build.  When I look at the action history of the repository, there is only a build failure history.  I am wondering if there is anything else I need to do in order for the build to succeed.

**Comment by caiiiycuk** [comment]
Hi, the reason is that v8 is under active development, and there is currently no reproducible build sequence available. I hope that soon I can create such a build system and write documentation on how to build it.

**Comment by caiiiycuk** [comment]
Anyway, we are waiting for the FF bug to be fixed to allow DosboxX to work in FF.

**Comment by skyksit** [comment]
Thank you for your kind reply. I'll wait for the build documentation to be updated. I hope the things you planned go well.
