### ISSUE TITLE
Questions Regarding initialization sequence and Save/Load feature.

### ISSUE THREAD

**Issue by jlcvp** [caiiiycuk/js-dos.com#288]
1. Does the `C:\AUTOEXEC.BAT` always run at startup or do I need to specify it in the dosbox.conf or jsdos.json?
2. Does the FS restore load overwrites occur before the start of the autoexec argument in jsdos.json or does it run together in a race condition?

**Comment by caiiiycuk** [comment]
1. I think no need to specify it in dosbox.conf
2. There is not race conditions (js is single threaded). FS resotred before emulation starts
