### ISSUE TITLE
Running Win95 image gives error loading operating system

### ISSUE THREAD

**Issue by imneckro** [caiiiycuk/js-dos.com#289]
Hello.
I'm trying to run win95 from the below source
https://archive.org/details/win95_in_dosbox
but jsdosbox shows error loading operating system
<img width="398" alt="image" src="https://github.com/caiiiycuk/js-dos/assets/42493772/95fc89bd-47d0-4828-b552-bb7a3141f287">
Can someone help?

**Comment by caiiiycuk** [comment]
The win95 is not officialy supported in v7 branch, but v8 (based on dosbox-x) supports it.
