### ISSUE TITLE
DOSBox appears to launch but error upon loading game (from examples on homepage)

### ISSUE THREAD

**Issue by voxoid0** [caiiiycuk/js-dos.com#29]
All 4 of the games I tried starting gave the following error in the browser console:

js-dos-api.js:173 Looks like you are rendering without using requestAnimationFrame for the main loop. You should use 0 for the frame rate in emscripten_set_main_loop in order to use requestAnimationFrame, as that can greatly improve your frame rates!

I'm using Windows 10, latest version of Chrome as of 9/26/17.

**Comment by caiiiycuk** [comment]
Hi. This is not error, this is optimization tip. Btw, it's not affect performance at all. Do you have other errors?

**Comment by caiiiycuk** [comment]
https://groups.google.com/forum/#!topic/emscripten-discuss/_UAt1hm--iw

**Comment by caiiiycuk** [comment]
Now fixed!
