### ISSUE TITLE
Can js-dos run locally under node?

### ISSUE THREAD

**Issue by djpeterso23662** [caiiiycuk/js-dos.com#290]
Can js-dos run under node.js on the server, and mount server folders for saving data between runs?  I am sorry this is a newbie question.  Under DOSBOX I am running a script that calls DOSBOX, runs a DOS command line program, then exits DOSBOX and returns to the script.  However, DOSBOX is hanging without starting up, so I wondered if js-dos might work better.  Thanks for your time-- js-dos is a pretty amazing piece of work!

**Comment by caiiiycuk** [comment]
Hi, yes. It's better to ask in telegram or discord channel
