### ISSUE TITLE
How can i add "active" style when clicking on a virtual button

### ISSUE THREAD

**Issue by shaylevary** [caiiiycuk/js-dos.com#292]
Hi,

I would like to add a function, that when clicking on a virtual button while playing on mobile, it will change the button color (active).
Currently, the virtual button style is static when clicking on it.

Can i add some script code in order to display the virtual buttons in active mode when click on it on mobile?

**Comment by caiiiycuk** [comment]
You can do it with css I think

**Comment by shaylevary** [comment]
I've tried to add this css code:

.emulator-button.active, .emulator-button:hover,  {
background-color:red;
}

But it doesn't seems to work when i click on the virtual button on my mobile.

**Comment by caiiiycuk** [comment]
Did you tried to use `!important`? Anyway there is no other options for now.
