### ISSUE TITLE
cannot compile

### ISSUE THREAD

**Issue by craq2017** [caiiiycuk/js-dos.com#30]
/usr/local/rvm/rubies/ruby-2.1.10/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2290:in `raise_if_conflicts': Unable to activate jekyll-sitemap-0.11.0, because addressable-2.5.2 conflicts with addressable (~> 2.4.0) (Gem::ConflictError)

**Comment by caiiiycuk** [comment]
Hi! You should use ruby 2.3.1 to compile. 
```
gem install jekyll -v 2.5.3
gem install jekyll-sitemap -v 0.11.0
jekyll build
```

**Comment by craq2017** [comment]
Hi! Still the same error. Sadly.

/usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:2290:in `raise_if_conflicts': Unable to activate jekyll-sitemap-0.11.0, because addressable-2.5.2 conflicts with addressable (~> 2.4.0) (Gem::ConflictError)
	from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1410:in `activate'
	from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems.rb:220:in `rescue in try_activate'
	from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems.rb:213:in `try_activate'
	from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
	from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:29:in `block in require_gems'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:26:in `each'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:26:in `require_gems'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:19:in `conscientious_require'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/jekyll-2.5.3/lib/jekyll/site.rb:79:in `setup'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/jekyll-2.5.3/lib/jekyll/site.rb:41:in `initialize'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:29:in `new'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:29:in `process'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.3.1/bin/jekyll:23:in `load'
	from /usr/local/rvm/gems/ruby-2.3.1/bin/jekyll:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'

**Comment by caiiiycuk** [comment]
This problem related to your ruby environment. I'am not master of ruby, I can only suggest to downgrade addressable gem to 2.4.0

**Comment by craq2017** [comment]
Yay! It's works! 

gem uninstall addressable

Select gem to uninstall:
 1. addressable-2.4.0
 2. addressable-2.5.2
 3. All versions
> 2
Successfully uninstalled addressable-2.5.2
[root@2104575cd287 js-dos.com]# jekyll build
Configuration file: /js-dos.com/_config.yml
            Source: /js-dos.com
       Destination: /js-dos.com/_site
      Generating... 
                    done.
 Auto-regeneration: disabled. Use --watch to enable.

Thank you!
