### ISSUE TITLE
Freeze after 1 second of jsdos loading

### ISSUE THREAD

**Issue by mho22** [caiiiycuk/js-dos.com#302]
I tried this with `doom.jsdos` or even `digger.jsdos` and no matter what. It seems like JSDos freezes 1 second after launch. If I decide to go to another tab and come back, it runs again. Like it unfocuses logically after launch. I am using VueJS, this could be the reason maybe : 

```
<script setup>

import { onMounted } from 'vue';
import '/public/js-dos/js-dos';

onMounted( () =>
{
    emulators.pathPrefix = 'js-dos/';

    const root = document.getElementById( 'js-dos' );

    const options = {};

    Dos( root, options ).run( 'doom.jsdos' );
});

<template>

    <div id="js-dos" />

</template>
```

**Comment by mho22** [comment]
It was due to the hidden message about the mouse. It was somehow hidden. Strange. Closed.

**Comment by caiiiycuk** [comment]
> It was due to the hidden message about the mouse. It was somehow hidden. Strange. Closed.

Yeah, this message is annoying, probably it's better to remove it. Also do you want to try 8.xx?

**Comment by mho22** [comment]
I would be glad to try it, I dove into the repo but it was not easy to understand. Do you have a documentation link for version 8.xx ?

**Comment by caiiiycuk** [comment]
You are right, there is no docs yet. I need to wirte something asap, cause 8.xx is already pretty good. Will try to do it in a week. You mostly interested in running js-dos bundles?

**Comment by mho22** [comment]
@caiiiycuk Firstly, yes. Could you provide some insights for version 8.xx? Perhaps direct me to a file in the repository that I could concentrate on to make it compatible with Vue on my end? I wouldn't pressure you to hastily write documentation.

**Comment by caiiiycuk** [comment]
> @caiiiycuk Firstly, yes. Could you provide some insights for version 8.xx? Perhaps direct me to a file in the repository that I could concentrate on to make it compatible with Vue on my end? I wouldn't pressure you to hastily write documentation.

Just deployed a small part of documentation, but good to start https://js-dos.com/overview.html
