### ISSUE TITLE
Backport emulators-ui to v8

### ISSUE THREAD

**Issue by NightMingGit** [caiiiycuk/js-dos.com#304]
Does v8 still not support touch mapping on mobile devices?

**Comment by caiiiycuk** [comment]
Hi, yes. This part is under development/rethink. You can use v7 for mobile support.

**Comment by NightMingGit** [comment]
> Hi, yes. This part is under development/rethink. You can use v7 for mobile support.

Is it possible to use the UI from version 7 with the engine from version 8? Are they compatible?

**Comment by caiiiycuk** [comment]
Damn 🤦 Actually yes, I can add virtual controls in read only mode. Should be easy to do. Let me finish current task and then I look into it.

**Comment by NightMingGit** [comment]
> Damn 🤦 Actually yes, I can add virtual controls in read only mode. Should be easy to do. Let me finish current task and then I look into it.

Does this mean that the emulators-ui from v7 can be used for v8?

**Comment by caiiiycuk** [comment]
I think so, but need to add some integration code...
