### ISSUE TITLE
mount directory to cdrom doesn't work

### ISSUE THREAD

**Issue by guozanhua** [caiiiycuk/js-dos.com#306]
below config line doesn't work in jsdos.conf
==================
mount d i:\ -t cdrom
=================

**Comment by caiiiycuk** [comment]
Which version of js-dos, should work fine in v8.xx

**Comment by guozanhua** [comment]
in v7.xx,

**Comment by guozanhua** [comment]
in v8.xx, how to run imgmount 2 sockdrive wss://localhost:8001 system dos7.1-v1, load from localhost

**Comment by caiiiycuk** [comment]
typically no need to use sockdrive for dos. just use v8 and use imgmount normally

**Comment by guozanhua218** [comment]
> typically no need to use sockdrive for dos. just use v8 and use imgmount normally

thanks

**Comment by guozanhua218** [comment]
by the way,how to use sockdrive vialocalhost for win95

**Comment by guozanhua218** [comment]
some dos game need audio cdrom will result the jsdos bundle file is too big, these game will caused can't run on ios devices, so it has to be run via socket drive

**Comment by caiiiycuk** [comment]
> by the way,how to use sockdrive via localhost for win95

You can run sockdrive locally, but it is not finished yet, I will provide docs soon. But anyway I think you can't emulate audio cdrom with sockdrive, because sockdrive is used to be an HDD drive not cdrom. You need some software to emulate cdrom from hdd, like daemon tools or something.

**Comment by guozanhua218** [comment]
> > by the way,how to use sockdrive via localhost for win95
> 
> You can run sockdrive locally, but it is not finished yet, I will provide docs soon. But anyway I think you can't emulate audio cdrom with sockdrive, because sockdrive is used to be an HDD drive not cdrom. You need some software to emulate cdrom from hdd, like daemon tools or something.
Can daemon tools  work with js-dos together?

**Comment by caiiiycuk** [comment]
https://js-dos.com/deployment.html#new-deployment
