### ISSUE TITLE
Large file ROMs do not work in iOS Safari browser

### ISSUE THREAD

**Issue by zslliu** [caiiiycuk/js-dos.com#307]
Roms that exceed 200M cannot be run in ios safari.For example, Heroes of Might and Magic II.How to fix it？
Iphone: iphone Xs
System version: 17.4.1
![未标题-1](https://github.com/caiiiycuk/js-dos/assets/36098473/a86a26ca-0767-4533-b0ab-b67932ec9a51)

**Comment by caiiiycuk** [comment]
1st. You need to use v8. 
2nd. For large rooms there is sockdrive support (network drives). I will write docs on it asap.

**Comment by caiiiycuk** [comment]
As far I know on 8.xx 200mb rooms should works just fine on iOS
