### ISSUE TITLE
[Question] Can I upload game image files for Windows 95 to cloud storage?

### ISSUE THREAD

**Issue by skyksit** [caiiiycuk/js-dos.com#309]
I am using a subscription service. 
Can I upload a game image for Windows 95 already created on my PC to cloud storage? 
If I want to service a game for Windows 95 in the cloud, do I have to fork an empty image and install it directly there?

Since I live in Korea, the download speed of the diablo game you provided is very slow. Initially, the intro video does not play at startup. It can be played only after some time has passed.

**Comment by caiiiycuk** [comment]
Yeah, for this case mirror should be created, this is possible if some one take care of it
