### ISSUE TITLE
Bootable disk images?

### ISSUE THREAD

**Issue by neozeed** [caiiiycuk/js-dos.com#31]
I have some raw hard disk images, I'd love to use, but I don't see any good way to accomplish this.

I tried to do something like this in dosbox.conf

`[autoexec]`
`mount d: "."`
`d:`
`z:imgmount c win21r.img -t hdd -size 512,16,2,512`
`boot -l c:`

But it just crashed out.  The zip file I'm trying to use is here [win21russian_z.zip](http://vpsland.superglobalmegacorp.com/jdosbox/win21russian_z.zip).

Thanks for any/all help!  Love this javascript DOSBox!

**Comment by caiiiycuk** [comment]
Main problem of creating bootable images is that they required infinite loops. They not supported yet by js-dos.com. It can be done by using emterpreter technique, I want to release special version of js-dos, that will support running this kind of code. I hope I release that version soon.

**Comment by caiiiycuk** [comment]
Hope fixed:
http://js-dos.com/Tetris/
