### ISSUE TITLE
I have some DOS games with inaccurate mouse positioning. Can this issue only be resolved by modifying mouse locking? Can modifying the emulator's source code solve the problem?

### ISSUE THREAD

**Issue by NightMingGit** [caiiiycuk/js-dos.com#313]
I have some DOS games with inaccurate mouse positioning. Can this issue only be resolved by modifying mouse locking? Can modifying the emulator's source code solve the problem?

**Comment by caiiiycuk** [comment]
Yes you can.

**Comment by NightMingGit** [comment]
> Yes you can.

For games where the mouse position is inaccurate and mobile devices cannot use the mouse lock mode, does this mean that such games cannot be played on mobile devices? Do you have any good solutions?

**Comment by caiiiycuk** [comment]
I didn't get it. It almost depend on concrete game. There is a lot of options

**Comment by NightMingGit** [comment]
> 我不明白。这几乎取决于具体的游戏。有很多选择
On a mobile device, adjusting the offset can be a solution to fix inaccurate mouse position.
