### ISSUE TITLE
I have a DOS game, and an error occurs when calling the local save file. What could be the cause?

### ISSUE THREAD

**Issue by NightMingGit** [caiiiycuk/js-dos.com#314]
![image](https://github.com/caiiiycuk/js-dos/assets/92633021/819546b0-5e16-4d8e-ad7f-5f220ced4d57)
![image](https://github.com/caiiiycuk/js-dos/assets/92633021/62cd80b8-fcaa-4c3d-a4ea-1e2e558f7846)

**Comment by caiiiycuk** [comment]
HI, thank you for testing. Can you please write bugs with more context. Provide jsdos file to test and your integration code. It's not clear what happening.

**Comment by NightMingGit** [comment]
> HI, thank you for testing. Can you please write bugs with more context. Provide jsdos file to test and your integration code. It's not clear what happening.

https://www.123pan.com/s/sFV5jv-g2ivd.html  

This is my game file. I hope you can help me take a look at the issue. When I try to use the save feature, I encounter this error.

**Comment by caiiiycuk** [comment]
I can't download it, cause I don't have any account here (it's not free?). Btw, Why you need to do cs.persist()? js-dos player manage saves automatically.

**Comment by NightMingGit** [comment]
> 我无法下载它，因为我在这里没有任何帐户（它不是免费的？顺便说一句，为什么需要做cs.persist（）？JS-DOS Player Manage 自动保存。

I apologize for the confusion earlier. When it comes to the save feature, adjusting the offset is not typically necessary. The save function is designed to allow players to save their progress in a game and then resume from that point later on. It should not require any adjustments to the mouse position or offset. If you are encountering issues with the save feature, it is likely unrelated to mouse position accuracy.

**Comment by NightMingGit** [comment]
![image](https://github.com/caiiiycuk/js-dos/assets/92633021/7f51e2b0-6ec4-4a3b-9fb8-4be8b91ac417)
When I click this button, I encounter this error. 
this new download url
https://drive.google.com/file/d/1_aQJkrfmxoZrH-ylwaewBM1OMvB0ZzbI/view?usp=sharing

**Comment by caiiiycuk** [comment]
This happens when there is no changes in FS.

**Comment by caiiiycuk** [comment]
I will try to remove this error message in next release, however it should not affect normal execution of player, so I am closing this.

**Comment by NightMingGit** [comment]
> I will try to remove this error message in next release, however it should not affect normal execution of player, so I am closing this.
I am still experiencing this error issue with version 8.1.4, which prevents me from saving. Additionally, I noticed that there is no .jsdos data in the indexdb.
![Snipaste_2024-07-08_14-38-27](https://github.com/caiiiycuk/js-dos/assets/92633021/8e450d34-7807-420b-a165-5dec21d42434)
![Snipaste_2024-07-08_14-41-33](https://github.com/caiiiycuk/js-dos/assets/92633021/65e000db-2c6a-4be2-8d21-87cc6db5f987)

**Comment by caiiiycuk** [comment]
Version 8.1.4 does not contains this cange, cause it's too small fix. 
It should not prevent you from saving, this is just console message.
This happens when game does not save any changes onto disk. 
Maybe you miss something in game, I mean did you use some save/load menu (inside game)?
