### ISSUE TITLE
Mouse works very slowly in WarCraft II (dosbox-x), native version works fine

### ISSUE THREAD

**Issue by guozanhua** [caiiiycuk/js-dos.com#316]
When I execute the following JavaScript, v7 is normal. And v8 is too slow.

const xyArray = [[0.25, 0.25], [0.75, 0.25], [0.75, 0.75], [0.25, 0.75]];
    let index = 0;
    setInterval(() => {
        ci.sendMouseMotion(xyArray[index][0], xyArray[index][1]);
        index = (index + 1) % xyArray.length;
    }, 500);

https://github.com/caiiiycuk/js-dos/assets/157069/2fc84f23-4dc7-4a8b-901e-d4e189df0011

https://github.com/caiiiycuk/js-dos/assets/157069/f6c0c239-292f-457f-936b-b4bec472392c

**Comment by caiiiycuk** [comment]
This happens because Warcraft II is working very slow under DOSBOX-X backend. I don't know why this happens, but if you switch to DOSBOX it will work smooth. Also with other games, for example simcity sendMouseMotion works fine with dosbox-x.

**Comment by caiiiycuk** [comment]
You need to enable capture mouse for the game, if you use dosbox-x backend. Then it works fine
![изображение](https://github.com/caiiiycuk/js-dos/assets/1727152/ba97aebd-6e4e-4e84-8713-e2a7e03a7fa4)
