### ISSUE TITLE
Any known issues with SCI games?

### ISSUE THREAD

**Issue by jeffnyman** [caiiiycuk/js-dos.com#32]
I'm trying to run a home-built game that was built with the SCI engine (old style Sierra) and that does run in DosBox. I have the following file in place on my server:

http://testerstories.com/files/testquest.html

If you click Start, you'll see that it loads up the SCIV.exe and then once everything is loaded up (no errors in the console), I just get dumped at a DosBox Z:\ prompt.

There is a TestQuest.exe in that zip file as well but I don't call that because that's just a DosBox executable wrapped up to read a dosbox.conf file. But all that conf file does is call "sciv.exe" anyway, which is the same thing I'm doing with the page above. The line I have in place in the script is:

    dosbox.run("http://testerstories.com/files/TestQuest.zip", "./SCIV.EXE");

Again, the game definitely runs in DosBox on its own so I wasn't sure if this had something to do with SCI or with a specific configuration that I might not be aware of.

**Comment by caiiiycuk** [comment]
Hi. The problem it that you setup to run "./SCIV.EXE" file but actually there is no file with path './SCIV.EXE' in archive. You should use correct path. Worked solution:
```
dosbox.run("http://testerstories.com/files/TestQuest.zip", "./TestQuest/SCIV.EXE");
```

Also if you want to use dosbox.conf you should put it into root of archive.

**Comment by jeffnyman** [comment]
Thank you for the assistance. You are completely correct. I had the incorrect parameters.
