### ISSUE TITLE
Adding new options to emulator API

### ISSUE THREAD

**Issue by shaylevary** [caiiiycuk/js-dos.com#321]
Hi,

I would like to suggest adding this option to the script api (as default):

- Aspect (16:9, 4:3, Fit, ect… )
- Render (webgl, canvas) 
- Image Rendering (Pixelated, Smooth)

It will be also nice if you'll add the "saving" button on "kiosk mode", otherwise, user won't be able to save their game progress.

**Comment by caiiiycuk** [comment]
Fixed in v8.1.15, docs is here: https://js-dos.com/player-api.html

--
Regarding to kiosk mode. It's not clear hot to do this, because kiosk mode  should not have any ui. You can call setKiosk(false) to bring panels back. I mean you can add some ui button to switch between kiosk and not.
