### ISSUE TITLE
bug: win95 game screen r and b color channel is flipped

### ISSUE THREAD

**Issue by guozanhua** [caiiiycuk/js-dos.com#322]
run with dosbox-x windows standalone version,the game screen as below
![2e2065cdffeea4a69bcbab347bfb64f](https://github.com/caiiiycuk/js-dos/assets/157069/775b5ab3-74e1-4e8e-a600-856ca65068d7)

run with js-dosboxX version, the game screen  as below
![0d7e07cb19f556ce862c9e972e5a85b](https://github.com/caiiiycuk/js-dos/assets/157069/bc19fe96-4441-4e34-8fff-d8a6053662a5)
looks like r and b channel is flipped

**Comment by guozanhua** [comment]
but run the diablo i hellfire  with the same win95image, the game screen color display is correct

**Comment by caiiiycuk** [comment]
This depends on color mode. 256 colors works fine, 16/32 bits are swapped

**Comment by guozanhua** [comment]
> This depends on color mode. 256 colors works fine, 16/32 bits are swapped

so this bug is easy to fix, modify the emulator source code

**Comment by caiiiycuk** [comment]
Fixed in v8.1.19
