### ISSUE TITLE
 Feature Request: More buttons to virtual keyboard

### ISSUE THREAD

**Issue by sounddrill31** [caiiiycuk/js-dos.com#324]
It'd be great if someone could add Double Quote, = and Add buttons to the keyboard, quite helpful in turbo C++

Reposted from [here](https://github.com/js-dos/repository/issues/16)

**Comment by caiiiycuk** [comment]
Now you can redesing keyboard: https://js-dos.com/virtual-keyboard.html

But double quotes still not working...

**Comment by caiiiycuk** [comment]
closing this as duplicate of #325
