### ISSUE TITLE
 Turbo C++ - Some keys don't work

### ISSUE THREAD

**Issue by sounddrill31** [caiiiycuk/js-dos.com#325]
The following keys don't work at all with js-dos:
+ and subsequently, =
' and subsequently "

I've tried to replicate it on dosbox-staging and it works OOTB without any need for mapper(even if an invalid mapper is provided)

Here's my repo: https://github.com/sounddrill31/TurboCPP-Web
Here's my instance: https://sounddrill31.github.io/TurboCPP-Web/

Reposted from [here](https://github.com/js-dos/repository/issues/15)

**Comment by caiiiycuk** [comment]
Probably fix is discribed in #276

**Comment by caiiiycuk** [comment]
Fixed in v8.2.3

**Comment by sounddrill31** [comment]
Works great, thanks a lot!
