### ISSUE TITLE
Feature request: Add api support for "ScaleControls" (virtual keys resize)

### ISSUE THREAD

**Issue by shaylevary** [caiiiycuk/js-dos.com#326]
Hi,

It will be great if you can please add support for set the mobile virtual keys size from the script api using the "ScaleControls" command, similar as it work on v7.

Also, I would like to suggest adding option for D-Pad support, so I will be able to set from the script menu or from api if the script show nipple or d-pad as default (some games are more easy and accurate to play with d-pad).

Thank you.

**Comment by caiiiycuk** [comment]
Starting from v8.1.16 you can set `{ scaleControls: x }` in options.
