### ISSUE TITLE
remove account/please login and networking

### ISSUE THREAD

**Issue by AlinGheaja** [caiiiycuk/js-dos.com#328]
hello
i want to use jsdos as offline for a few games and i want "account" / "please login"  and "networking" options removed from the UI so that they dont show anymore.
thank you kindly

**Comment by AlinGheaja** [comment]
@caiiiycuk please dont forget about me

**Comment by caiiiycuk** [comment]
Starting from v8.1.16 you can set `{ noCloud: true }` in options.

**Comment by AlinGheaja** [comment]
![image](https://github.com/user-attachments/assets/3a2f01c8-7454-47b6-9ab7-5c23fc35f7a4)
what about this ? after turning it on it asks for an account ?

thank you, it works great !
