### ISSUE TITLE
Add classnames to all sidebar buttons

### ISSUE THREAD

**Issue by shaylevary** [caiiiycuk/js-dos.com#329]
Hi,

I will appreciate if you can please add classnames for each sidebar buttons.
for example this buttons got classnames:
**save-button** sidebar-button overflow-hidden undefined
**network-button** sidebar-button  inactive undefined
**fullscreen-button** sidebar-button undefined

While this buttons are missing classnames:
Keyboard, Screen Render, ...

**Comment by caiiiycuk** [comment]
I don't think it's the worth to do, I don't want to use such type of contract in js-dos player.
