### ISSUE TITLE
OpenTTD

### ISSUE THREAD

**Issue by Luraktinus** [caiiiycuk/js-dos.com#33]
It would be neat to have OpenTTD running in the browser, please make it possible<3

**Comment by caiiiycuk** [comment]
Already done: epicport.com/en/ttd

:)

**Comment by Luraktinus** [comment]
is it open source? 
what is openttd.js?

**Comment by caiiiycuk** [comment]
OpenTTD.js is compiled by emscripten version of http://www.openttd.org/en/.
Yes it is open source

6 янв. 2018 г. 7:03 пользователь "Luraktinus" <notifications@github.com>
написал:
