### ISSUE TITLE
Correct way to dispose the player in v8?

### ISSUE THREAD

**Issue by muditjuneja** [caiiiycuk/js-dos.com#330]
Hey, I am trying to use this in react and almost everytime, anyone leaves the game page, they can still hear the game sounds. I can fix this by hard reloading the page anytime but this doesn't seem like a good way. What are my options? Happy to support as well if it is not there yet.

Thanks team and awesome work!

**Comment by caiiiycuk** [comment]
Yeah, I forgot to add dispose method, I will try to close this issue on next week

**Comment by caiiiycuk** [comment]
Starting from v8.1.16 you can use `props.stop()` to dispose player and free all resources.

**Comment by muditjuneja** [comment]
Awesome @caiiiycuk!! Let me pull the latest version. Thanks for quickly addressing it.
