### ISSUE TITLE
override dosconfig even with the url?

### ISSUE THREAD

**Issue by muditjuneja** [caiiiycuk/js-dos.com#332]
Hi Team, I am trying to override dosbox config like below - 

`
instance = window.Dos(root, {
                url: bundleUrl,
                theme: 'night',
                backendLocked: true,
                dosboxConf:{
                    sensitivity:50
                }
            });
`

But this doesn't seem to work and the setting from inside the package are being set. Is this possible? If yes, can anyone help?
If it is not there,I I feel like this is something we can support right? I can contribute if anyone can give me the direction from where to start.

Thanks team and awesome work!

**Comment by caiiiycuk** [comment]
Please read the docs. Dosbox conf is readed from bundle (cause you use URL option) 

https://js-dos.com/jsdos-bundle.html

**Comment by muditjuneja** [comment]
I figured another way to override a few configs. I am able to set `jsdos.8.mouse_sensitivity` directly using localstorage.set and it works. Thanks!

**Comment by caiiiycuk** [comment]
Starting from v8.1.16 you can set `{ mouseSensitivity: xx }` in options.

**Comment by muditjuneja** [comment]
This is awesome. Thanks for doing this.
