### ISSUE TITLE
How to set controls in v8? Can we override the controls from the UI?

### ISSUE THREAD

**Issue by muditjuneja** [caiiiycuk/js-dos.com#334]
Hi @caiiiycuk I wonder what is the default config for keymaps. I know we can pass the mapping in the dosbox.conf but just wanted to check if that can be overridden while instantiating of the player?

**Comment by caiiiycuk** [comment]
Is it what are you looking for: https://js-dos.com/virtual-keyboard.html

**Comment by eanth** [comment]
Hello @muditjuneja Some games such as DOOM (DEFAULT.CFG) and Duke Nukem 3D (DUKE3D.CFG) have config files that can be set and take precedence for default control mappings. 

Is this what you are looking for?
