### ISSUE TITLE
Need help in running dos games without jsdos files.

### ISSUE THREAD

**Issue by beingretrogamer** [caiiiycuk/js-dos.com#335]
Hey, I am trying to run a few dos games but I don't want to go through the bundle creation. My code looks like - 
```

 <script>
        Dos(document.getElementById("dos"), {
            dosboxConf: `
[dos]
ver=7.1
hard drive data rate limit=0
floppy drive data rate limit=0

[cpu]
cputype=pentium_mmx
core=auto
integration device=true

[sblaster]
sbtype=sb16vibra

[autoexec]
mount c:
cd ANTH2
ANTHILL2.EXE
`,
            onEvent: async (event, ci) => {
                console.log("ci", ci);
                if (event === "ci-ready") {

                    console.log(await ci.config());
                    // ci: CommandIterface is ready
                    console.log(ci.fs);
                }
            },
        });
    </script>
```

How do I upload the zip file inside the dosbox and then run the file? I am not able to see any working example. I have set an [autoexec] block but it fails as files are not found. Can you help?

**Comment by beingretrogamer** [comment]
I am V8 and following the docs  here - https://js-dos.com/working-with-fs.html#write-file-to-fs

Even if I upload a file using `fsWriteFile`, how do I run it? I feel like [autoexec] wont work as the file will be uploaded later.

**Comment by caiiiycuk** [comment]
Hi, you are right, this is not documented. Actually it can be done by passing [InitFS](https://github.com/caiiiycuk/emulators/blob/ecfc7dd224790d2af51a7cdf5cea5066c34abb2b/src/emulators.ts#L23-L30) instead of url. It's better to wait while I test it and document. But actually why you need this, you always can create zip archive on the fly with some open source js lib. With level 0 it will be work very fast.

I am very curious about use case, why you can't pre-create a bundle?

**Comment by beingretrogamer** [comment]
Hey! Thanks for the quick reply. I am trying to download game packages from archive.org when requested and after the download is finished it becomes playable. I am not sure if I follow what you mentioned about creating a zip archive? I already have a zip archive? Do you mean create bundle on the fly? Can you help me with an example? I don't think the latest docs has any?

**Comment by beingretrogamer** [comment]
Also, a quick question around this old archived repostiory - https://github.com/js-dos/dos.zone.db
Are the bundles still valid?

**Comment by caiiiycuk** [comment]
1. Yeah I mean create bundle on the fly, you can use [zip.js](https://gildas-lormeau.github.io/zip.js/) to add dosbox.conf
2. No I think bundles not valid anymore

**Comment by beingretrogamer** [comment]
Ohh so you mean, I just attach the dosbox.conf and keep the jsdos.json empty as it is already an optional config. I think that would work. Is there a master dosbox config that I can use for majority of games? Thank you! Let me give that a try and get back to you.

On the 2nd point, are the bundles all closed source now? Maybe I could use these existing only in my project where I am letting users build personal dos cabinets (possibly self hosted locally or otherwise)

**Comment by beingretrogamer** [comment]
Also, any update on this? Can I get access to the library? IMO if I ask anyone else they would just tell me to scrape it all haha! Checking if there is any right way available? Thanks for all the hard work on this!

**Comment by caiiiycuk** [comment]
I don't care if somebody scrape it, actually is a best way to popularize jsdos - share bundles repo. I just do not have enough time to do it

**Comment by beingretrogamer** [comment]
Hahaha, true that! I'm already doing that with both js-dos and dosbox, spreading the word everywhere! I'm working on a project very much like doszone but with a modernized UI/UX. I’m planning to open-source the entire UI, which is built on Gatsby.

You can check it out here: https://weplaydos.games/

I have a proposal for collaboration: how about we rebuild dos.zone together using this new UI? We could include all the free and premium features, making it even more user-friendly and accessible. Let me know what you think!

**Comment by caiiiycuk** [comment]
I mostly doing a jsdos project, dos.zone is not so important part, I do not want to invent more time on it, and actually I like what it looks like. Thank you for interest in project

**Comment by caiiiycuk** [comment]
Added in v8.1.19, documentation https://js-dos.com/run-without-bundle.html#provide-dosbox-conf-directly
