### ISSUE TITLE
Can you share an example on how can I save states in v8?

### ISSUE THREAD

**Issue by beingretrogamer** [caiiiycuk/js-dos.com#337]
Hi @caiiiycuk hope you are doing good. Do you mind sharing a quick example on how can I save the games locally. And then upload the state to continue? Is this even possible in v8?

Thanks!

**Comment by caiiiycuk** [comment]
V8 do this automatically, it saves state in jsdos cloud if user is logged in, otherwise state is stored in indexed db of browser. Just do not forget to press save icon.

**Comment by beingretrogamer** [comment]
Thanks for the quick response. The thing is I am on the kiosk mode and am
interested in implementing the auto saves. Is that supported that way? Can
we expose the function being called when the user clicks in the normal mode?

**Comment by caiiiycuk** [comment]
Kiosk mode is harder, cause saves also use login information. If you can't activate normal mode (e.g. some ui that toggles it), then you need implement it by you own using CommandInterface instance.

**Comment by beingretrogamer** [comment]
Too bad! Do you mind sharing a quick snippet for reference?

Also, please point me to the file where saving happens. I would be happy to
contribute this if you feel like it is feasible.

Thanks!

**Comment by caiiiycuk** [comment]
If you doesn't  care about login stuff, I can expose the api method to trigger save code path. It will store only in indexed db

**Comment by beingretrogamer** [comment]
Yep that would do the trick. Would it be a async method? Maybe return
entire save state?

**Comment by beingretrogamer** [comment]
Hey there! Just checking in if there is any update on this one?

**Comment by caiiiycuk** [comment]
Added in v8.1.19, example:

```js
cost props = Dos(elem, options);
props.save(); // will trigger save function, it return Promise<boolean>
```

documentation: https://js-dos.com/player-api.html#dosprops

**Comment by beingretrogamer** [comment]
I am able to save the state and it adds an entry in indexedDB. Just after saving, I am retrieving the save data and converting it into a file to be stored locally. 
Now, how do I load the file before the game starts? I mean there is no load method and I tried initFs and it doesn't seem to work. The only thing that works is if I create an entry the indexedDB like below - 

`objectStore.add(_result, 'https://storage.yandexcloud.net/doszone-uploads/personal-v2/dzapi/guest/' + bundleName);`

`_result` is my `ArrayBuffer` but this is not very intuitive from the api perspective due to 

1. Why this file name convention?
2. I have to manually interact with the indexedDB which exposes very low level apis and is already a trouble
 
My 2 cents - 
1. Just like we have a save method, there should be a method which loads this data for merging.
2. The save method should return the savedState instead of the boolean value so that there is no need to interact with indexedDB.

Let me know what are your thoughts! Again, I would be happy to contribute if you feel like this makes sense.

Thanks!

**Comment by caiiiycuk** [comment]
I think you missunderstood the idea of js-dos project. js-dos player is built to run jsdos bundles in web, it works like a blackbox you provide bundle and it manages everything including save/load functions. This new api is made in case when you use kiosk mode, you call the save method and player will save progress same as when you press save button in UI. The loading happen automatically by player itself, it works while you use same url. 

There are two options:
1. if you want to add new feature to save progress locally in a file on PC and then load it somehow, then you need to design also UI part of player, I mean clients of player should understand how to use this new option.
2. If you want to build custom integration, like your own player with this feature, then you need to use emulators package instead, js-dos built on top of it. it has lowlevel api to implement save feature whatever you want.
