### ISSUE TITLE
win98 install daemon fail

### ISSUE THREAD

**Issue by citee520** [caiiiycuk/js-dos.com#342]
**[version]**
    jsdos/emu version: 8.1.19/8.1.9 (34a08e4c41ba7b5e93d56c9854e0c42f)
**[step]**
    1. select win98_zh to start, upload 'instmsia.exe' and 'daemon347.exe'
    2. mount d ./
    3. boot c:
    4. open e, install instmsia.xe and daemon347
**[Descripten]**
   Can't install successful when install daemon347.exe, if copy file to desktop to install again, It's fine.

**Comment by caiiiycuk** [comment]
Why you need this? Just fork Win98 image it already have daemon tools installed

**Comment by citee520** [comment]
I want to play mandarin game, use win98 will general Garbled characters.

**Comment by caiiiycuk** [comment]
Probably you need to install Windows Installer 2.0 https://js-dos.com/install-windows.html#windows-installer-2-0-windows-9x

**Comment by citee520** [comment]
I've already installed it, and the installation was successful. But I find it strange that it only worked when I placed it on the desktop (C:). When I uploaded it to the web and mounted it, the installation failed.

**Comment by caiiiycuk** [comment]
I didn't get what you mean. When you use jsdos sockdrive, can you install it from drive c?

**Comment by citee520** [comment]
<img width="867" alt="Daemon_fail" src="https://github.com/user-attachments/assets/7ecd1a9c-5076-44f1-8204-8184db72f938">
<img width="875" alt="Daemon_successful" src="https://github.com/user-attachments/assets/fbe7abf2-9ed5-47a5-ae33-c4eecdb108af">

I just tried it a few more times and realized it has nothing to do with what I mentioned earlier. It seems that the installation always fails the first time but works on the second attempt.

**Comment by caiiiycuk** [comment]
🤔 can I close issue?

**Comment by citee520** [comment]
Yes, thanks your answer.

**Comment by caiiiycuk** [comment]
@citee520 if possible share the link when you done)
