### ISSUE TITLE
QWERTY to AZERTY

### ISSUE THREAD

**Issue by florentbolo** [caiiiycuk/js-dos.com#344]
Hi there, 

Thanks for your amazing work !
Is there a way to switch from QWERTY config to AZERTY in the player API ?

Thanks

**Comment by caiiiycuk** [comment]
Hi, thank you. Unfrotinatelly keyboard is something in low priority. I never touched it, you can try use dosbox-x mapper to map keys.

**Comment by florentbolo** [comment]
Thanks for your answer.
Do I use dosboxConf in Player API ?

**Comment by caiiiycuk** [comment]
Is better to have jsdos bundle (it's a zip archive). You can create one with [dos.zone/studio](https://dos.zone/studio-v8/), then you can edit conf file (.jsdos/dosbox.conf) and also add [mapper file](https://www.dosbox.com/wiki/Mapper).

Also is better to look wiki of dosbox/dosbox-x how they solve this problem?

**Comment by florentbolo** [comment]
I've recreate a bundle with [dos.zone/studio](https://dos.zone/studio-v8/) and the keyboard is set good directly
Thanks !

**Comment by caiiiycuk** [comment]
@florentbolo can you say how you change the keyboard layout?

**Comment by florentbolo** [comment]
I didn't change the keyboard layout, i've just make a new bundle of doom shareware and arrow are directly well configured so it's enough for me.
