### ISSUE TITLE
Bug: Problem with creating a jsdos.json file dynamically using this InitFS option

### ISSUE THREAD

**Issue by shaylevary** [caiiiycuk/js-dos.com#349]
Hi,

I would like to have an option to create the jsdos.json settings file dynamically from the js script/api bt using one of the following options:
1. By creating the file "On the Fly" using the InitFS option. 
currently it generates the file properly, but the settings of the json file, such as the virtual buttons - don't work.
The problem may be related to the length of the extension characters of the file jsdos.json, which contains 4 characters instead of 3 (which is only support by dos).

2. Another solution can be achived by adding an option to the script, like "jsdosjson", where I can dynamically insert the Json code without the need to create a special bundle (similar to the "dosboxconf" option).

Thank you.

**Comment by caiiiycuk** [comment]
Fixed in v8.3.2, https://js-dos.com/run-without-bundle.html#provide-dosbox-conf-directly
