### ISSUE TITLE
fsWriteFile function cannot affect files in DOSBox in real time

### ISSUE THREAD

**Issue by duanyu5871** [caiiiycuk/js-dos.com#354]
When I add some files to the DOSBox system using the fsWriteFile function, the new files do not appear when I use the `DIR` command in the corresponding path. The previously added files only become visible after I using a command like `MD testfolder` to modify the file system. That' 

for example(Assuming that `ci `has successfully started and initialized):
```
[In console]
ci.fsWriteFile("./file3.txt",window.file11)  // window.file11 is a Uint8Array
[In dosbox]
DIR  // file3.txt will not appear
MD testfolder
DIR // both file3.txt and testfolder will appear
```
This is quite puzzling, so what solution should I use to refresh the file system directly in the console instead of creating a new folder in DOSBox?

Thank you

**Comment by caiiiycuk** [comment]
Yeah DOSBOX/X can't see changes until you remount drive :cry:

**Comment by RodionGork** [comment]
not necessarily remount, there is `RESCAN` command also, so perhaps you can utilize it, say, adding file and automatically executing rescan before your code runs

**Comment by duanyu5871** [comment]
Great thanks, I also found a solution in dosbox-x official wiki in [https://dosbox-x.com/wiki/#Home#_frequently_asked_questions_faq](https://dosbox-x.com/wiki/#Home#_frequently_asked_questions_faq)
it says
> you can let DOSBox-X synchronize them automatically with config options, or they may become desynchronized if there are changes outside DOSBox-X (DOSBox-X caches the file list on a directory/drive by default to improve its performance). To synchronize the content of mounted local drives with the host file system automatically, you can set nocachedir=true in [dosbox] section of the config file. Alternatively, you can synchronize individual drive with the host file system by adding the -nocachedir option to MOUNT command, e.g. MOUNT D D:\ -nocachedir.

This setting can really work and synchronize the content of mounted local drives in dosbox-x command interface. However, I found a new interesting question, files built in win95/win98 won't appear in FS and file changes in FS won't appear in win OS. This problem appeared in both official dosbox-x and jsdos. It maybe caused by other reasons and no official solution for now.

**Comment by caiiiycuk** [comment]
Great to know!

**Comment by caiiiycuk** [comment]
Can I close this?

**Comment by duanyu5871** [comment]
Yes, of course
