### ISSUE TITLE
Error saving progress in indexedDB in sockdrive alternative

### ISSUE THREAD

**Issue by grechucia** [caiiiycuk/js-dos.com#355]
Hello. I’m trying to serve win95 games via bundles, not sockdrives. Everything’s working very good when backend is forced to dosboxX in config.  Bundles downloading and extracting correctly, windows 95 loading and games are playable, but I can’t get saves states to work. (Console message: can’t connect to indexedDB). I’m presuming that api detect win95 game and require sockdrive format. Is it possible to implement some sort of workaround in this case to store progress locally?

Bundle structure
   -.jsdos
         - dosbox.conf 
   -windows95.img
   -game_cd.iso

In .jsdos/dosbox.conf I’m mounting img/iso using imgmount and booting windows. 

Why? It’s seamless for me and I have multiple ready to go bundles with win95 games that would be nightmare to convert to sockdrives.

**Comment by caiiiycuk** [comment]
Hi, non sockdrive logic to store progress is to get a diff between original FS and FS when you press save button. But win9x forces us to use img files, this means that for non sockdrive bundles the whole image will be saved in indexed db each time, this is no sense and can easily break the browser limit. This is one of the major reason to introduce sockdrive. 

But, you can use sockdrive, why not? I mean you can create own deployment

**Comment by grechucia** [comment]
That's very reasonable - approch you've taken makes a lot of sense. Thanks for your answer. 
I've tried to deploy my own sockdrive server but getting client error:

VM5:1  WebSocket connection to 'ws://192.168.1.61:8001/cache' failed: 

No drive cant boot, for example windows 95 hanging on boot screen.

Tried non secured and secured (self signed cert) backend server on localhost and another ip - same message everytime.



Error message:

![1](https://github.com/user-attachments/assets/048d1a8a-3de3-4486-99d2-35fcccca378b)


BTW is there any chance converting already builded .jsdos bundle or windows IMG file to your backend server format?

**Comment by caiiiycuk** [comment]
The error is realted to outdated sockdrive server, I will publish new one soon. IMG -> sockdrive is possible but no tools exists (

**Comment by caiiiycuk** [comment]
@grechucia please use this version of sockdrive backend (https://cdn.dos.zone/custom/tools/sockdrive-backend-15.11.2024.zip)

**Comment by grechucia** [comment]
I did tested it. Everything working fine now, will use it for sure, but how can I write to drives on my own backend server?

I mean - my goal here is to create new Windows 95 installation from empty drive, configure it and then use browser saves for game progress. Uploading to filesystem is clear, seen youtube video, but i can't switch "WRITABLE FAT DRIVES", every change get deleted.

**Comment by caiiiycuk** [comment]
To fix this, you can add your email to server config, as explained here https://js-dos.com/deployment.html#new-deployment. You can write as many emails as you want, all of them will get full access  to backend, another option is to buy js-dos subscription.

**Comment by grechucia** [comment]
Thanks for your explanation and updated backend files. Working fine right now.
