### ISSUE TITLE
Question: Possible to run TASM in js-dos?

### ISSUE THREAD

**Issue by zdxsector** [caiiiycuk/js-dos.com#356]
I am currently researching for "Compiling and running TASM code in web app" and then my research lead me here with js-dos. So the question, **Is it possible to compile and run TASM program with JS-DOS?**

**Comment by caiiiycuk** [comment]
Yep, you can run anything that could work in dos

**Comment by sounddrill31** [comment]
Hey @slaee, what's the general procedure for using tasm?

In turbo c++, we are thrown into a IDE with a text editor and all that. 

I haven't tested it but I spun it up a while back based on @qb40's jsdos file

https://github.com/qb40/tasm/releases/tag/1.0.0

https://turboc.pages.dev/tasm/

**Comment by zdxsector** [comment]
> Hey @slaee, what's the general procedure for using tasm?
> 
> In turbo c++, we are thrown into a IDE with a text editor and all that.
> 
> I haven't tested it but I spun it up a while back based on @qb40's jsdos file
> 
> https://github.com/qb40/tasm/releases/tag/1.0.0
> 
> https://turboc.pages.dev/tasm/

You can check it here: https://shreyasjejurkar.com/2017/03/27/how-to-install-and-configure-tasm-on-windows-7810/

**Comment by caiiiycuk** [comment]
@slaee did you try this? https://github.com/dosasm/masm-tasm (based in jsdos)

**Comment by zdxsector** [comment]
> @slaee did you try this? https://github.com/dosasm/masm-tasm (based in jsdos)

I have not seen it yet but cool you found that. Thanks.

**Comment by zdxsector** [comment]
I will update soon once my integration is successful.

**Comment by xsro** [comment]
I'm very glad to hear that you are also concerned about this matter. I have a very rough webapp to do this for my personal usage. My webapp  is https://dosasm.github.io/dosplay/. If there is a chance, I also want to contibute in your project.
