### ISSUE TITLE
Is there a way to pass arguments to the executable?

### ISSUE THREAD

**Issue by nfriend** [caiiiycuk/js-dos.com#37]
I'd like to be able to pass command-line arguments to the executable. Is this possible?  I've tried this:

```javascript
dosbox.run("qb11.zip", "./QBASIC.EXE /RUN MYFILE.BAS");
```

and this:

```javascript
dosbox.run("qb11.zip", "./QBASIC.EXE", "/RUN MYFILE.BAS");
```

and even this:

```javascript
dosbox.run("qb11.zip", "./QBASIC.EXE", ["/RUN", "MYFILE.BAS"]);
```

but none of these seem to have any effect.

Thanks!

**Comment by Nikomaru** [comment]
I'd like to piggy-back on to this also, inquiring as to simple cli arguments that are specific to the program.

**Comment by caiiiycuk** [comment]
Yes, you can use ```[autoexec]``` section of dosbox.conf. You should put dosbos.conf into root folder of archive

**Comment by caiiiycuk** [comment]
Now you can do this with new [js-dos 6.22](https://js-dos.com/#js-dos-622-faq-how-to-pass-command-line-arguments)

**Comment by nfriend** [comment]
Awesome, thanks @caiiiycuk!
