### ISSUE TITLE
Configuration (cycles)

### ISSUE THREAD

**Issue by dhewer** [caiiiycuk/js-dos.com#38]
Hi, thank you for your work in creating this useful script!

Is there a way to specify the cycles when running a game? I can create a batch file inside the zip, ex:

```
cycles 1000
game.exe
```

But is there any more efficient way to specify it in the code? Thank you for your help.

**Comment by caiiiycuk** [comment]
Hi! You can add dosbox config file to archive
dosbox.conf. js-dos will read it and apply before running game.
ср, 23 мая 2018 г., 2:40 Darren Hewer <notifications@github.com>:

**Comment by dhewer** [comment]
Thank you, I will try that! I have a second question but I'll start a new issue.
