### ISSUE TITLE
JS-DOS doesn't work on Firefox version 60

### ISSUE THREAD

**Issue by perelowski** [caiiiycuk/js-dos.com#40]
Hello,

I noticed that there are problems with Firefox (version 60, 64-bit) on Mac OS X (10.13.4) and Windows 7 64-bit, when running js-dos emulator. The emulator just won't run and will give you an error "A web page is slowing down your browser. What would you like to do? [Stop it] [Wait]". Can you check it on your instances of Firefox?

I have a suspicion that this might be related to the new Firefox (aka Quantum). So far other platforms tested: 

FF 52 on Windows XP - works fine.
FF 57 on Windows 7 32bit - works fine

**Comment by caiiiycuk** [comment]
Hi. Little bit strange, just checked on FF 60.0.1 Linux, works fine.

**Comment by perelowski** [comment]
Hi Alexander,
 
Thanks for info. I have removed my Firefox completely and re-installed it clean: seems like one of the plugins blocked the JS DOS from rendering (plugins are synced between various machines if you have the same profile on both on them). Case solved, thanks!
 
Piotr Kowalski
 
 
W dniu 2018-06-13 11:37:24 użytkownik Aleksander Guryanov <notifications@github.com> napisał:
Hi. Little bit strange, just checked on FF 60.0.1 Linux, works fine.

**Comment by perelowski** [comment]
Hello, I'd like to refresh this ticket... is there any chance to get this fixed?
