### ISSUE TITLE
Mouse does not work in Fullscreen Mode

### ISSUE THREAD

**Issue by perelowski** [caiiiycuk/js-dos.com#41]
Hello,

It looks like there are more problems with JS DOS. I have spotted issues with Chrome and Firefox, both on Windows and Mac OS X). In mouse-driven games, if you switch to the Fullscreen Mode, the cursor does not react to mouse moves and stays frozen in the top-left part of the screen.

The only browser that worked fine was Safari on Mac OS X.

**Comment by caiiiycuk** [comment]
Hi, thanks. I see, mouse is not working properly in full screen. Should be easy to fix.

**Comment by perelowski** [comment]
Hello,
 
Thanks for quick reply, I have also asked some of my friends to test it on different platforms and they confirmed this weird behavior. When do you plan to do the fix?
 
Piotr Kowalski
 
 
W dniu 2018-06-13 11:38:02 użytkownik Aleksander Guryanov <notifications@github.com> napisał:
Hi, thanks. I see, mouse is not working properly in full screen. Should be easy to fix.

**Comment by caiiiycuk** [comment]
Unfortunately I can't say exact date when this bug will be fixed. I keep it in mind, but I am very busy for now. Maybe someone can help to do it.

**Comment by perelowski** [comment]
Hello, I'd like to refresh this bug. Are there any chances for you to fix it? I'd be grateful! :-)

**Comment by x-wolverine-x** [comment]
Same on #35

**Comment by caiiiycuk** [comment]
Fixed in 6.22.37. Please use `fullscreen` method from command inteface.
http://js-dos.com/#js-dos-622-faq-fullscreen

If not working, please reopen and if possible provide test case.
