### ISSUE TITLE
Editing hardware configurations in js-dos

### ISSUE THREAD

**Issue by JakeTrock** [caiiiycuk/js-dos.com#43]
I've used dosbox on my home computer for leisure, but I'm wondering how would I change the dosbox.conf for js-dos? I want to play games that only work with certain cpu hardware.

https://www.dosbox.com/wiki/Dosbox.conf

**Comment by caiiiycuk** [comment]
Hi. Try to put dosbox.conf in root of your zip archive, it's should works as on PC

**Comment by JakeTrock** [comment]
alright
