### ISSUE TITLE
zip file structure

### ISSUE THREAD

**Issue by Nikomaru** [caiiiycuk/js-dos.com#44]
In testing the app, I was able to run Rogue, as it is a single file. Another test that is failing is Quick Basic 7.1, with a nested folder structure. I'm wondering if js-dos has inherent ability to allow a program to access other files in the zip? Some files are across different folders and require loading as well. What is the limitation on folder structure?

**Comment by Nikomaru** [comment]
Hmm. After double checking (in Chromium) the developer view, I see that yes, indeed, js-dos goes through the entire zip extracts everything. Then loads the appropriate file. I'm however getting some "uncaught ReferenceError: $st is not defined" at line 168 of the js-dos-api.

 Module.prototype.print = function(text) {
      text = Array.prototype.slice.call(arguments).join(' ');
      return typeof console !== "undefined" && console !== null ? typeof console.log === "function" ? console.log(text) : void 0 : void 0;
    };

I have no skill in this area. Looks like it's doing it's job and I should try a different browser.

**Comment by Nikomaru** [comment]
Firefox is giving me a type error:

TypeError: asm.js type error: Disabled by debugger       js-dos-api.js 

Sorry if this isn't very helpful. I didn't do any crazy stuff with the api. It just doesn't run the program with its dependencies, I guess.

I'm loath to throw this out there, but if it helps to take a look: http://nikomaru.tripod.com/js-dosbox.html

**Comment by caiiiycuk** [comment]
js-dos should respect file structure from archive. Try to double check files, filenames should have exact match. FS is case sensetive. From your link, you tried to run ./BIN/QBX.EXE, but actual file is: BC7/BIN/QBX.EXE.

**Comment by Nikomaru** [comment]
Okay. That was a little confusing. Looking at my zip, I see I messed it up by putting everything in a folder a the top level. Didn't even notice! And here I was thinking I was following the api with the proper location path string.
Thanks for your time!
