### ISSUE TITLE
A game can not be loaded at full

### ISSUE THREAD

**Issue by vetvennarost** [caiiiycuk/js-dos.com#46]
Hi!

I tried to use js-dos.com to play an installed game "Grand Prix 2" on my site. But it just can not be loaded till the start of the game. Instead, I get "Z:\>" on the screen.

![image](https://user-images.githubusercontent.com/37515184/49688879-d6285b00-fb29-11e8-9f60-7454b4bdb39d.png)

**Comment by caiiiycuk** [comment]
Hi, please share link to your site
