### ISSUE TITLE
Dr. Sbaitso

### ISSUE THREAD

**Issue by DigiEggz** [caiiiycuk/js-dos.com#47]
[sbaitso.zip](https://github.com/caiiiycuk/js-dos/files/2761447/sbaitso.zip)
I've been trying to get Dr. Sbaito to run but it just kicks me back to the run prompt without any complaints. Any idea of what may be wrong?

**Comment by caiiiycuk** [comment]
I run SBAITSO\SBAITSO2.EXE and it works for me. Share you initialization code, or better html page

**Comment by DigiEggz** [comment]
You helped me solve it just with that basic reply. Even though it was reading in the files I forgot I need to tell it the folder structure "SBAITSO/SBAITSO2.BAT". Thanks for the help!
