### ISSUE TITLE
DOS-box loading  issues

### ISSUE THREAD

**Issue by Holdberg** [caiiiycuk/js-dos.com#49]
I've tried to test latest distributive (6.22.10) on the three various hostings and have faced very strange problem:
dos-box stucking at 20-80% percent, depends on browser. Mozilla - 22,6%, Safari - 20,2, Chrome-80,8.
For example: [http://zapuskdva.shn-host.ru/dist3/](http://zapuskdva.shn-host.ru/dist3/)
There is no error information in console, when it getting stuck. 
And,most bizzare thing - js-dos 6.22.10 have worked perfectly on previous shn-host site of mine.

**Comment by caiiiycuk** [comment]
Hi! I think that you didn't see any error in console because you have not declare catch blocks. Try this:
```javascript
    Dos(document.getElementById("jsdos")).ready((fs, main) => {
      fs.extract("test/digger.zip").then(() => {
        main(["DIGGER.COM"])
      }).catch((err) => console.log(err));
    }).catch((err) => console.log(err));
```

or

```javascript
    Dos(document.getElementById("jsdos"), {onerror: (err) => console.log(err)}).ready((fs, main) => {
      fs.extract("test/digger.zip").then(() => {
        main(["DIGGER.COM"])
      }).catch((err) => console.log(err));
    });
```

**Comment by Holdberg** [comment]
Thanks for reply!
My mistake, added what you recommend and got this in Firefox:
1) First suggested code (at my local machine console showing the same error, but starts js-dos without problem):
> TypeError: Dos(...).ready(...) is undefined dist3:19:43
   http://zapuskdva.shn-host.ru/dist3/:19 
[INFO] Resolving DosBox 4.9% js-dos-module.ts:66:44
[INFO] Resolving DosBox 22.6% js-dos-module.ts:66:44

2) second suggested code:
>  http://zapuskdva.shn-host.ru/dist3/
[INFO] Resolving DosBox 4.9% js-dos-module.ts:66:44
[INFO] Resolving DosBox 22.6% js-dos-module.ts:66:44
CompileError: wasm validation error: at offset 603: bad type dist3:19:62 

And in Chrome:

Second code: 

> Uncaught (in promise) CompileError: AsyncCompile: Wasm decoding failed: invalid local type @+602
(index):1 Uncaught (in promise) CompileError: AsyncCompile: Wasm decoding failed: invalid local type @+602
(index):19 CompileError: AsyncCompile: Wasm decoding failed: invalid local type @+602

**Comment by caiiiycuk** [comment]
How did you create your project? Looks like http://zapuskdva.shn-host.ru/dist3/wdosbox.wasm.js no actually wasm file.
I checked it with md5 and it is not same as on js-dos site:
```
caiiiycuk@caiiiycuk-xps:/tmp$ curl http://zapuskdva.shn-host.ru/dist3/wdosbox.wasm.js -o 1.wasm
caiiiycuk@caiiiycuk-xps:/tmp$ curl http://js-dos.com/6.22/current/wdosbox.wasm.js -o 2.wasm

caiiiycuk@caiiiycuk-xps:/tmp$ md5sum 1.wasm 2.wasm 
43251c4767f04865ec730f49a7e84cf8  1.wasm
a057aefbc5eb38cdd1ba0e0f013600ca  2.wasm
```

**Comment by Holdberg** [comment]
Thanks for your time!
It was a very strange problem - sending files by Filezilla corrupting wdosbox.wasm.js, which i took from your latest release.
According to your suggestion about different files i've just uploaded wasm.js by cPanel uploader and everything seems working normal!
Once again, thank you!

**Comment by Holdberg** [comment]
Ah, and one more, may be it will help someone later.

[Guide how to fix uploading](https://www.inmotionhosting.com/support/website/file-management/corrupt-file-ftp-transfer)

**Comment by caiiiycuk** [comment]
Good to know. Thank you. I added console.error as default error output
