### ISSUE TITLE
How do you embed it into normal web pages?

### ISSUE THREAD

**Issue by ThatLinuxNerd** [caiiiycuk/js-dos.com#50]
Not exactly an issue... But I would like to see if I can use JS-DOS on a normal website.

I will close it when I get an answer.

**Comment by caiiiycuk** [comment]
What do you mean, normal website?

**Comment by x-wolverine-x** [comment]
Maybe he just want to know how to use it without to compile it? If so, then try the last compiled build 6.22.14 (https://github.com/caiiiycuk/js-dos/releases/download/6.22.14/6.22.14.zip)

**Comment by caiiiycuk** [comment]
You can use npx from node. Call this command:
```
npx create-dosbox digger
```
This will create project template with digger game. You can simple put `public` directory on static webserver. It will work.
