### ISSUE TITLE
Mouse problem

### ISSUE THREAD

**Issue by Holdberg** [caiiiycuk/js-dos.com#51]
Hello!

The current version of js-dos (6.22.14) works fine, except for one thing - the mouse does not respond to movements and clicks. (I tested it on different computers and in different browsers. The test project is a good old strategy - [Fantasy General](http://zapuskdva.shn-host.ru/6.22.14) )

Meanwhile, in an older version of js-dos (for example, [a project from a closed issue](http://testerstories.com/files/testquest.html) ), the mouse works without problems.

According to the data from the .conf file in version 6.22.14 - autolock: true and sensitivity: 100, which, I believe, is enough for interaction.
In addition - from a mobile phone I can interact and move the cursor in a test project.
Maybe I'm just missing some obvious things, but I need your help.)

**Comment by caiiiycuk** [comment]
I think it's bug. There are some changes that I does not merge to 6.22 yet. I will fix this soon.

**Comment by Holdberg** [comment]
Oh, I see! Thanks for the answer. 
I really want to try the new version of js-dos when it'll be done

**Comment by caiiiycuk** [comment]
Try latest version 6.22.17. Mouse problem should be fixed. Now autolock=false by default, I think it's much better.

**Comment by Holdberg** [comment]
Yeah, now the mouse works perfectly. Thanks!
