### ISSUE TITLE
Error while extracting archive

### ISSUE THREAD

**Issue by caiiiycuk** [caiiiycuk/js-dos.com#52]
[terb-04.zip](https://github.com/caiiiycuk/js-dos/files/2882906/terb-04.zip)

**Comment by caiiiycuk** [comment]
Seems that archive is used IMPLODE & SHRUNK method. Unfortunately libzip supports only DEFLATE method. Btw IMPLODE is very old algorithm and cost of fixing this is much more then profit. So, wan't fix.

**Comment by Benman2785** [comment]
if js-dos could understand 7zip we could save 20% for bigger titles ;)

**Comment by caiiiycuk** [comment]
@Benman2785  You already can do this, but not 7zip you need to use brotli on server side
