### ISSUE TITLE
Cannot Destroy/Kill DosBox Process

### ISSUE THREAD

**Issue by BillRamos** [caiiiycuk/js-dos.com#53]
I've tried removing the canvas from the DOM but the DosBox processes are still running in the background despite there not being a DOM object to display it.

Is there a method to kill the DosBox instance? I have yet to find this in the docs.

**Comment by caiiiycuk** [comment]
Hi, you are right I need to add this to docs. You can do this as follow:
```js
Dos(canvas).ready((fs, main) => {
        fs.extract("digger.zip").then(() => {
            main(["-c", "DIGGER.COM"]).then((ci) => {
                // ci is a command http://js-dos.com/6.22/docs/api/generate.html?page=js-dos-ci
                ci.exit(); // will exit from runtime
            });
        });
    });
```

**Comment by caiiiycuk** [comment]
Documentation is updated
