### ISSUE TITLE
MouseEvent thread safety

### ISSUE THREAD

**Issue by gogogoghost** [caiiiycuk/js-dos.com#54]
Thread insecurity when SDL process mouse event. When I send a mock mouse click event to canvas, with a mousedown and a mouseup. If I send it no delay, it not work correctly.
Like this:
```
canvas.dispatchEvent(downEvent);
canvas.dispatchEvent(upEvent);
```
This code can word correctly:
```
canvas.dispatchEvent(downEvent);
setTimeout(()=>{
  canvas.dispatchEvent(upEvent);
},200);
```

There may be problems with the mouse event queue here.
https://github.com/caiiiycuk/js-dos/blob/2c977925e94bba250ffdf5d0b9310d4c25638c81/dreamlayers-em-dosbox-em-dosbox-svn-sdl2/src/ints/mouse.cpp#L212-L232
I am not good at C++. I hope this will be useful to you.

**Comment by caiiiycuk** [comment]
Can you explain a bit what you want to achive?

**Comment by gogogoghost** [comment]
I build a site to play dos game on mobile phone, some of them need mouse event to play but mobile don't have it. So I watch the touch event and send mock mouse event to canvas. Here is [site](https://dos.gogogoghost.site), and [repository](https://github.com/gogogoghost/dosbox)
emm.....It is Chinese
https://github.com/gogogoghost/dosbox/blob/12d8d8fadd25cfb7102f39ef4259db38c1a64050/src/components/pad.vue#L324

**Comment by caiiiycuk** [comment]
Hmm, strange. Touch events should work put of the box

пт, 22 мар. 2019 г., 18:07 gogogoghost <notifications@github.com>:

**Comment by gogogoghost** [comment]
I am not use js-dos native touch event support. I just make a div cover canvas and proxy touch event, send mock mouse event to canvas with my logic. There maybe no wrong with js-dos native touch event support. But maybe some wrong with mouse event. I try to add some log print here:

https://github.com/caiiiycuk/js-dos/blob/6.22/dreamlayers-em-dosbox-em-dosbox-svn-sdl2/src/gui/sdlmain.cpp#L2184-L2222

When I send a mouse down event and a mouse up event no delay. It will not work but can log correctly. So I think  the problem should in "INLINE void Mouse_AddEvent"

**Comment by caiiiycuk** [comment]
Can you create simple test page that demonstrate problem, I will take a look

пт, 22 мар. 2019 г., 23:19 gogogoghost <notifications@github.com>:

**Comment by gogogoghost** [comment]
By some test I find that problem is not in js-dos. Some old games of them cannot response mouse down and mouse up too fast, so I have to add timeout for them. I play old game a lot. The newer game can response it correctly. For example in Chinese, "终极任务" "阿曼斯传说3" "2001特遣队" cannot response event correctly. "富甲天下 series" "主题医院" "大明英雄传" work with no wrong. Thank you for taking the time to reply to me. It is a nice project.
