### ISSUE TITLE
Pre-Built Version

### ISSUE THREAD

**Issue by Balrog85** [caiiiycuk/js-dos.com#55]
Hi.  I don't have access to a Linux machine that I can run the bootstrap project on at the moment.  Is there a pre-built version or something that I can just upload straight to my website?  I really want to upgrade to v6.22 so I can make use of the saved data feature you added.

**Comment by caiiiycuk** [comment]
Sure just open releases on main github page and diwnload latest version

вс, 7 апр. 2019 г., 2:54 Balrog85 <notifications@github.com>:

**Comment by Balrog85** [comment]
Oh, I'm an idiot, I completely missed the releases section.  Thanks :)

Edit: The persistent save data is working perfectly.  Great job and thanks!

**Comment by caiiiycuk** [comment]
Cool!
