### ISSUE TITLE
Feature request: multiplayer support

### ISSUE THREAD

**Issue by letsdig** [caiiiycuk/js-dos.com#57]
Hello, great job, would be awesome let users to create their room and share the game with their friends, or just a bridge to make possible a multiplayer game when the game got the feature.

**Comment by kalee** [comment]
Is multiplayer something planned for the future, or would this be something done in a forked release?

**Comment by caiiiycuk** [comment]
HI, for sure you can do it in forked version. For js-dos, I doing a big refactoring that will help me to add features easily. Network support is what everybody wants, so I will look on it at some point. But, for now I still have more basic task. So, I don't know when this happen.

**Comment by caiiiycuk** [comment]
Related to #108

**Comment by caiiiycuk** [comment]
Done in #108
