### ISSUE TITLE
Usage on electron

### ISSUE THREAD

**Issue by btzr-io** [caiiiycuk/js-dos.com#58]
I can't get this to work with [electron](https://github.com/electron/electron).
I tried to follow the react [example](https://github.com/caiiiycuk/js-dos#react-component-typescript), but I keep getting some errors.

**Here is the log:**

I guess this error is about the storage of [user progress](https://github.com/caiiiycuk/js-dos#store-user-progress-between-sessions),
but I'm not sure why it fails since electron supports the IndexDB api:

https://github.com/caiiiycuk/js-dos/blob/a5673922598aaea6d1015d09ebaee6060f4fd1ca/js-dos-ts/js-dos-cache-db.ts#L20-L23

```
ERR! Can't initalize cache, cause: Can't open cache database
```
Looks like the extraction works :+1: 
```
js-dos.js:1 [INFO] Resolving DosBox 2.5%
js-dos.js:1 [INFO] Resolving DosBox 42.7%
js-dos.js:1 [INFO] Resolving DosBox 82%
js-dos.js:1 [INFO] Resolving DosBox 82%
js-dos.js:1 [INFO] Resolving DosBox 84.6%
js-dos.js:1 [INFO] Resolving DosBox 100%
js-dos.js:1 [INFO] Resolving DosBox 100%
js-dos.js:1 [INFO] Resolving DosBox 100%
js-dos.js:1 [INFO] DosBox resolved
```
What's this about?
```
js-dos.js:1 Uncaught TypeError: e is not a constructor
    at e.ondosbox (js-dos.js:1)
    at js-dos.js:1
    ...
```

Anyway thanks for this awesome project :v:

**Comment by btzr-io** [comment]
Small update, Looks like I can't use `indexDB.open`  
because there is an electron bug and always trows and  error:
``` DOMException: Internal error opening backing store for indexedDB.open. ```

Is there a way to use `js-dos` without indexDB ?

**Comment by btzr-io** [comment]
I should probably rename this issue ^^

**Comment by btzr-io** [comment]
Is this related to the indexDB issue ?
``` JS
    js-dos.js:1 Uncaught TypeError: e is not a constructor
    at e.ondosbox (js-dos.js:1)
    at js-dos.js:1
```

**Comment by caiiiycuk** [comment]
Hi, @btzr-io. Can you tell how you fix this?

**Comment by btzr-io** [comment]
@caiiiycuk I didn't fix it, but it's an external bug on the electron app I'm working so is not related to this project

**Comment by taigrr** [comment]
@btzr-io Did you ever figure it out? Now I'm running into it.

**Comment by taigrr** [comment]
For anyone else who runs into this, [take a look at this page.](https://www.electronjs.org/docs/faq) You need the following four lines above your include to the js-dos code and it will work:

```
window.nodeRequire = require;
delete window.require;
delete window.exports;
delete window.module;
```
