### ISSUE TITLE
Screenshot resolution

### ISSUE THREAD

**Issue by Holdberg** [caiiiycuk/js-dos.com#59]
Hello!
When I try to get a screenshot (right mouse button on canvas -> save the image) on dosify.me (22.28 version, i suppose) - I get an image with a resolution of 320x200.
If I remember correctly - in the 22.19 version of js-dos, the screenshots was in 640x400 format.
Can I manually set the resolution for screenshots or maybe you can add this feature to the future version?

**Comment by caiiiycuk** [comment]
Image resolution is equal to size of your canvas. So just set canvas width and height to 640x400 and you will get this image. But, actually resolution is always same (== game resolution) bigger screen shots is just up scaling.

**Comment by caiiiycuk** [comment]
So you can just resize 320x200 to 640x400 and will have same results

**Comment by Holdberg** [comment]
If I understand you correctly - the dimension of the saved image will be equal to the width and the height of the canvas(CSS)? Actually it does not work on two of my laptops... Here is a [link](http://s000.tinyupload.com/?file_id=04914471605221734448) to the archive with 2 versions .19 and .28 with the same canvas parameters and the same game - for example, Detroit by Sierra.
In version .19 - right click - save image - screenshot 640x400
In version .28 - rifght click - save image - screenshot 320x200

**Comment by Holdberg** [comment]
Also output image will be different in .19 (640x400) and .28 (320x200) if you remove canvas dimension in html. This i suppose affects the size of screenshot

**Comment by caiiiycuk** [comment]
Hmm, interesting need to check. Thanks. I will be back asap

вт, 18 июн. 2019 г., 0:25 Holdberg <notifications@github.com>:

**Comment by caiiiycuk** [comment]
Now (in v7) ci return screenshot with resolution that match native game resolution
