### ISSUE TITLE
Application Works in Dosbox but Not JS-Dosbox

### ISSUE THREAD

**Issue by KR0SIV** [caiiiycuk/js-dos.com#61]
I'm not sure if there is a configuration change on my end that will fix this or not.
I'm using an application called Quick Yagi 4, which works great in native dosbox.

However, inside JS-Dosbox it locks up as soon as I try to calculate a yagi.
The software can be found here: http://www.hamuniverse.com/quickyagiqy4.html

Steps to re-create issue:

Run setup
     Select VGA
Run QY4
    Select Enter
    Select A
    Select A
    Select M
    Select 3
    Select Y
    Select 3
    Select 5

It is here that it locks up inside js-dosbox

**Comment by caiiiycuk** [comment]
It works for me, however it looks very slow. Or maybe I don't understand what this software do.

![output](https://user-images.githubusercontent.com/1727152/62641057-0cde9b80-b96d-11e9-9299-f4a7cf595c45.gif)

**Comment by KR0SIV** [comment]
> It works for me, however it looks very slow. Or maybe I don't understand what this software do.
> 
> ![output](https://user-images.githubusercontent.com/1727152/62641057-0cde9b80-b96d-11e9-9299-f4a7cf595c45.gif)

It certainly does appear to be working for you. How might I go about fixing this? I'm not sure where I can pull logs that might show what is happening.

**Comment by caiiiycuk** [comment]
Did you use latest version? Can you add the link to page?

**Comment by KR0SIV** [comment]
I used the boot strap https://js-dos.com/

**Comment by caiiiycuk** [comment]
I mean do you have you own web site where you put this program?

**Comment by KR0SIV** [comment]
Yes, I was running it from a digital ocean droplet.
I'll start it up in a screen session so you can take a look.

http://kr0siv.com:8080

**Comment by caiiiycuk** [comment]
Sorry man, I lost the last message. Is it still actual for you?
