### ISSUE TITLE
JS DOS - keyboard does not work in iframe

### ISSUE THREAD

**Issue by perelowski** [caiiiycuk/js-dos.com#62]
Hello,

I have played around with a new version of JS Dos. I have tried to embed Civilization, my favorite childhood game, to my blog - in the IFRAME. I used the 'standard' HTML code shown on the official JS Dos project page. You can check it here:

https://zmozgu.net/cywilizacja-teraz-mozesz-grac-w-przegladarce/

Unfortunately, when the game is in the IFRAME, the keyboard does not work. You cannot enter any options etc. 

However, if you open the iframe source URL directly, it works perfectly:

https://zmozgu.net/civ.html

The console does not show any errors. What am I doing wrong?

**Comment by caiiiycuk** [comment]
Thanks for reporting, will look into in

**Comment by caiiiycuk** [comment]
Ok, you just need to set focus on your iframe. You can do it with javascript
```
document.getElementsByTagName('iframe')[1].focus()
```

By evaluating this snippet in console fix civilization on your site. However this should work automatically when you mouse click on iframe. For example on empty page it works perfectly

```
<html>
<body>
<iframe 
    style="display: block; margin-left: auto; margin-right: auto;" 
    scrolling="no" 
    msallowfullscreen="true" 
    width="100%" 
    height="100%" 
    allowfullscreen="true" 
    frameborder="0" src="https://zmozgu.net/civ.html" 
    allowtransparency="true" 
    webkitallowfullscreen="true" 
    mozallowfullscreen="true">
</iframe>
</body>
</html>
```

But not on your page, I think it because you have some mouse listener that prevent default behaviour of mouse click (e.preventDefault). You can fix this listener, or fix focus iframe directly.

Please reopen this issue if this not work for you.

**Comment by perelowski** [comment]
Hello,

I just tried the HTML code you provided in the HTML sandbox JSFiddle:

https://jsfiddle.net/avh0927e/

After the page loads, press "Run" in the top-left corner to launch the code.

 - I copied and pasted the code to test it. The issue happens there as well. Despite clicking in the iframe, the game does not react to keyboard. 

The same code works on https://codepen.io. I am really puzzled.

**Comment by caiiiycuk** [comment]
Because it's not problem of js-dos itself, it's more about "host" page how it is implemented.
```
document.getElementsByTagName('iframe')[1].focus()
```
Works for your original page at least for me.

![output](https://user-images.githubusercontent.com/1727152/62779118-7a5d0a00-badc-11e9-91e2-f566e43846b2.gif)

**Comment by perelowski** [comment]
Thanks for a quick reply. I have put the code you mentioned in the header, but the JS Console is giving me this: "Uncaught TypeError: Cannot read property 'focus' of undefined"
...and still cannot get it to work :\

The link to page is here: https://zmozgu.net/cywilizacja-teraz-mozesz-grac-w-przegladarce/

**Comment by perelowski** [comment]
Case solved. I added to the <iframe> tag the following:
<iframe onload="this.contentWindow.focus();" (.......)
and it works!
