### ISSUE TITLE
Would it be possible to provide instructions on installing Windows 3.1

### ISSUE THREAD

**Issue by lexterror** [caiiiycuk/js-dos.com#64]
I would like to know if you could provide instructions on installing windows 3.1 on js-dos.

Thank you.

**Comment by caiiiycuk** [comment]
Mmm, what exactly you want? May be this can help https://www.howtogeek.com/230359/how-to-install-windows-3.1-in-dosbox-set-up-drivers-and-play-16-bit-games/
