### ISSUE TITLE
Step by step guide?

### ISSUE THREAD

**Issue by developmentsedge** [caiiiycuk/js-dos.com#65]
I am new to all of this and I am having a difficult time getting this setup. I have a WordPress website, and I would like to add js-dos to my server and then add the html code to a page and be able to have the various DOS games I own play, but after many attempts I cannot seem to get it to work.

Is there anyone that can write a layman's easy install and setup guide for this scenario? For example, how to compile the files correctly, where to place them within the WordPress server file structure, where to place the game files, ect...

Any help would be greatly appreciated! Thanks

**Comment by caiiiycuk** [comment]
Hi. What is your web server configuration? Did you tried to put js-dos html template on your site? 
http://js-dos.com/#js-dos-622-html-template

**Comment by developmentsedge** [comment]
Hi caiiiycuk,

I am using WordPress hosting through DreamHost called DreamPress and they do not give us all of the server configuration details. However, I can make many configuration changes via request to DreamHost if needed. I can also make changes using a user.ini file and I have access to sftp, MYSQL, and .htaccess, etc. 

I copied the HTML code on the link you sent me and put it into a blank page on my website and it worked just fine. 

After looking the HTML code over, I noticed I could simply upload a ROM to my server and then use the call to the folder on my server and the game would load and work.

For example:
fs.extract("/Games/doom.zip").then(() => {
        main(["-c", "DOOM.EXE"])

So is the point of the js-dos project to call the .js from your site and then simply call and extract the ROM's from our own websites, or do you intend for us to install the js-dos onto our own servers?

If we are to install js-dos onto our own servers, can you please explain the process?

Please advise.

Thank you

**Comment by caiiiycuk** [comment]
Hi, you can do in both ways. Probably easiest solution is to upload only ROM to your site, and refer js-dos scripts from js-dos.com. I see only one problem - js-dos scripts can be updated and it's possible to have some breaking changes in API that can stop your site from working.

Another way - is to copy also js-dos scripts on your site and use it. js-dos is server less solution, you need only static web page hosting to run it. You can download latest version from releases page here on github. You need to extract release on your website and then change url to js like this
http://js-dos.com/#js-dos-622-faq-how-to-change-url-to-wdosboxjs

**Comment by developmentsedge** [comment]
Hi @caiiiycuk 

Thank you! I greatly appreciate your feedback. This has cleared up my confusion, and now I can make the best choice on how I am going to set up my web-page. :)
