### ISSUE TITLE
Interact with filesystem while running

### ISSUE THREAD

**Issue by matthewturk** [caiiiycuk/js-dos.com#66]
It would be really excellent to be able to interact with the filesystem in a running instance.  I can see that creating new mount points that are persistent is not accessible (as the syncTime is checked before allowing that) but is it feasible to ephemeral files into a running instance?

**Comment by caiiiycuk** [comment]
Hi, you can use filesystem api that emscripten provides. https://emscripten.org/docs/api_reference/Filesystem-API.html Is it what you are looking for?
