### ISSUE TITLE
Arrow keys with Czech keyboard layout

### ISSUE THREAD

**Issue by CliveDent** [caiiiycuk/js-dos.com#68]
Hello. I had this issue with the desktop version of DosBox too. I don't know why but while using Czech keyboard layout all the keys work fine except for the arrow keys (up, down, left, right). If I switch to US layout, it works normally.

**Comment by caiiiycuk** [comment]
Js-dos is just a port of Dosbox to js, so any bugs that exists in desktop version will exists in js version too. Just for clarification, you said that only arrow keys didn't work? Pls, share link to sample game that have this issue.

**Comment by CliveDent** [comment]
Thank you for your quick reply. I thought desktop version already fixed it.
Here is a link to sample game:

http://princess.tknp.cz/

**Comment by caiiiycuk** [comment]
Do you know ticket, or changset where desktop bug was fixed?

**Comment by CliveDent** [comment]
Unfortunately, I don't. But I tried to remember why does it work in my desktop Dosbox. It was very frustrating at the time but now it's fine. Then I remembered that someone said it was actually fault of SDL...

**Comment by rrodrigofranco** [comment]
Hey CliveDent,
Were you able to fix the problem of the game's movements?
Because I can't move the princess in your sample

**Comment by caiiiycuk** [comment]
@rrodrigofranco which browser do you use, I tried game and it works or me

**Comment by caiiiycuk** [comment]
Need to check if this bug also exists in js-dos v7. @CliveDent, can you try to update your sample on js-dos v7?

**Comment by rrodrigofranco** [comment]
@CliveDent I used the opera browser, but I tested it on Microsoft Egde too and it didn't work

**Comment by CliveDent** [comment]
Hello. I just directed people to different website where everything works and is maintained by someone else: [here](https://playclassic.games/games/platform-dos-games-online/play-princess-of-persia-online/).

It seems they are also using jdosbox but I don't know what is different. If I remember correctly, there is some [keyboard layout configuration](https://www.dosbox.com/wiki/KEYB) in dosbox.config that you can try to play with.

**Comment by caiiiycuk** [comment]
Nope, they used different version of dosbox. But don't worry I will release this game as *.jsdos archive in couple of weeks and you will be able to run it with v7 on any place you want.

**Comment by caiiiycuk** [comment]
Just need someone to test how it works with Czech layout.

**Comment by rrodrigofranco** [comment]
@caiiiycuk I tried to run 4d_prince with this same code and was unsuccessful. I will wait for your updates

http://inflacaobr.000webhostapp.com/4d_prince.html

**Comment by caiiiycuk** [comment]
@rrodrigofranco It works for me. Please answer in related ticket
