### ISSUE TITLE
Center Align FullScreen Mode

### ISSUE THREAD

**Issue by developmentsedge** [caiiiycuk/js-dos.com#69]
Hi,

Is there a way to properly center align the fullscreen window when DOSBOX is opened in full screen. I looked at the CodePen Example https://codepen.io/nodws/pen/VWOLPZ and noticed that the fullscreen mode is centered using a CSS line of code:

body {
  text-align: center;
}
As I show in this video example: https://www.screencast.com/t/ISwdlK9x

But is there a way to center align the fullscreen window without having to center all of the text on the screen?

Thanks

**Comment by caiiiycuk** [comment]
Just move `text-align: center` from body to `.dosbox-container`. I am not master of css, so myabe there is a better way. Btw, why I using old version of dosbox?

**Comment by astigmatism** [comment]
I achieved this using a method on the command interface api:

commandInterface.api.requestFullScreen()

**Comment by developmentsedge** [comment]
Hi @caiiiycuk,
That worked! Thank you. I am using the old version for now. Just waiting for your new html code examples before I try coding the new way.

Thanks
