### ISSUE TITLE
PC Speaker sound is distorted

### ISSUE THREAD

**Issue by ZaDarkSide** [caiiiycuk/js-dos.com#72]
PC Speaker sound is distorted.

Here is an example with Emularity:
https://emupedia.net/beta/emuos/vfat/apps/dosbox/index.html?game=19

And here is an example with JS-DOS:
https://emupedia.net/beta/emuos/vfat/apps/dosbox/index.html?gamev2=arkanoid

**Comment by ZaDarkSide** [comment]
Still reproducible with 6.22.44 running wasm sync version.

**Comment by caiiiycuk** [comment]
Fixed in 6.22.48
