### ISSUE TITLE
Cursor jumps to top in lock mode

### ISSUE THREAD

**Issue by caiiiycuk** [caiiiycuk/js-dos.com#73]
Hello! I have tested the new version of js-dos on yet another game - Panzer General:
https://zmozgu.net/pg.html
...and found another interesting behavior. If you click on the game canvas just after it starts, during title screens - when mouse cursor gets locked, the DOS game cursor will always jump to the top of the game canvas after every click.

If you wait with the cursor 'outside' until the DOS game cursor appears on the screen, then click on the game canvas, it will work properly in the game.

This behaviour happens in Chrome 78 and in Firefox 70. In Safari 13 it works fine (all tested on Mac)

**Comment by ZaDarkSide** [comment]
This bug is also confirmed by me.

**Comment by caiiiycuk** [comment]
Not reproduced in v7. Even more works totally fine without locking (autolock: false)
