### ISSUE TITLE
Canvas resized by game once launched to 200p

### ISSUE THREAD

**Issue by maximilien-noal** [caiiiycuk/js-dos.com#78]
Hello,

In my tests, a lot of dos games resize the canvas to something very small.

Here is my current code :

```

<div class='fiche_online online_block'>
    <canvas id="jsdos" width="320" height="200"
        style="border: 0px; border-color: currentColor; display:inline-block; width: 1024px; height: 600px"></canvas>
    <button class="btn_play" onclick="dosbox.fullscreen();">Mettre en plein-écran</button>
    <script type="text/javascript" src="/abw_nx/lib/js/js-dos/js-dos.js"></script>
    <script type="text/javascript">
    Dos(document.getElementById("jsdos"), {
        autolock: true,
        log: (message) => {
            /* désactivé pour de meilleurs perfs */
        },
        onerror: (message) => {
            /* désactivé pour de meilleurs perfs */
        },
        wdosboxUrl: "/abw_nx/lib/js/js-dos/wdosbox-emterp.js"
    }).ready((fs, main) => {
        fs.extract("/abw_nx/lib/data/online/LVDT.zip", "/LVDT").then(() => {
            main(["-c", "cd LVDT", "-c", "LVDT.BAT"]).then((dosbox) => {
                window.dosbox = dosbox;
            });
        });
    });
    </script>
</div>

```

Games tested : "Future Wars : Time Travellers", "Syndicate".

What am I doing wrong ?

**Comment by caiiiycuk** [comment]
Hi! Do you have link for example above?

**Comment by caiiiycuk** [comment]
OT: Instead of wdosbox-emterp.js, I suggest to use just wdosbox.js it's smaller and faster.

**Comment by maximilien-noal** [comment]
wdosbox.js borks the sound (it's very distorted) on my end with Firefox and Chrome.

Trying wdosbox-emterp.js finally fixed it. But yes, that's another issue I should probably report in another thread.

I don't have a link, sadly. I'll try to attach a freeware game to this issue some time soon.

**Comment by caiiiycuk** [comment]
I see. I will check you example asap, I just ask link because css of parent div can affect size of canvas.

**Comment by caiiiycuk** [comment]
Okay, I see what happen. Currently style inside canvas tag is under js-dos/emscripten control, and when dosbox changes video mode it's vanished. Too fix this you need just declare canvas width and height inside <style> tag. Like this:

```
  <style>
    canvas {
      width: 1024px; 
      height: 600px;
    }
  </style>
```

Is it works for you?

**Comment by caiiiycuk** [comment]
I updated documentation, because I am not sure if style attribute will be supported soon.

**Comment by maximilien-noal** [comment]
That fixed it ! Thank you very much ! :D

**Comment by caiiiycuk** [comment]
@maximilien-noal with **6.22.49** you can switch to wdosbox.js, sound problem is solved.

**Comment by maximilien-noal** [comment]
Confirmed fix on my end. You are officially awesome ! :)
