### ISSUE TITLE
Question/help with game: Deluxe Ski Jump 2

### ISSUE THREAD

**Issue by Mtik333** [caiiiycuk/js-dos.com#81]
Hello,
I'm not sure if this kind of question or performance complaint is valid here but I'll at least try, in worst case you'll simply delete/close this issue/question. 

So the game is Deluxe Ski Jump 2: [DSJ2.zip](http://www.mediamond.fi/dsj2/downloads/dsj210.zip). Once I create bootstrap project, everything seems to be fine, but game sadly works very, very slow when it comes to actual gameplay (menus are rather ok). 

I tried using both default js-dos configuration and the one that I use for standard Dosbox and the default one is actually better in browser, but still game is rather unplayable. Is there anything that can be done is this case? Game has no source code released, it's only known it was written in Turbo Pascal but I'm not sure if it's worth mentioning that.

Thanks for reading my question and developing this project.

**Comment by caiiiycuk** [comment]
Hi. You can try to configure the game in this way:
```
 Dos(document.getElementById("jsdos"), {
      wdosboxUrl: 'wdosbox-nosync.js',
      cycles: 'max',
    })
```

Game will work little bit faster, but anyway looks slow. The strange thing is that game didn't waste many CPU time. Need to check what I can do, to fix this game.

**Comment by caiiiycuk** [comment]
Can you confirm that it also works slow in native dosbox? In my case the game speed is almost same when I run it under linux dosbox. Maybe there is some timings issue.

**Comment by caiiiycuk** [comment]
![image](https://user-images.githubusercontent.com/1727152/70400717-e0dc3f80-1a5e-11ea-9d0d-e1f03acdd29e.png)

**Comment by Mtik333** [comment]
Well, I found somewhere this game bundled with DOSBox (0.74-3) and it runs very smoothly. Link to YT video with it (though it might be not very helpful since it's in Polish but link is in description I guess): [DSJ2 for Win10](https://www.youtube.com/watch?v=csWwMDW9kSI).
I'll attach the conf file that this guy created: 
[DSJ.txt](https://github.com/caiiiycuk/js-dos/files/3940650/DSJ.txt)
Here I changed cycles from "max" to 500000, but I'll give it a try by testing OOTB DOSBox as well.

EDIT: Technically, changing core to dynamic seems to be the only option that is needed to make it work, but I'll also check DOSBox on Linux.

**Comment by Mtik333** [comment]
So I did some tests on Lubuntu with DOSBox and it worked fine for me after doing following things:

- autolock (false) for mouse issues
- core (dynamic)
- cycles (500000)
- output (overlay) but it might not have any impact at all

I don't think I changed anything else.

**Comment by caiiiycuk** [comment]
Yeah it works perfectly on `dynamic` core. Unfortunately this core does not supported by js version of dosbox. Because it's used special X86 assembly that not supported by browser. Maybe in future this will be changed

**Comment by Mtik333** [comment]
Ok, thanks for investigation, I hope it will be possible one day.

**Comment by caiiiycuk** [comment]
Now playable! Even if your mobile is not powerful try trubo mode.
https://talks.dos.zone/t/deluxe-ski-jump-aug-31-2000/1841

**Comment by Mtik333** [comment]
> 
> 
> Now playable! Even if your mobile is not powerful try trubo mode.
> https://talks.dos.zone/t/deluxe-ski-jump-aug-31-2000/1841

Hmm, thanks. I tried it, but it seems to be slightly better than previously, however it's still far away from smooth framerate from PC. Tried with but Turbo mode and "standard" mode. Maybe I'm doing something wrong? I don't think my network bandwidth is the issue here.

Oh and by the way, this game was recently released on Android, [link to Google Play](https://play.google.com/store/apps/details?id=fi.mediamond.dsj2) - then I would say that only browser mode is something that anyone would need.

**Comment by caiiiycuk** [comment]
@Mtik333 Can you record video in turbo mode? For me it works totally ok:
https://drive.google.com/file/d/1X2qUYFNBJayH_61Ph-3bCbVrSpNiIyU9/view?usp=sharing

**Comment by caiiiycuk** [comment]
Ohh! I watched video from GP it works really faster. I will look why Turbo mode is not so fast...

**Comment by Mtik333** [comment]
> 
> 
> Ohh! I watched video from GP it works really faster. I will look why Turbo mode is not so fast...

Yeah, exactly. I'm pretty sure it might take some time to find out what is happening, therefore yeah, I'll wait but it will not be a surprise for me if there's nothing more possible to improve here.
