### ISSUE TITLE
Extract multiple zips into same folder

### ISSUE THREAD

**Issue by Violet-CLM** [caiiiycuk/js-dos.com#82]
As noted in the [sources documentation](https://js-dos.com/6.22/docs/api/generate.html?page=js-dos-fs#dosfs-dosarchivesource), "you can’t store different content (from different archives) into one path." But I want to. Attempting to use the same path in multiple list items in `extractAll` fails predictably, as does:
```
fs.extract("foo.zip").then(function () {
fs.lastSyncTime = 0;
fs.extract("bar.zip").then(function () {
```
My use case is replacing specific files from a game without repackaging and reuploading the entire game zip for every changed file. For example, suppose a game has a few dozen required files, plus a bunch of individual level files, `L01.LEV`, `L02.LEV`, `L03.LEV`, and so on. Suppose I have an alternate version of `L01.LEV` that someone created, in a separate zip. I'm looking for a way to run the game using that alternate version of `L01.LEV`, overwriting the copy from the main game zip, but all other files unchanged.

The other possibility that comes to mind is combining the two zips in javascript on the client side, but the js-dos API as described only wants zips from URLs, not from memory, so I'm not sure if that's doable either.

**Comment by caiiiycuk** [comment]
Hi. Currently there is no direct api from js-dos to do this, but you can use [emscripten fs api](https://emscripten.org/docs/api_reference/Filesystem-API.html), like this:
```
Dos(canvas, {
    wdosboxUrl: "https://js-dos.com/6.22/current/wdosbox.js",
}).ready((fs, main) => {
    fs.extract(archive).then(() => {
        // load file by xhr
        // write it to fs using emscripten fs api
        // fs.fs.writeFile
        // and call main
        main([...]).then((ci) => {
            // ...
        });
    });
});
```

Important, fs api availabe under fs property of fs object, e.g. **fs.fs**. In your case `fs.fs.writeFile` should works:
```
fs.fs.writeFile('file', 'foobar');
```

**Comment by Violet-CLM** [comment]
Thanks, I was able to get it working by starting from the `extractAll` source and gradually cutting away everything I didn't need.
