### ISSUE TITLE
Game does not exit properly

### ISSUE THREAD

**Issue by Yoni7** [caiiiycuk/js-dos.com#86]
I have an Angular 9 application which uses `js-dos` package.

This is how use the package:
`require('js-dos');`
`import { DosFactory } from 'js-dos';`
`const Dos = (window as any).Dos as DosFactory;`

```
		const configOptions = {
			wdosboxUrl: 'https://js-dos.com/6.22/current/wdosbox.js',
			cycles: gameInfo.config && gameInfo.config.cycles || 'auto',
			autolock: false,
			// log: (message: string) => { console.log('message', message); },
			// onerror: (err: string) => { console.error('err', err); }
		};

		const dosCanvas = <HTMLCanvasElement>document.getElementById('jsdos');
		Dos(dosCanvas, configOptions).ready((fs, main) => {
			fs.extract(`assets/games/${gameInfo.fileName}.zip`).then(() => {
				main(['-c', gameInfo.runFile]).then((ci) => {
					this.currentGameRunning = ci;
				});
			});
		});
```
(BTW: `log` and `onerror` does not seems to work, that's why it's currently in comment)

When I call `exit()` then there is a console error: `[ERROR] Runtime is still alive!`
The game seems to be close (it stops, but after a minute i can still here the sound of it playing)
It also causes my Angular `input` field to be freeze (user cannot type anything)

This is what i see when game upload:
`[INFO] Resolving DosBox 100%
main-es2015.a49cef9c357cd881cef6.js:1 [INFO] DosBox resolved
main-es2015.a49cef9c357cd881cef6.js:1 [INFO] …ownloading assets/games/dave.zip 67.6%
main-es2015.a49cef9c357cd881cef6.js:1 [INFO] …ownloading assets/games/dave.zip 100%
main-es2015.a49cef9c357cd881cef6.js:1 [INFO] …ownloading assets/games/dave.zip 100%
VM290:9 extracting: 'DAVE.EXE', size: 76586, mtime: 652464400
VM290:9 extracting: 'EGADAVE.DAV', size: 86332, mtime: 652396020
VM290:9 js-dos version 6.22.59 (41e421b7818042bda0cd05c85fd24394)
VM290:9 Copyright 2002-2015 DOSBox Team, 2019 Alexander Guryanov, published under GNU GPL.
VM290:9 ---
VM290:9 CONFIG:Loading primary settings from config file /home/web_user/.dosbox/dosbox-jsdos.conf
VM290:9 MIDI: Opened device:none`

Please advise, Thx

**Comment by caiiiycuk** [comment]
Hi. Thanks for reporting. It could be because there is no valid exit scenario in current implementation. How it's critical for you? I am working on new version of js-dos that will support correct exit too, if you can wait is better to wait. In other case I can try to find workaround for you.

**Comment by Yoni7** [comment]
@caiiiycuk sure i can wait for the next version, when do you expect it to be released?
it seems that after i exit the game, then my Angular application `input` field do not respond.

Also, do you know why `log` and `onerror` does not work? (see details in the first comment)

**Comment by caiiiycuk** [comment]
Unfortunately I can't say when. The changes is very big, it is a reason why I ask if you can wait. I think month or two. 

Regarding to log & onerror, have no idea need to check. I never used this feature :)
Probably the fix should be easy so I will check if I can fix it.

**Comment by shitpoet** [comment]
Not sure it is what Yoni7 wants, but it seems that this completely stops dosbox:
```
ci.simulateKeyEvent(17, true) // Ctrl
ci.simulateKeyEvent(120, true) // F9
ci.simulateKeyEvent(120, false) 
ci.simulateKeyEvent(17, false) 
```
This code sends `Ctrl + F9` to the dosbox, which is a standard shortcut to kill dosbox.

**Comment by caiiiycuk** [comment]
Please use js-dos v7, it supports correct exit
