### ISSUE TITLE
add support for "nosound" in DOSoptions

### ISSUE THREAD

**Issue by Yoni7** [caiiiycuk/js-dos.com#87]
Is it possible to add support for parameter `nosound` in [DOS Options](https://js-dos.com/6.22/docs/api/generate.html?page=js-dos-options) ?

it will be much more convient instead of having to re-create `dosbox.conf`.

**Comment by caiiiycuk** [comment]
yes sure

**Comment by caiiiycuk** [comment]
jsdos v7 now released, nosound: yes will disable all sounds
