### ISSUE TITLE
Is it possible persist data between runs

### ISSUE THREAD

**Issue by yoazmenda** [caiiiycuk/js-dos.com#89]
Is there a was to use JS-dos with some persistence layer? Meaning that I could somehow save the state into the browser local storage and come back to it later?

**Comment by caiiiycuk** [comment]
It work by default if you mount your archive to some folder, not `/`
http://js-dos.com/#js-dos-622-faq-store-user-progress-between-sessions

**Comment by yoazmenda** [comment]
Thanks, very simple.
