### ISSUE TITLE
add f117 :)

### ISSUE THREAD

**Issue by wizzard0** [caiiiycuk/js-dos.com#9]
I'll try to dig it up in my archives probably...

**Comment by caiiiycuk** [comment]
I trying to add this game, but unfortunately the game freezes on start. I will try to fix this soon.

**Comment by wizzard0** [comment]
Great, thanks in advance!

**Comment by ghost** [comment]
> ! can you add turbo pascal also?
> ! i need an IDE

**Comment by caiiiycuk** [comment]
http://js-dos.com/F117A/
