### ISSUE TITLE
js-dos doesn't work with "npm start" (or "yarn start")

### ISSUE THREAD

**Issue by Strahinja** [caiiiycuk/js-dos.com#90]
Steps to reproduce:

1.  `npx create-dosbox myprog myprog.zip`

2. `cd myprog`

3. `yarn`

4. `yarn start`; output:

```
yarn run v1.22.4
warning package.json: No license field
$ http-server
Starting up http-server, serving ./public
Available on:
  http://192.168.0.16:8080
  http://127.0.0.1:8080
Hit CTRL-C to stop the server
[Sun May 10 2020 10:34:27 GMT+0200 (GMT+02:00)] "GET /" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.142 Safari/537.36"
```

5. Open browser, navigate to http://127.0.0.1:8080

Browser reports invalid host response with the code `ERR_INVALID_REDIRECT`

**Comment by Strahinja** [comment]
I'm unsure if I should open this as a separate issue. I managed to at least get js-dos to start loading when included in my statically built Nuxt project, inside an existing statically hosted `/dist` folder, but unfortunately it hangs, leaving the following error in the console:

```
/programi:1 Uncaught (in promise) CompileError: WebAssembly.compile(): expected magic word 00 61 73 6d, found 3c 21 64 6f @+0
/programi:1 Uncaught (in promise) CompileError: WebAssembly.compile(): expected magic word 00 61 73 6d, found 3c 21 64 6f @+0
4171337….js:1 CompileError: WebAssembly.compile(): expected magic word 00 61 73 6d, found 3c 21 64 6f @+0
```

According to [this answer](https://stackoverflow.com/a/42770413/184064), this could indicate that what would normally be a `.wasm` file is somehow loaded as HTML. I presume this is because of Webpack.

I added js-dos with `yarn add js-dos` and I'm loading it with:

```vue
    mounted()
    {
        if (process.client)
        {
            require('js-dos');
            const Dos = window.Dos;

            Dos(document.getElementById('dos-canvas')).ready((fs, main) =>
            {
                fs.extract('/programi/paskal/zvez.zip').then(() =>
                {
                    main(['-c', 'ZVEZ.EXE']);
                });
            });
        }
    },
```

Does js-dos work with Webpack? Should I perform some additional configuration?

**Comment by caiiiycuk** [comment]
Hi. 
**1).**
I checked js-dos using [digger.zip](https://github.com/caiiiycuk/js-dos/files/4607172/digger.zip):
```
npx create-dosbox myprog digger.zip
cd myprog
npm install
npm start
```
It works for me. Btw, you can just server generated public directory to see if it's actually worked. You have network level error, I think it not related to js-dos.

**2).**
This error means, that instantiation of WASM module is failed. At first steps js-dos downloads wasm binary by network, and then tries to instantiate it. You should look into browser Network tab and check state of  `wdosbox.wasm.js`.

Regarding webpack, it should work. But, take in attention that `*.wasm.js` files is actually not js files it's wasm modules, you should provide them as is.

**Comment by Strahinja** [comment]
As far as the original issue **1)** here is concerned, I found a [workaround](https://github.com/http-party/http-server/issues/525), so I am closing this issue. It works if I access `http://127.0.0.1:8080/index.html`, but not `http://127.0.0.1:8080`. I didn't try downgrading to http-server@0.9.0, reportedly that should work as well. My installed version is current, http-server@0.12.3 and it still has the linked issue. This is under Windows 10.

Regarding the point **2)**, I didn't see any `*.wasm(.js)` loading in the Network tab, only `[hash].js` as I am using Nuxt.js which in turn uses Webpack. ~I am looking for a way to use js-dos with Nuxt.js.~

**Edit:** The solution to **2)** was to copy `wdosbox.{js,js.symbols,wasm.js}` to `/static/js` and add the parameter to `Dos()` call:

```javascript
            Dos(document.getElementById('dos-canvas'),
                { wdosboxUrl: '/js/wdosbox.js' }
            ).ready((fs, main) =>
            {
                fs.extract('/programi/paskal/zvez.zip').then(() =>
                {
                    main(['-c', 'ZVEZ.EXE']);
                });
            });
```

**Edit 2:** I also had to modify `.htaccess` on my static host to include:

```apache
  <FilesMatch "\.wasm\.js$">
    ForceType application/wasm
  </FilesMatch> 
```
