### ISSUE TITLE
is there any way to read memory of js-dos in the browser?

### ISSUE THREAD

**Issue by emalron** [caiiiycuk/js-dos.com#91]
Sorry for writing question in Issues.

I'm finding a way to read memory of a game in js-dos which is running in chrome.

to say more detail, I want to read scores in a game playing.
I expected the virtual machine of js-dos existed as an object in the chrome browser.

but I don't know where I started to analyse complex application like js-dos.

so I just started to look around the js-dos objects like fs, dos, em, etc. then I found HEAP8, HEAP16, ...

Did I find right places for the memory of the game playing on js-dos?

**Comment by caiiiycuk** [comment]
Hi you can use any of HEAP8, HEAPU8, HEAP16, ... object. All of them are views over js-dos memory. This memory contains everything including emulator memory and game memory. Using it you definitely can find place that contains score.

**Comment by emalron** [comment]
I'm really appreciated for your answer! your js-dos is awesome.
