### ISSUE TITLE
Keyboard captured when unfocused

### ISSUE THREAD

**Issue by JosephSemrai** [caiiiycuk/js-dos.com#94]
When the canvas element is unfocused, keyboard input continues to still be captured despite the mouse capture being released. 

This presents an issue in many use cases (for example, you cannot CTRL + F on the documentation website as the keyboard is being continuously captured). Is there any way to prevent this (by wrapping in an iframe, etc.) that would work in React?

**Comment by caiiiycuk** [comment]
I think you should define top level keyboard listener and stop event propagation when it's not needed.

**Comment by JosephSemrai** [comment]
I'm able to define a top level keyboard listener, but am unable to direct the input to the component. `stopPropagation()` leads to the initial issue.

Is there a particular way that you would approach this problem with the React/TypeScript example in the documentation (seen below)? I've tried wrapping the component in an iframe to no avail.
```jsx
import React, { useRef, useEffect } from "react";

import { DosFactory } from "js-dos";
require("js-dos");
const Dos = (window as any).Dos as DosFactory;


const JsDos: React.FC = () => {
    const ref = useRef<HTMLCanvasElement>(null);

    useEffect(() => {
        if (ref !== null) {
            const ciPromise = Dos(ref.current as HTMLCanvasElement, {
                wdosboxUrl: "https://js-dos.com/6.22/current/wdosbox.js",
            }).then((runtime) => {
                return runtime.fs.extract("https://js-dos.com/6.22/current/test/digger.zip").then(() => {
                    return runtime.main(["-c", "DIGGER.COM"]);
                });
            });

            return () => {
                ciPromise.then(ci => ci.exit());
            };
        }
    }, [ref]);

    return <canvas ref={ref} />;
}

export default JsDos;```

**Comment by caiiiycuk** [comment]
Now, there is no official way from api side to do it. I only can suggest workaround or hack. Here you can see how emscripten attaches events:
https://github.com/emscripten-core/emscripten/blob/master/src/library_sdl.js#L1361
And here how it process `recievEvent`
https://github.com/emscripten-core/emscripten/blob/master/src/library_sdl.js#L553

You can access `reciveEvent` through `ci.dos.SDL.receiveEvent`, so you can remove all listener and reattach fixed one.

Btw, looks like iframe trick works, here https://js-dos.com/6.22/examples/?digger I can use `ctrl+f` to search if I select code view.
Source of examples: https://github.com/caiiiycuk/js-dos/blob/js-dos-examples/src/Renderer.tsx

Next version, that I am doing now will have different way to handling events, so you will can just override event handlers with official api.

**Comment by ewiner** [comment]
@JosephSemrai in case this is still useful to you, I found a good workaround/hack by working from @caiiiycuk's tips.

1. Instead of just `<canvas ref={ref} />`, use this:
```jsx
<canvas ref={canvasRef} tabIndex={0} onClick={event => event.target.focus()}/>
```
The `tabIndex=0` attribute allows the canvas to receive focus and keyboard events.  The `onClick` ensures that the canvas gets focus when you click into it.

2. Start dosbox with this extra (undocumented) option: `Dos(canvas, {..., keyboardListeningElement: canvas})`.  Any options passed to `Dos()` get put into the [Emscripten `Module` options](https://emscripten.org/docs/api_reference/module.html).  And you can see where that's read at https://github.com/emscripten-core/emscripten/blob/master/src/library_sdl.js#L1360.
