### ISSUE TITLE
Pixel as a webgl vertex cube/square

### ISSUE THREAD

**Issue by Mitchbux** [caiiiycuk/js-dos.com#95]

**Comment by caiiiycuk** [comment]
Wow, amazing idea. Defenitely DOS pixels can be transformed to cube. Actually I already did in this way with new js-dos (not ready yet). I mean I detached rendering from emulation, and now I can use any rendering front end. But I have only pixel information for each frame as rgba image.

**Comment by caiiiycuk** [comment]
https://js-dos.com/v7/build/examples/threejs.html
