### ISSUE TITLE
No arrow keys in Prince of Persia (Chrome only)

### ISSUE THREAD

**Issue by maximilien-noal** [caiiiycuk/js-dos.com#96]
Chrome ver: 83.0.4103.116
Latest js-dos release used
OS : Windows 10 x64 Desktop
Issue :  Can't move the prince, only the spacebar and F1 seem to do something (displays time left)
Where to reproduce it : here -> https://js-dos.com/Prince%20of%20Persia/
(and other websites)

But my script is below :

``` javascript

<style>
  canvas {
    min-width: 640px;
    height: 97%;
    image-rendering: pixelated;
}
</style>
<div style="width: 640px; height: 480px;">
  <canvas id="jsdos"></canvas>
</div>
<button class="btn_play" onclick="ci.fullscreen();">Fullscreen</button>
<script type="text/javascript" src="/lib/js/js-dos/js-dos.js"></script>
<script type="text/javascript">
        var canvas = document.getElementById("jsdos");
        var isFirefox = navigator.userAgent.toLowerCase().indexOf('firefox') > -1;
        var wDosUrl = "/lib/js/js-dos/wdosbox.js";
        if(isFirefox === true) {
          wDosUrl = "/lib/js/js-dos/wdosbox-emterp.js"; 
        }
	Dos(canvas, {
                cycles: 8000,
		log: (message) => {},
		onerror: (message) => {},
		wdosboxUrl: wDosUrl
	}).ready((fs, main) => {
		fs.extract("https://mysite.com/lib/PoP.zip", "/PoP").then((ci) => {
			main(["-c", "cd pop", "-c", "prince.exe"]).then((ci) => {
				window.ci = ci;
                                DosController.Qwerty(ci.getParentDiv(), ci.getKeyEventConsumer());
			});
		});
	});
</script>

```

Thank you in advance for any insight about this.
Other games using arrow keys work fine (Epic Pinball for example).
The game works fine inside native DOSBox.
Using wdosbox-emterp.js with Chrome does not fix it.

Thiis issue does not affect Firefox (v77.0.1 x64) in any way.

**Comment by maximilien-noal** [comment]
It's also reproductible in Microsoft Edge (both the old one, before the switch to a Webkit engine, and the new one)

**Comment by SenhorFlibble** [comment]
This is because games seem to detect a functional joystick in JS-DOS even if there is none available. Press Ctrl + K to switch PoP to keyboard and it works on the page you linked to. Or set DOSBox to joysticktype=none. You can put in a BAT file that runs like
config -set joysticktype=none
PRINCE.EXE

**Comment by maximilien-noal** [comment]
I already tried joysticktype=none, the problem stays the same.
Thanks for the Ctrl+K tip however, but people using mobile phones can't do that.

**Comment by caiiiycuk** [comment]
@maximilien-noal switch to js-dos v7. Prince Persia already supported and it have mobile controls.

**Comment by caiiiycuk** [comment]
https://talks.dos.zone/t/prince-of-persia-1990/4978

**Comment by maximilien-noal** [comment]
Will do ! Thanks. :)

JS-DOS v7 sounds amazing. I'm really looking forward to JS-DOS v7 being production ready !
