### ISSUE TITLE
Support Question: Share data between sessions and machines

### ISSUE THREAD

**Issue by ncpunt** [caiiiycuk/js-dos.com#98]
I have a dos application that maintains a database, which I would like to share across sessions and machines. The actual implementation of IndexedDB is browser dependent. E.g. Firefox uses a SqlLite database for this purpose, so I could access this directly and somehow sync this (profile) folder in the cloud. But this requires a lot of work on behalf of the user (for every machine). Is there a pure javascript way for fetching the data from an online datastore (e.g. MySQL), store it in the correct IndexedDB slot before launching js-dos. And when the user quits, I must be able to capture this event, in order to update the online data store with the latest changes.

**Comment by caiiiycuk** [comment]
HI. You can store program database between sessions on same browser using js-dos [persist system](http://js-dos.com/#js-dos-622-faq-store-user-progress-between-sessions). To share it between machines you need to replicate indexed db using default browser api. Indexed db will have same name as folder that you used in extract command.

Btw, in next version of js-dos (v7) that currently developed you can solve this much easier.

**Comment by ncpunt** [comment]
Now you made me curious about v7 ! Can you describe this a little.

**Comment by caiiiycuk** [comment]
I am documenting it right now, need to write a lot of things, so it will be quite long. The main features of v7 release is:
- worker support
- proper exit flow
- detach emulator from ui
- more controls over emulator

**Comment by caiiiycuk** [comment]
Read more: https://js-dos.com/v7/build/docs/

I will close this issue. If you have problems please reopen it, or create new. Thanks
