### ISSUE TITLE
Lag in keyboard input

### ISSUE THREAD

**Issue by asturur** [caiiiycuk/js-dos.com#99]
With the test page of digger, created with `npx create-dosbox digger`, by default digger seems to execute at ludicrous speed on a modern macbook.

That was sort of expected by me.

I set cpu cycles to 400 and the game run at normal speed, but the arrow keys have a sensible input lag.
Adding extra cycles do not improve the situation, game start to run faster, but the input is still a bit laggy.

Do you know if it is a known issue?

**Comment by caiiiycuk** [comment]
Can you test v7 integration does it also have lags?
https://dos.zone/en/player/https%3A%2F%2Fdoszone-uploads.s3.dualstack.eu-central-1.amazonaws.com%2Foriginal%2F2X%2F9%2F9ed7eb9c2c441f56656692ed4dc7ab28f58503ce.jsdos

**Comment by caiiiycuk** [comment]
Fixed in v7
